fix/ gallery thumbnail ratio
wix/ricos pull request #1705
Opened 2020-10-29 11:59 UTC by talevy17

2020-12-02 16:16 UTC, shaulgo commented on packages/plugin-gallery/web/src/gallery-viewer.jsx
> +    let height;
```suggestion
    let height = 305;
```

2020-12-02 16:22 UTC, shaulgo requested changes

2020-12-02 16:22 UTC, shaulgo commented on packages/plugin-gallery/web/src/gallery-viewer.jsx
> +        height = this.props.isMobile ? Math.floor((width * 2) / 3) + 92.5 : Math.max(height, 585);
is mobile needed?

2020-12-02 16:22 UTC, shaulgo commented on packages/plugin-gallery/web/src/gallery-viewer.jsx
> +      mobileParams = { ...mobileParams, arrowsSize: 20, imageMargin: 0 };
```suggestion
      mobileParams.arrowsSize = 20;
      mobileParams.imageMargin = 0;
```

2020-12-02 16:22 UTC, shaulgo commented on packages/plugin-gallery/web/src/gallery-viewer.jsx
> +          : mobileParams;
```suggestion
	if (styleParams.galleryLayout === GALLERY_LAYOUTS.THUMBNAIL) {
	mobileParams.thumbnailSize = 90;
	}
```

2020-12-03 13:15 UTC, talevy17 commented on packages/plugin-gallery/web/src/gallery-viewer.jsx
> +        height = this.props.isMobile ? Math.floor((width * 2) / 3) + 92.5 : Math.max(height, 585);
yes, the 2:3 ration (+95) is relevant for mobile only, on Desktop we want to have enough height to show the image properly and not cut it (that's why the Math.max is there)

2020-12-10 12:59 UTC, shaulgo approved these changes

2021-04-01 07:32 UTC, merged