[undo-redo] fix: plugin customisations support
wix/ricos pull request #1847
Opened 2020-12-09 16:50 UTC by talevy17

2020-12-17 16:18 UTC, shaulgo requested changes

2020-12-17 16:18 UTC, shaulgo commented on packages/editor-common/web/src/Utils/handleUndoRedoCommands.ts
> +    if (key in replaceableEntitiesMap && currentEntity) {
isBlockInContent(contentState, block) && isBlockInContent(newContentState, block) && isBlockTypeUndoFix(block)

2020-12-17 16:18 UTC, shaulgo commented on packages/editor-common/web/src/Utils/handleUndoRedoCommands.ts
> +      if (!isEqual(currentData, undoneData)) {
else if

2020-12-17 16:18 UTC, shaulgo commented on packages/editor-common/web/src/Utils/handleUndoRedoCommands.ts
> +      key,
no need for key

2020-12-17 16:18 UTC, shaulgo commented on packages/editor-common/web/src/Utils/handleUndoRedoCommands.ts
> +
const dataFixers = {
IMAGE_TYPE: (currentData, undoneData) => { ...; return ({...})},
}
return dataFixers[type]?.(currentData, undoneData);

2021-01-07 10:30 UTC, maimonav commented on packages/editor-common/web/src/Utils/handleUndoRedoCommands.ts
> +const TABLE_TYPE = 'table';
You can import from all types from `ricos-content`/`wix-rich-content-common` packages.

2021-01-07 11:00 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/handleKeyCommand.js
> +      return 'handled';
Suggestion: I would have keep the same logic here.
delete this if, and let the line below do the trick.
`else {
      newState = customHandlers[command](editorState, event);
    }`
Of course, you will need to change the behaviour to return editorState and not call setEditorState within the handler.

2021-01-07 11:30 UTC, maimonav commented
Is there a reason for the larger bundle? or will it be corrected when you merge with master?

2021-01-07 11:41 UTC, maimonav commented on packages/editor-common/web/src/Utils/draftUtils.ts
> +    });
There is a bug in Accordion, when you enter text and then hit Undo, the cursor jumps to the beginning of the block, I guess this is why.

2021-01-07 11:57 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/RichContentEditor.tsx
>        ...this.pluginKeyBindings.commands,
It might be more convenient to separate out the constant commands rather than add them here. It can make this function easier to read.

2021-01-07 12:15 UTC, maimonav commented on packages/editor-common/web/src/Utils/draftUtils.ts
> +    });
Might not be connected, we need to check.

2021-01-07 12:33 UTC, maimonav commented on packages/plugin-gallery/web/src/gallery-component.jsx
> +    }
Check it, gallery should have fake loader.

2021-01-07 13:17 UTC, maimonav commented on packages/editor-common/web/src/Utils/handleUndoRedoCommands.ts
> +    newItems[brokenItemIndex] = { ...newItem, itemId, url, metadata, tempData: undefined };
When video in gallery will be supported, should add changes here.

2021-01-07 13:19 UTC, maimonav commented on packages/editor-common/web/src/Utils/handleUndoRedoCommands.ts
> +    }
Add case for `SoundCloud`.

2021-01-07 13:39 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/RichContentEditor.tsx
> +  };
Try return `editorState` than updateEditorState.

2021-01-07 14:07 UTC, maimonav commented on packages/editor-common/web/src/Utils/handleUndoRedoCommands.ts
> +import { EditorState, convertToRaw, convertFromRaw, ContentState } from '@wix/draft-js';
Go over the file and refactor.

2021-01-07 14:12 UTC, maimonav commented on packages/editor-common/web/src/Utils/handleUndoRedoCommands.ts
> +  }
Extract method (Duplicate code from updateUndo...)

2021-01-07 14:16 UTC, maimonav commented on packages/editor-common/web/src/Utils/handleUndoRedoCommands.ts
> +            entityToReplace.shouldKeepSelection = true;
Check if needed.

2021-03-14 11:50 UTC, shaulgo commented on packages/editor-common/web/src/Utils/handleUndoRedoCommands.ts
> +function removeFocus(editorState: EditorState) {
Let's move the draft function to undoRedoDraftUtile.ts

2021-03-14 11:54 UTC, shaulgo commented on packages/editor-common/web/src/Utils/handleUndoRedoCommands.ts
> +function createNewEditorStateWithChangeType(editorState, lastChangeType) {
this can move to where it is used. Or remove it completly

2021-03-14 12:31 UTC, shaulgo requested changes

2021-04-01 13:45 UTC, merged