[link] feat: add support for external link
wix/ricos pull request #1892
Opened 2020-12-21 17:58 UTC by maimonav

Add support for consumers to render their own linkModal, save their data in the linkEntity and dispatch it in viewer `onClick` event.

2020-12-21 21:08 UTC, shaulgo requested changes

2020-12-21 21:08 UTC, shaulgo commented on e2e/tests/text.e2e.js
> +          isExternalModal: true,
I thought this would be a callback that would allow the consumers to render whatever they need.

2020-12-21 21:08 UTC, shaulgo commented on e2e/tests/text.e2e.js
> +          isExternalModal: true,
Am I missing something?

2020-12-21 21:08 UTC, shaulgo commented on e2e/tests/text.e2e.js
> +          isExternalModal: true,
I see you split it to two settings. What do you think about customLinkModal. Also we should probably give it the current data. So user opens it for edit.

2020-12-22 08:41 UTC, maimonav commented on e2e/test-env/src/client/RicosTestApp/editorPlugins.js
> +      const data = await Promise.resolve({ externalData: {} });
Sure.

2020-12-22 08:53 UTC, maimonav commented on e2e/test-env/src/client/RicosTestApp/RicosTestApp.jsx
> +        <RichContentViewer config={{ ...testAppConfig.pluginsConfig }} />
It's just for the test-env, the same thing for RichContentEditor.

2020-12-22 08:55 UTC, maimonav commented on e2e/tests/text.e2e.js
> +          isExternalModal: true,
You are right, let me know when we can talk about it, I have some questions :)

2020-12-22 09:41 UTC, shaulgo commented on e2e/tests/text.e2e.js
> +          isExternalModal: true,
addLink: (saveData) => {
  const data = await renderPanel();
  saveData(data);
}

2020-12-22 11:48 UTC, maimonav commented on e2e/test-env/src/client/RicosTestApp/RicosTestApp.jsx
> +        <RichContentViewer config={{ ...testAppConfig.pluginsConfig }} />
removed.

2020-12-29 13:56 UTC, shaulgo requested changes

2020-12-29 13:56 UTC, shaulgo commented on e2e/test-env/src/client/RicosTestApp/RicosTestApp.jsx
> +    const externalPluginsConfigs = { ...testAppConfig.pluginsConfig, ...nativeFileUploadConfig };
```suggestion
    const customPluginsConfigs = { ...nativeFileUploadConfig, ...testAppConfig.pluginsConfig };
```

2020-12-29 13:56 UTC, shaulgo commented on packages/editor-common/web/src/Utils/draftUtils.ts
> +    createLinkEntityData({
const linkEntityData = ...

2020-12-29 13:56 UTC, shaulgo commented on packages/plugin-link/web/src/toolbar/TextLinkButton.jsx
> +    const shouldRenderModal = !onLinkAdd;
```suggestion
    const isExternalLinkHandling = !onLinkAdd;
```

2020-12-29 13:56 UTC, shaulgo commented on packages/plugin-link/web/src/toolbar/TextLinkButton.jsx
> +          );
put in method

2020-12-29 13:56 UTC, shaulgo commented on packages/plugin-link/web/src/toolbar/TextLinkButton.jsx
> +      onLinkAdd?.(insertExternalLink(getEditorState(), setEditorState));
```suggestion
      onLinkAdd(insertExternalLink(getEditorState(), setEditorState));
```

2020-12-29 13:56 UTC, shaulgo commented on packages/plugin-link/web/src/toolbar/TextLinkButton.jsx
> +      onLinkAdd?.(insertExternalLink(getEditorState(), setEditorState));
onLinkAdd(text, externlLinkData).then(externlLinkData => setEditorState(insertExternalLink(externlLinkData)))

onLinkAdd(data, externlLinkData, externlLinkData => setEditorState(insertExternalLink(editorState, data))))

2020-12-29 13:56 UTC, shaulgo commented on packages/plugin-link/web/src/toolbar/TextLinkButton.jsx
> +      onLinkAdd?.(insertExternalLink(getEditorState(), setEditorState));
onLinkAdd = (text, externlLinkData) => ... return promise(resolve(data))

onLinkAdd = (text, externlLinkData, cb) => ... cb(data)

2020-12-29 15:24 UTC, maimonav commented on packages/editor-common/web/src/Utils/draftUtils.ts
> +    createLinkEntityData({
done.

2020-12-29 15:32 UTC, maimonav commented on packages/plugin-link/web/src/toolbar/TextLinkButton.jsx
> +    const shouldRenderModal = !onLinkAdd;
done.

2020-12-29 15:32 UTC, maimonav commented on packages/plugin-link/web/src/toolbar/TextLinkButton.jsx
> +          );
done.

2021-01-05 14:55 UTC, shaulgo commented on packages/plugin-link/web/src/LinkViewer.jsx
> +    if (componentData?.externalData) {
move here event.preventDefault();

2021-01-05 14:58 UTC, shaulgo commented on packages/editor-common/web/src/Utils/draftUtils.ts
> +export const insertExternalLink = (editorState: EditorState, externalData: ExternalLinkData) => {
ExternalLinkData => any

2021-01-05 15:29 UTC, maimonav commented on packages/editor-common/web/src/Utils/draftUtils.ts
> +export const insertExternalLink = (editorState: EditorState, externalData: ExternalLinkData) => {
Done.

2021-01-05 15:33 UTC, maimonav commented on packages/plugin-link/web/src/toolbar/TextLinkButton.jsx
> +      const externalLinkData = getExternalLinkData(getEditorState());
Done.

2021-01-05 16:37 UTC, merged