Unavailable on oneapp plugin new
wix/ricos pull request #1896
Opened 2020-12-22 13:35 UTC by tamrat-bay

2020-12-27 10:53 UTC, shaulgo requested changes

2020-12-27 10:53 UTC, shaulgo commented on packages/plugin-commons/web/src/Base/createBasePlugin.ts
> +  supportedPluginsOnOneApp?: string[];
supportedBlockTypes

2020-12-27 10:53 UTC, shaulgo commented on packages/plugin-commons/web/src/Base/createBasePlugin.ts
> +          type === UNAVAILABLE_ON_ONEAPP_TYPE ||
delete line

2020-12-27 10:53 UTC, shaulgo commented on packages/plugin-commons/web/package.json
> +    "wix-rich-content-plugin-unavailable-on-oneapp": "8.10.1"
delete line

2020-12-27 10:53 UTC, shaulgo commented on packages/plugin-commons/web/src/Base/createBasePlugin.ts
>          if (config.type === type || config.legacyType === type) {
let type
if (config.type === entityType || config.legacyType === entityType) {
   type = entityType;
else if (!config.supportedPluginsOnOneApp?.includes(type)) {
   type = UNAVAILABLE_ON_ONEAPP_TYPE;
}
const blockRenderObject = type ? {
            component: DecoratedCompWithBase,
            editable: false,
            props: {
              getData: getData(contentBlock, { getEditorState }),
              setData: setData(contentBlock, { getEditorState, setEditorState }),
              deleteBlock: deleteEntity(contentBlock, { getEditorState, setEditorState }),
              type,
            },
          } : null;
return blockRenderObject;

2020-12-27 10:53 UTC, shaulgo commented on packages/plugin-unavailable-on-oneapp/web/src/defaults.ts
> +// import { PaletteColors, ThemeUtils, RicosCustomStyles } from 'wix-rich-content-common';
clean up

2020-12-27 10:53 UTC, shaulgo commented on packages/plugin-unavailable-on-oneapp/web/src/editor.ts
> +/*
cleanup

2020-12-27 10:53 UTC, shaulgo commented on packages/plugin-unavailable-on-oneapp/web/src/icons/CircleInfoIcon.tsx
> +  //     <defs>
cleanup

2020-12-27 10:53 UTC, shaulgo commented on packages/plugin-unavailable-on-oneapp/web/src/modals.ts
> +// This is your plugin's ModalSetting & ModalMap.
remove file

2020-12-27 10:53 UTC, shaulgo commented on packages/plugin-unavailable-on-oneapp/web/src/toolbar/createToolbar.ts
> +import createInlineButtons from './inline-buttons';
check if this is needed

2020-12-27 10:53 UTC, shaulgo commented on packages/plugin-unavailable-on-oneapp/web/src/toolbar/inline-buttons.tsx
> +import { BUTTONS } from 'wix-rich-content-plugin-commons';
check if needed

2020-12-27 10:53 UTC, shaulgo commented on packages/plugin-unavailable-on-oneapp/web/src/toolbar/insert-buttons.tsx
> +// import { DEFAULTS } from '../unavailable-on-oneapp-component';
remove file

2020-12-27 10:53 UTC, shaulgo commented on packages/plugin-unavailable-on-oneapp/web/src/typeMapper.ts
> +import UnavailableOnOneAppViewer from './unavailable-on-oneapp-viewer';
this file is probably not needed

2020-12-27 10:53 UTC, shaulgo commented on packages/plugin-unavailable-on-oneapp/web/src/types.ts
> +export interface UnavailableOnOneAppPluginViewerConfig extends ViewerPluginConfig {
probably don't need

2020-12-27 10:53 UTC, shaulgo commented on packages/plugin-unavailable-on-oneapp/web/src/unavailable-on-oneapp-viewer.tsx
> +        <div className={styles.unaOnOneApp_alert}>
no need for 2 divs

2020-12-27 10:53 UTC, shaulgo commented on packages/plugin-unavailable-on-oneapp/web/src/unavailable-on-oneapp-viewer.tsx
> +    const pluginName = this.getPluginName(this.props.unsupportedType);
```suggestion
    const pluginName = t(this.props.unsupportedType) || t('unsupportedBlockFallback');
```

2020-12-27 10:53 UTC, shaulgo commented on packages/plugin-unavailable-on-oneapp/web/src/viewer.ts
> +  This module exports the required CreatePluginFunction for RicosViewer.
file not needed

2020-12-27 10:53 UTC, shaulgo commented on packages/plugin-unavailable-on-oneapp/web/viewer/package.json
> +{
not needed

2021-01-13 07:12 UTC, closed without merging

2021-01-13 07:25 UTC, tamrat-bay commented
This branch has problems.
The changes were merged in different branch.