[fullscreen] feat: changing bg and icon colors
wix/ricos pull request #1916
Opened 2020-12-27 12:19 UTC by talevy17

2021-01-06 14:43 UTC, talevy17 commented on packages/fullScreen/web/src/icons/expand.tsx
> +    // style="background:#fff"
remove

2021-01-07 10:04 UTC, shaulgo requested changes

2021-01-07 10:04 UTC, shaulgo commented on packages/fullScreen/web/src/icons/expand.tsx
> +import React from 'react';
all icons - the convention for react component files is to start with capital letter.

2021-01-07 10:14 UTC, talevy17 commented on packages/fullScreen/web/src/fullscreen.rtlignore.scss
> +}
yes, gallery adds a drop shadow that Nitzan didn't like

2021-01-07 10:14 UTC, talevy17 commented on docs/docs/ricos/ricos-api.mdx
> +  backgroundColor?: string;
yes it's a color string, I'll add to the docs

2021-01-07 10:15 UTC, talevy17 commented on packages/fullScreen/web/src/InnerFullScreen.jsx
> +  iconsColor: PropTypes.string,
yes it does, in expand mode - I'll change iconsColor to foreground and apply for titles as well

2021-01-10 09:40 UTC, shaulgo approved these changes

2021-01-10 10:34 UTC, merged