[ricos-editor] feat: call RICOS_PUBLISH event
wix/ricos pull request #1990
Opened 2021-01-13 18:27 UTC by maimonav

New EditorEvent: RICOS_PUBLISH.
this event will fire only when old PUBLISH event is done , PUBLISH will be changed to PLUGIN_PUBLISH when after Groups update to the new event.

2021-01-13 19:45 UTC, lxgreen requested changes
please see my comment

2021-01-13 19:45 UTC, lxgreen commented on packages/ricos-content/web/src/consts.ts
> +export const EditorEvents = {
why did you put _editor_ events into the _common_ common? the polls has the editor-common dependency, so there's no problem to import it from there

2021-01-13 21:31 UTC, oded-soffrin commented on packages/ricos-content/web/src/consts.ts
> +export const EditorEvents = {
also please note ricos-content shouldn't have any component related data, this is a pure js package which handles content structure only

2021-01-14 08:33 UTC, maimonav commented on packages/ricos-content/web/src/consts.ts
> +export const EditorEvents = {
<img width="804" alt="Screen Shot 2021-01-14 at 10 31 59" src="https://user-images.githubusercontent.com/26568665/104564615-d02fcd00-5653-11eb-8201-1e41160aded4.png">

That's why..
I wanted to set declare the 'rce:publish' const in a package that will not increase poll's bundle size.

2021-01-14 10:50 UTC, oded-soffrin commented on packages/ricos-content/web/src/consts.ts
> +export const EditorEvents = {
I see. but content is not the place.
Since all the consumers will want to load editorEvents, and won't want to load editor-common as well, maybe we should create yet another package or a lib ?
Just a reminder - our editor have to import it from the same place, and it has to be externalized in order for it to work

I suggest split into two different PR, keep the string for now so groups will be able to update version, and solve the editorEvents location on a different PR

2021-01-14 11:18 UTC, maimonav commented on packages/ricos-content/web/src/consts.ts
> +export const EditorEvents = {
Sure, and I think creating a lib in editor-common of EditorEvents is a good idea.

2021-01-14 18:26 UTC, merged