[plugin-video] feat: settings-modal enable download toggle
wix/ricos pull request #2033
Opened 2021-01-22 15:38 UTC by tamrat-bay

2021-01-31 17:05 UTC, maimonav commented on bundle-analyzer/bundlesSizesBaseline.json
> +  "rcv-with-media-plugins": 549,
Can we avoid this increment?

2021-01-31 17:11 UTC, maimonav commented on packages/common/web/statics/locale/messages_en.json
> +	"VideoSettings_Header":"Video",
Please check why translations does not appear correctly in Settings modal
<img width="1438" alt="Screen Shot 2021-01-31 at 19 11 22" src="https://user-images.githubusercontent.com/26568665/106391876-1cbb2c80-63f8-11eb-8b73-3aaf9ae03e17.png">

2021-01-31 17:22 UTC, maimonav commented on e2e/cypress/support/commands.js
> +
In general , we try to avoid duplicated code.
But in this case, extract method won't do the trick, it needs deeper refactor.
Just a thought...

2021-01-31 17:28 UTC, maimonav commented on packages/plugin-video/web/src/toolbar/inline-buttons.tsx
> +    { keyName: 'sizeSmallRight', type: BUTTONS.SIZE_SMALL_RIGHT, mobile: false },
Good catch!

2021-01-31 17:30 UTC, maimonav commented on packages/plugin-video/web/src/toolbar/videoSelectionInputModal.jsx
> +      // eslint-disable-next-line no-unused-vars
Check if you can revert this.

2021-01-31 17:33 UTC, maimonav commented
Fix conflicts please.

2021-01-31 18:08 UTC, maimonav commented on packages/plugin-video/web/src/video-viewer.jsx
> +    const disableDownload = settings.disableDownload || componentData.config.disableDownload;
Make sure `componentData.config` is not undefined.

2021-01-31 18:12 UTC, maimonav commented on packages/plugin-video/web/statics/styles/video-settings.scss
> +  }
Is all this CSS needed?

2021-01-31 18:15 UTC, maimonav commented on packages/plugin-commons/web/statics/styles/settings-mobile-header.scss
> +}
Just a reminder for you to show me this css changes tomorrow :)

2021-01-31 18:25 UTC, maimonav commented
Make sure new icon & modal settings is wired to ricos-theme.
I would suggest to add customVideo upload functionality to storybook to check it.

2021-01-31 18:32 UTC, maimonav commented on packages/editor-common/web/src/Icons/NotificationIcon.tsx
> +          <path
This might not work well with ricos-theme, please check that the icon's color is overriden.

2021-02-01 07:53 UTC, maimonav commented on packages/plugin-commons/web/src/Modals/SettingsMobileHeader.js
> +      >
What does the var 'isSettingsModal' mean? It's under Modals/Settings**, so it should be always settings modal no?

2021-02-01 07:56 UTC, maimonav commented on packages/plugin-commons/web/src/Base/baseToolbarButton.jsx
> +        : !(activeButton.keyName === keyName && activeButton.isActive));
Please refactor, it's hard to understand.
Plus, `this.props.type === BUTTONS.EXTERNAL_MODAL` is found twice in isActive.
Once, in line 107, and second, in line 104.

2021-02-01 07:59 UTC, maimonav commented on packages/plugin-commons/web/src/Base/baseToolbarButton.jsx
> +
A reminder to understand what this used for. :)

2021-02-01 08:00 UTC, maimonav requested changes
Please follow the comments and make the changes, and talk to me if you need anything.

2021-02-01 08:49 UTC, tamrat-bay commented on packages/plugin-video/web/src/toolbar/videoSelectionInputModal.jsx
> +      // eslint-disable-next-line no-unused-vars
done - the comment is not needed

2021-02-01 09:35 UTC, tamrat-bay commented on packages/plugin-video/web/src/video-viewer.jsx
> +    const disableDownload = settings.disableDownload || componentData.config.disableDownload;
fixed

2021-02-01 09:37 UTC, tamrat-bay commented on packages/plugin-video/web/statics/styles/video-settings.scss
> +  }
deleted - z-index: 6;

2021-02-01 10:33 UTC, tamrat-bay commented on packages/editor-common/web/src/Icons/NotificationIcon.tsx
> +          <path
svg color is now wired to $primary-text-color

2021-02-01 10:39 UTC, tamrat-bay commented on packages/plugin-commons/web/src/Modals/SettingsMobileHeader.js
> +      >
I changed it to "isMediaSettingsModal"

the modal is used in few places and when it is used for
media plugins it should have a different style

2021-02-01 13:31 UTC, tamrat-bay commented on packages/plugin-commons/web/src/Base/baseToolbarButton.jsx
> +
what do you mean?
to add a comment

2021-02-01 14:29 UTC, tamrat-bay commented on packages/common/web/statics/locale/messages_en.json
> +	"VideoSettings_Header":"Video",
fixed

2021-02-01 14:53 UTC, tamrat-bay commented on bundle-analyzer/bundlesSizesBaseline.json
> +  "rcv-with-media-plugins": 549,
I couldn't avoid the increment

2021-02-02 13:57 UTC, maimonav commented on packages/plugin-commons/web/src/Base/baseToolbarButton.jsx
> +  renderVideoSettingsFlag = () =>
Extract method to `shouldRenderButton`.

2021-02-02 13:58 UTC, maimonav commented on packages/plugin-commons/web/src/Base/baseToolbarButton.jsx
> +  renderVideoSettingsFlag = () =>
Before that, check with noam, maybe we can implement this inside video plugin.

2021-02-02 14:20 UTC, maimonav commented
Check with Noam about baseToolbarButton, if it can be implemented from video, if not, refactor baseToolbarButton as we talked.

2021-02-03 12:04 UTC, maimonav commented on CHANGELOG.md
> +  - [#2033](https://github.com/wix-incubator/rich-content/pull/2033) add settings-modal enable download toggle
Please rewrite it to something more understandable, so consumers will understand what this new feature is.
Something like: 'added new settings panel for custom videos with download toggle'

2021-02-03 12:04 UTC, maimonav approved these changes
Please rewrite changelog

2021-02-17 15:03 UTC, shaulgo requested changes

2021-02-18 08:55 UTC, tamrat-bay commented on packages/plugin-commons/web/src/Base/toolbars/createAtomicPluginToolbar.jsx
> +          return null;
done

2021-02-18 09:37 UTC, tamrat-bay commented on packages/plugin-video/web/src/toolbar/video-settings.tsx
> +  const onCancelClick = () => helpers.closeModal?.();
I used it because the type of 
heleprs.closeModal is : (() => void) | undefined '
And I got TS error that the func is possibly 'undefined'

2021-02-18 09:37 UTC, tamrat-bay commented on packages/plugin-video/web/src/toolbar/video-settings.tsx
> +    helpers.closeModal?.();
done

2021-02-18 09:37 UTC, tamrat-bay commented on packages/plugin-video/web/src/toolbar/video-settings.tsx
> +        <React.Fragment>
done

2021-02-18 10:07 UTC, tamrat-bay commented on packages/plugin-commons/web/src/Base/baseToolbarButton.jsx
> +    const isActive =
remove active state

2021-02-23 10:11 UTC, tamrat-bay commented on packages/editor-common/web/src/Components/InfoIcon.jsx
> +    isNotification: PropTypes.bool,
Remove

2021-02-28 10:27 UTC, shaulgo approved these changes

2021-02-28 10:27 UTC, shaulgo commented on packages/plugin-video/web/src/toolbar/video-settings.tsx
> +  const disableDownload = settings.disableDownload || componentData?.config?.disableDownload;
config is generally for the wrapper data (alignment, size...). In the new schema we will stick to this better. 
```suggestion
  const disableDownload = settings.disableDownload || componentData?.disableDownload;
```

2021-02-28 10:42 UTC, merged