[link] fix: href usage
wix/ricos pull request #2038
Opened 2021-01-24 11:36 UTC by maimonav

2021-01-24 16:43 UTC, maimonav commented on packages/viewer/web/src/getPluginViewers.jsx
> +  isSSR,
```suggestion
  isSSR,
```

2021-01-25 15:54 UTC, shaulgo requested changes

2021-01-25 15:54 UTC, shaulgo commented on packages/plugin-image/web/src/image-viewer.jsx
> +      this.scrollToAnchor(e);
no need to pass event through 3 functions.

2021-01-25 15:54 UTC, shaulgo commented on packages/viewer/web/src/getPluginViewers.jsx
> +  getUrlWithAnchorTag = anchorString => {
is this used? 
Also duplicate.

2021-01-25 15:54 UTC, shaulgo commented on packages/plugin-link/web/src/toolbar/UrlLinkButton.jsx
> +    anchorScroll(e, element);
Was there need to preventDefault here? What's UrlLinkButton?

2021-01-25 15:54 UTC, shaulgo commented on packages/plugin-link/web/src/LinkViewer.jsx
> +    }
Will this work?
`return url ? normalizeUrl(url) : `#viewer-${anchor}``

2021-01-25 16:01 UTC, maimonav commented on packages/viewer/web/src/getPluginViewers.jsx
> +  getUrlWithAnchorTag = anchorString => {
Oops, it should have been deleted.

2021-01-25 16:03 UTC, maimonav commented on packages/plugin-link/web/src/LinkViewer.jsx
> +    }
I think so, as long as we have at least one of (url,anchor) defined.

2021-01-25 17:43 UTC, shaulgo commented on packages/common/web/src/Utils/anchor.ts
>    element.style.marginTop = null;
const {marginTop, paddingTop} = element.style;

2021-01-25 17:47 UTC, shaulgo approved these changes

2021-01-26 12:05 UTC, merged