Feat/EditorAPI-v2
wix/ricos pull request #2044
Opened 2021-01-25 11:35 UTC by maimonav

2021-03-14 13:04 UTC, oded-soffrin commented
@shaulgo can we prioritize this PR review?

2021-03-19 12:35 UTC, oded-soffrin commented
@shaulgo ?

2021-03-24 11:26 UTC, shaulgo requested changes

2021-03-24 11:26 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/EditorCommands.ts
> +      settings?: { forceSelection?: boolean; isRicosSchema?: boolean }
Let's try to remove forceSelection.

2021-03-24 11:26 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/EditorCommands.ts
> +      if (createPluginData) {
no need for this

2021-03-25 11:01 UTC, shaulgo requested changes

2021-03-25 16:35 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/EditorCommands.ts
> +        if (pluginData) {
Done.

2021-03-25 16:35 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/EditorCommands.ts
> +      if (createPluginData) {
Done.

2021-03-25 16:36 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/EditorCommands.ts
> +    updateBlock: <K extends keyof PluginsDataMap>(
Done.

2021-03-25 16:36 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/EditorCommands.ts
> +      if (createPluginData) {
Done.

2021-03-25 16:36 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/EditorCommands.ts
> +      settings?: { forceSelection?: boolean; isRicosSchema?: boolean }
Done.

2021-03-25 16:36 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/EditorCommands.ts
> +    getSelectedBlockKey: () =>
Done.

2021-03-25 16:36 UTC, maimonav commented on packages/common/web/src/types/pluginTypes.ts
> +Record<string, any> | undefined;
Removed.

2021-03-30 12:11 UTC, shaulgo requested changes

2021-03-30 12:11 UTC, shaulgo commented on packages/ricos-editor/web/src/RicosEditor.spec.tsx
> +    ricosEditor.getEditorCommands().insertDecoration(type, newData, settings);
Does this change the whole entity?

2021-03-30 12:11 UTC, shaulgo commented on packages/ricos-editor/web/src/RicosEditor.spec.tsx
> +        ricosEditor.getEditorCommands().setSelection('o12', {});
o12?

2021-03-30 12:11 UTC, shaulgo commented on packages/ricos-editor/web/src/RicosEditor.spec.tsx
> +      });
let's make generic functions
testInlineStyle('bold')
testInlineStyle('underline')
...

2021-04-04 09:57 UTC, maimonav commented on packages/editor-common/web/src/Utils/draftUtils.ts
> +export const updateEntityData = (editorState: EditorState, blockKey: string, data) => {
Removed updateEntityData, added `blockKeyToEntityKey`.

2021-04-04 10:13 UTC, maimonav commented on packages/plugin-commons/web/src/Base/toolbars/createAtomicPluginToolbar.jsx
> +      if (focusedBlock && !isSSR() && window.getSelection?.().isCollapsed) {
Done

2021-04-04 10:19 UTC, maimonav commented on packages/ricos-editor/web/src/RicosEditor.spec.tsx
> +import 'mutationobserver-shim';
Done

2021-04-04 10:21 UTC, maimonav commented on packages/ricos-editor/web/src/RicosEditor.spec.tsx
> +type Settings = { isRicosSchema?: boolean; forceSelection?: boolean };
Done

2021-04-04 10:21 UTC, maimonav commented on package.json
> +		"mutationobserver-shim": "^0.3.7",
Removed.

2021-04-04 10:38 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/EditorCommands.ts
> +type TextBlockType =
Done

2021-04-04 10:45 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/EditorCommands.ts
> +    toggleInlineStyle: (style: InlineStyle): void =>
Tried it, it makes the consumption harder.
User will need to import enum InlineStyle and Do `InlineStyle.Bold` for example.

2021-04-04 12:45 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/EditorCommands.ts
> +      type: K
Yes

2021-04-04 12:49 UTC, maimonav commented on packages/ricos-editor/web/src/utils/editorCommandsUtil.ts
> +  }),
Done.

2021-04-04 12:50 UTC, maimonav commented on packages/ricos-editor/web/src/utils/editorCommandsUtil.ts
> +  },
Done

2021-04-04 12:57 UTC, maimonav commented on packages/ricos-editor/web/src/RicosEditor.spec.tsx
> +    expect(ricosEditor.getEditorCommands().getSelectedBlockData()).toEqual({});
Done.

2021-04-05 07:16 UTC, maimonav commented on packages/ricos-editor/web/src/RicosEditor.spec.tsx
> +      .setSelection(blockKey, isMention(type) ? endOfSelection : selection);
Done.

2021-04-05 07:47 UTC, maimonav commented on packages/ricos-editor/web/src/RicosEditor.spec.tsx
> +        ricosEditor.getEditorCommands().setSelection('o12', {});
Done.

2021-04-05 07:47 UTC, maimonav commented on packages/ricos-editor/web/src/RicosEditor.spec.tsx
> +      });
Done.

2021-04-05 08:05 UTC, maimonav commented on packages/ricos-editor/web/src/RicosEditor.spec.tsx
> +    ricosEditor.getEditorCommands().insertDecoration(type, newData, settings);
It works like it should.
-  if you select partial selection of block - it adds a link on it.
- if you select all block and it contains other links - it overrides them and change the block entity to single link for all block.

2021-04-05 08:11 UTC, maimonav commented on packages/plugin-link/web/src/createLinkData.ts
> +  return pluginData ? convertLinkData(pluginData) : {};
Done

2021-04-06 08:41 UTC, merged