[full-screen] feat: allow expand in innerce images
wix/ricos pull request #2069
Opened 2021-01-31 12:26 UTC by tamrat-bay

2021-02-17 15:39 UTC, shaulgo requested changes
> Comparison bundleSizes:
> Packages that shrank:
> wix-rich-content-plugin-accordion: 167KB => 166KB
> wix-rich-content-plugin-code-block: 175KB => 174KB
> wix-rich-content-plugin-gallery: 436KB => 435KB
> wix-rich-content-plugin-giphy: 165KB => 164KB
> wix-rich-content-plugin-headings: 159KB => 158KB
> wix-rich-content-plugin-line-spacing: 160KB => 159KB
> wix-rich-content-plugin-link-preview: 176KB => 175KB
> wix-rich-content-plugin-link: 163KB => 162KB
> wix-rich-content-plugin-social-polls: 316KB => 315KB
> wix-rich-content-plugin-sound-cloud: 247KB => 246KB
> wix-rich-content-plugin-table: 235KB => 234KB
> 
> Please update the baseline files by running locally "npm run saveBundlesSizesBaseline" and push the changes.

Please update the bundleSizes

2021-02-17 15:39 UTC, shaulgo commented on e2e/tests/media.e2e.js
> +          .click();
1. what does the second click do?
2. The test clicks on the nav-arrow but doesn't check that anything happened?

2021-02-17 15:39 UTC, shaulgo commented on e2e/tests/media.e2e.js
> +        cy.get('[data-hook=ricos-viewer] [data-hook=item-wrapper]', {
Please fix other places with the specific selectors. Like this one #pgiea8ec1609e052b7f196935318316299d_1

2021-02-17 16:30 UTC, tamrat-bay commented on e2e/tests/media.e2e.js
> +          .click();
fixed

2021-02-17 16:30 UTC, tamrat-bay commented on e2e/tests/media.e2e.js
> +        cy.get('[data-hook=ricos-viewer] [data-hook=item-wrapper]', {
done

2021-02-18 09:48 UTC, shaulgo requested changes

2021-02-18 10:33 UTC, tamrat-bay commented on e2e/tests/media.e2e.js
>          // cy.eyesCheckWindow({
check if we can uncomment these eye checks

2021-02-18 16:23 UTC, merged