[link] add sponsored val & check box, update rel string with initial …
wix/ricos pull request #2107
Opened 2021-02-07 18:27 UTC by maimonav

- Add Sponsored checkbox.
- Add `sponsored: boolean | undefined` to link data.
- Add ref = 'noopener noreferrer' as default value.
- Add `sponsoredRelToggleVisibilityFn` to `LinkPanelSettings {
  blankTargetToggleVisibilityFn?: (anchorTarget?: AnchorTarget) => boolean;
  nofollowRelToggleVisibilityFn?: (relValue?: RelValue) => boolean;
  sponsoredRelToggleVisibilityFn?: (relValue?: RelValue) => boolean; }`

2021-05-18 15:35 UTC, maimonav commented on packages/editor-common/web/src/Utils/draftUtils.ts
> +        rel: `noopener noreferrer ${rel}`,
```suggestion
        rel,
```

2021-05-18 15:37 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/Toolbars/LinkModal.jsx
This class can be deleted

2021-05-18 15:40 UTC, maimonav commented on packages/plugin-commons/web/src/Base/createBaseComponent.jsx
> +              sponsored,
Delete this changes

2021-05-18 15:40 UTC, maimonav commented on packages/plugin-commons/web/src/Base/toolbars/createAtomicPluginToolbar.jsx
> +            sponsored,
Delete this changes

2021-05-18 17:06 UTC, maimonav commented on packages/plugin-gallery/web/src/components/gallery-controls/gallery-image-settings.js
> +  linkPanelToLink = ({ url, targetBlank, nofollow, isValid, sponsored }) => ({
fix this

2021-05-18 17:07 UTC, maimonav commented on packages/ricos-common/web/src/RicosEngine.tsx
Fix bundle size

2021-05-23 09:44 UTC, shaulgo requested changes

2021-05-23 09:44 UTC, shaulgo commented on packages/editor-common/web/src/Components/LinkComponents/BasicLinkPanel.jsx
> +            onChange={linkPanelValues => onChangeLinkPanel(linkPanelValues)}
```suggestion
            onChange={onChangeLinkPanel}
```

2021-05-23 09:44 UTC, shaulgo commented on packages/editor-common/web/src/Components/LinkComponents/LinkPanel.jsx
> +    this.props.onChange({ ...merge(this.props.linkValues, changes) });
```suggestion
    this.props.onChange(merge(this.props.linkValues, changes));
```

2021-05-23 09:44 UTC, shaulgo commented on packages/editor-common/web/src/Components/LinkComponents/LinkPanel.jsx
> +    const { nofollow, sponsored /*, ugc*/ } = rel || {};
```suggestion
    const { nofollow, sponsored } = rel || {};
```

2021-05-23 09:44 UTC, shaulgo commented on packages/editor-common/web/src/Components/LinkComponents/LinkPanel.jsx
> +              isMobile={isMobile}
NewTabCheckbox doesn't have isMobile. Probably needed in all or none of the checkboxes.

2021-05-23 09:44 UTC, shaulgo commented on packages/editor-common/web/src/Components/LinkComponents/LinkPanel.jsx
> +              t={t}
is needed?

2021-05-23 09:44 UTC, shaulgo commented on packages/editor-common/web/src/Components/LinkComponents/LinkPanelContainer.jsx
> +      unchangedUrl;
```suggestion
      hideUrlInput;
```

2021-05-23 14:07 UTC, maimonav commented on packages/editor-common/web/src/Components/LinkComponents/BasicLinkPanel.jsx
> +        {isMobile && this.renderMobileTitle()}
Always true so I removed it

2021-05-23 14:12 UTC, maimonav commented on packages/editor-common/web/src/Components/LinkComponents/LinkPanel.jsx
> +              isMobile={isMobile}
`isMobile` needed only for checkboxes with tooltips.

2021-05-23 14:12 UTC, maimonav commented on packages/editor-common/web/src/Components/LinkComponents/LinkPanel.jsx
> +              t={t}
Nope

2021-05-23 14:32 UTC, maimonav commented on packages/editor-common/web/src/Components/LinkComponents/BasicLinkPanel.jsx
> +            onChange={linkPanelValues => onChangeLinkPanel(linkPanelValues)}
Done.

2021-05-23 14:34 UTC, maimonav commented on packages/editor-common/web/src/Components/LinkComponents/LinkPanelContainer.jsx
> +      unchangedUrl;
Done.

2021-05-23 14:45 UTC, maimonav commented on packages/editor-common/web/src/Components/LinkComponents/LinkPanel.jsx
> +    const { nofollow, sponsored /*, ugc*/ } = rel || {};
Done.

2021-05-23 14:55 UTC, maimonav commented on packages/editor-common/web/src/Components/LinkComponents/LinkPanel.jsx
> +    this.props.onChange({ ...merge(this.props.linkValues, changes) });
`merge` of lodash makes in-place changes in the destination object, `this.props.linkValues` here, which lead to a weird behavior, so I fixed it by making a new object to be the destination object.

2021-05-23 15:03 UTC, maimonav commented on examples/main/shared/editor/EditorPlugins.tsx
> +    showSponsoredCheckbox: true,
Done.

2021-05-24 09:39 UTC, shaulgo requested changes

2021-05-24 09:39 UTC, shaulgo commented on e2e/tests/__snapshots__/media.e2e.js.snap
> +exports[`plugins > image > should disable image expand #0`] =
please revert

2021-05-24 09:39 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/Toolbars/BlockLinkModal.jsx
>      const { url, anchor, target, rel } = componentLink || {};
```suggestion
    const { url, anchor, target = anchorTaget, rel } = componentLink || {};
```

2021-05-24 09:39 UTC, shaulgo commented on packages/common/web/src/Utils/linkConverters.ts
> +  if (targetBlank) {
check if anchorTarget should be default value of target

2021-05-24 09:39 UTC, shaulgo commented on packages/editor-common/web/src/Components/LinkComponents/MultiSelectLinkPanelDesktop.jsx
> +                onChange={linkPanelValues => onChangeLinkPanel(linkPanelValues)}
```suggestion
                onChange={onChangeLinkPanel}
```

2021-05-24 09:39 UTC, shaulgo commented on packages/editor-common/web/src/Components/LinkComponents/MultiSelectLinkPanelDesktop.jsx
> +              onChange={anchorPanelValues => onChangeAnchorPanel(anchorPanelValues)}
```suggestion
              onChange={onChangeAnchorPanel}
```

2021-05-24 09:39 UTC, shaulgo commented on packages/editor-common/web/src/Components/LinkComponents/MultiSelectLinkPanelMobile.jsx
> +              onChange={anchorPanelValues => onChangeAnchorPanel(anchorPanelValues)}
```suggestion
              onChange={onChangeAnchorPanel}
```

2021-05-24 09:39 UTC, shaulgo commented on packages/editor-common/web/src/Components/LinkComponents/MultiSelectLinkPanelMobile.jsx
> +                onChange={linkPanelValues => onChangeLinkPanel(linkPanelValues)}
```suggestion
                onChange={onChangeLinkPanel}
```

2021-05-24 09:39 UTC, shaulgo commented on packages/editor-common/web/src/Components/LinkComponents/MultiSelectLinkPanelDesktop.jsx
>                <LinkPanel
if super easy to merge mobile and desktop components then do it

2021-05-24 09:57 UTC, maimonav commented on packages/common/web/src/Utils/linkConverters.ts
> +  if (targetBlank) {
Yes

2021-05-24 10:00 UTC, maimonav commented on packages/editor-common/web/src/Components/LinkComponents/MultiSelectLinkPanelDesktop.jsx
> +                onChange={linkPanelValues => onChangeLinkPanel(linkPanelValues)}
Done.

2021-05-24 10:00 UTC, maimonav commented on packages/editor-common/web/src/Components/LinkComponents/MultiSelectLinkPanelDesktop.jsx
> +              onChange={anchorPanelValues => onChangeAnchorPanel(anchorPanelValues)}
Done.

2021-05-24 10:00 UTC, maimonav commented on packages/editor-common/web/src/Components/LinkComponents/MultiSelectLinkPanelMobile.jsx
> +                onChange={linkPanelValues => onChangeLinkPanel(linkPanelValues)}
Done.

2021-05-24 11:34 UTC, maimonav commented on packages/editor-common/web/src/Components/LinkComponents/MultiSelectLinkPanelDesktop.jsx
>                <LinkPanel
Done.

2021-05-24 11:34 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/Toolbars/BlockLinkModal.jsx
>      const { url, anchor, target, rel } = componentLink || {};
Done.

2021-05-24 12:01 UTC, maimonav commented on e2e/tests/__snapshots__/media.e2e.js.snap
> +exports[`plugins > image > should disable image expand #0`] =
Done.

2021-05-25 08:25 UTC, shaulgo requested changes

2021-05-25 08:46 UTC, maimonav commented on packages/common/web/src/Utils/linkConverters.ts
> +  } else return anchorTarget || SELF;
Done.

2021-05-26 13:35 UTC, shaulgo requested changes

2021-05-26 13:35 UTC, shaulgo commented on packages/plugin-button/web/src/components/settings-component.jsx
> +    const { t, shouldShowLink, uiSettings, theme } = this.props;
```suggestion
    const { t, shouldShowLinkPanel, uiSettings, theme } = this.props;
```

2021-05-26 13:35 UTC, shaulgo commented on packages/plugin-link/web/src/toolbar/UrlLinkButton.jsx
> +      rel: `noopener noreferrer ${rel || ''}`.trim(),
fix

2021-05-26 13:35 UTC, shaulgo commented on packages/ricos-content/web/src/normalization/dataNormalizers/linkDataNormalizer.ts
>      target: targetBlank ? '_blank' : anchorTarget || '_self',
```suggestion
    target: targetBlank ? '_blank' : anchorTarget || '_top',
```

2021-05-26 13:35 UTC, shaulgo commented on website/docs/ricos/ricos-api.mdx
> +  nofollowRelToggleVisibilityFn?: () => boolean;
delete

2021-05-26 13:35 UTC, shaulgo commented on website/docs/ricos/ricos-api.mdx
> +Deprecated, please use `showNewTabCheckbox` instead.
```suggestion
*** Deprecated *** please use `showNewTabCheckbox` instead.
```

2021-05-26 13:54 UTC, maimonav commented on packages/plugin-button/web/src/components/settings-component.jsx
> +    const { t, shouldShowLink, uiSettings, theme } = this.props;
Done

2021-05-26 14:03 UTC, maimonav commented on packages/plugin-link/web/src/toolbar/UrlLinkButton.jsx
> +      rel: `noopener noreferrer ${rel || ''}`.trim(),
Done.

2021-05-26 14:06 UTC, maimonav commented on website/docs/ricos/ricos-api.mdx
> +  nofollowRelToggleVisibilityFn?: () => boolean;
Done

2021-05-31 08:57 UTC, shaulgo requested changes

2021-05-31 08:57 UTC, shaulgo commented on packages/common/web/src/Utils/linkConverters.ts
> +export const convertTargetBooleanToString = (targetBlank?: boolean, anchorTarget?: string) => {
unit test

2021-05-31 08:57 UTC, shaulgo commented on packages/plugin-button/web/src/components/settings-component.jsx
> +    };
Move to converters file

2021-05-31 08:57 UTC, shaulgo commented on packages/plugin-link/web/src/LinkComponent.jsx
> +  const componentData = contentState.getEntity(entityKey).getData();
1. check if we can use this line in createLinkPlugin. 
2. delete this file

2021-05-31 08:57 UTC, shaulgo commented on packages/plugin-link/web/src/LinkViewer.jsx
> +      target: anchor ? '_top' : getTargetValue(target),
```suggestion
      target: anchor ? '_self' : getTargetValue(target),
```

2021-05-31 08:57 UTC, shaulgo commented on packages/ricos-editor/web/src/utils/editorCommandsTestsUtil.ts
> +  data1: LinkData.fromJSON({ url: 'www.wix.com', rel: 'nofollow', target: '_self' }),
need to check

2021-05-31 08:57 UTC, shaulgo commented on packages/viewer/web/src/getPluginViewers.jsx
> +            target: '_top',
```suggestion
            target: '_self',
```

2021-06-01 07:20 UTC, maimonav commented on packages/plugin-link/web/src/LinkComponent.jsx
> +  const componentData = contentState.getEntity(entityKey).getData();
Done.

2021-06-01 07:20 UTC, maimonav commented on packages/plugin-link/web/src/LinkViewer.jsx
> +      target: anchor ? '_top' : getTargetValue(target),
Done.

2021-06-01 07:21 UTC, maimonav commented on packages/viewer/web/src/getPluginViewers.jsx
> +            target: '_top',
Done.

2021-06-01 12:47 UTC, shaulgo requested changes

2021-06-01 12:47 UTC, shaulgo commented on packages/common/web/src/test/linkConverters.spec.ts
> +const compare = (relObject1, relObject2) =>
can probably be replaced with toEqual

2021-06-01 13:23 UTC, maimonav commented on packages/common/web/src/test/linkConverters.spec.ts
> +const compare = (relObject1, relObject2) =>
Done.

2021-06-02 13:25 UTC, shaulgo approved these changes

2021-06-03 07:28 UTC, merged