[cplor-picker] fix:mobile style
wix/ricos pull request #2159
Opened 2021-02-17 09:58 UTC by tamrat-bay

2021-02-18 12:20 UTC, tamrat-bay commented on e2e/tests/text.e2e.js
> +      browser: DEFAULT_DESKTOP_MOBILE,
Change to DEFAULT_MOBILE_BROWSERS

2021-02-18 12:21 UTC, tamrat-bay commented on e2e/tests/text.e2e.js
> +    cy.switchToMobile();
move cy.switchToMobile() before th "it"

2021-03-17 13:08 UTC, shaulgo requested changes

2021-03-17 13:08 UTC, shaulgo commented on packages/plugin-commons/web/src/Components/ColorPicker/ColorPicker.jsx
> +      colors.pop();
what does this do? Doesn't look like something that should happen in the render function

2021-03-21 10:18 UTC, maimonav commented on e2e/tests/text.e2e.js
> +    .addColor();
Rename `add color` to `openCustomColorModal`.

2021-03-21 10:29 UTC, maimonav commented on packages/plugin-commons/web/src/Components/ColorPicker/ColorPicker.jsx
> +
Move color's logic to parent component.
Parent in `isMobile` mode will pass array of 5 colors, and 6 colors in desktop.
Make sure to clean all other logic here that related.

2021-03-21 10:42 UTC, maimonav commented on packages/plugin-text-color/web/src/toolbar/TextColorPanel.jsx
> +                <div className={mergedStyles.colorPicker_header}>{t(colorPickerHeader)}</div>
Call `t` function in parent and pass here translated header text.

2021-03-21 10:47 UTC, maimonav requested changes
1. Size of Hex input text.
2. Check Surge, multiple css issues - (reset to default & new color), colors not centered in mobile.
3. Comments from PR.

2021-03-22 10:09 UTC, maimonav approved these changes

2021-03-22 18:01 UTC, merged