[image-plugin] feat: updated settings to have expand and download toggle
wix/ricos pull request #2176
Opened 2021-02-21 13:11 UTC by tamrat-bay

2021-02-22 14:36 UTC, tamrat-bay commented on packages/plugin-image/web/src/toolbar/image-settings.js
> +    const tooltipText = toggleKey === 'isRightClickEnabled' ? this.imgCanBeDownloadedTooltip : null;
move tooltip to data

2021-02-22 14:37 UTC, tamrat-bay commented on e2e/tests/media.e2e.js
> +    it.only('should disable image expand', () => {
done

2021-02-22 14:37 UTC, tamrat-bay commented on packages/plugin-commons/web/statics/styles/input-with-label.scss
> +  margin-left: 4px;
done

2021-02-22 14:37 UTC, tamrat-bay commented on packages/editor-common/web/src/Icons/InfoIcon.tsx
> +  <svg xmlns="http://www.w3.org/2000/svg" {...props} width={24} height={24} viewBox="0 0 24 24">
done

2021-02-22 14:41 UTC, tamrat-bay commented on packages/plugin-image/web/src/image-viewer.jsx
> +      !this.props.componentData.config?.disableExpand && this.handleExpand(e);
done

2021-03-14 13:41 UTC, tamrat-bay commented on packages/plugin-image/web/src/image-viewer.tsx
> +  hasExpand = () => !this.props.componentData.config?.disableExpand && this.props.settings.onExpand;
what about new line between functions

2021-03-14 13:41 UTC, tamrat-bay commented on packages/plugin-image/web/src/toolbar/createToolbar.ts
> +    InsertButtons: createInsertButtons({ t, settings, uiSettings }),
```suggestion
    InsertButtons: createInsertButtons({ t, settings, disableRightClick }),
```

2021-03-14 13:41 UTC, tamrat-bay commented on packages/plugin-image/web/src/toolbar/image-settings.js
> +          style={{ paddingTop: 24 }}
delete

2021-03-14 13:41 UTC, tamrat-bay commented on packages/plugin-image/web/src/toolbar/image-settings.js
> +          tooltipText={tooltipText ? tooltipText : null}
This should probably work
```suggestion
          tooltipText={tooltipText}
```

2021-03-14 13:41 UTC, tamrat-bay commented on packages/ricos-content/web/src/normalization/normalizeInitialState.spec.ts
> +      const actual = normalizeInitialState(imageGalleryContentState, {
beforeEach() {
deepClone imageGalleryCont...
}

2021-03-15 13:16 UTC, tamrat-bay commented on packages/ricos-content/web/src/normalization/normalizeInitialState.spec.ts
> +    let imageGalleryInitialState: DraftContent = imageGalleryContentState;
```suggestion
    let imageGalleryInitialState: DraftContent;
```

2021-03-30 15:23 UTC, shaulgo requested changes

2021-03-30 15:23 UTC, shaulgo commented on website/docs/ricos/ricos-api.mdx
> +#### `disableRightClick` (deprecated) if used the same behavior will remain
```suggestion
#### `disableRightClick` (deprecated)
```

2021-03-30 15:23 UTC, shaulgo commented on website/docs/ricos/ricos-api.mdx
> +`Note disableRightClick?: boolean; is deprecated`
remove this line

2021-03-30 15:23 UTC, shaulgo commented on website/docs/ricos/ricos-api.mdx
> +Disables the mouse right click functionality for the gallery, video and image plugins and also sets the initial download mode for custom videos.
```suggestion
Sets the initial value of disableDownload for image, gallery and video plugins. 
Images - disables right click. 
Video - removes the download option from context menu.
```

2021-03-30 15:23 UTC, shaulgo commented on website/docs/plugins_api/PluginCustomization.md
> +| `disableExpand` (deprecated!) | disables expanding images & fullscreen | false         | No           | viewer (this option is deprecated! if used it will be supported and the same behavior will re
no need to explain deprecated

2021-04-01 09:44 UTC, merged