Truncate docs
wix/ricos pull request #2192
Opened 2021-02-22 19:16 UTC by oded-soffrin

![image](https://user-images.githubusercontent.com/1297297/108757922-28ab9180-7553-11eb-95fb-7292edeee453.png)

2021-02-23 09:05 UTC, mharsat requested changes

2021-02-24 14:47 UTC, oded-soffrin commented on packages/ricos-content/web/src/truncateContent/index.ts
> +  contentState: RicosContent,
removed it, isn't needed here only in common

2021-02-24 14:52 UTC, oded-soffrin commented on packages/ricos-content/web/src/truncateContent/index.ts
> +      const blockWords = block.text.split(' ').filter(x => x !== ' ');
yes indeed!

2021-02-26 14:24 UTC, mharsat approved these changes

2021-02-28 07:09 UTC, merged