Video settings fix config
wix/ricos pull request #2229
Opened 2021-02-28 12:05 UTC by tamrat-bay

2021-03-09 10:21 UTC, tamrat-bay commented on packages/common/web/statics/styles/draftDefault.rtlignore.scss
> +
Remove change

2021-03-09 10:23 UTC, tamrat-bay commented on packages/ricos-content/web/src/normalization/normalizeInitialState.ts
> +  // console.log('new entity:', normalizeEntityMap(entityMap, config, content.VERSION || '0.0.0'));
Remove change

2021-03-30 13:40 UTC, shaulgo requested changes

2021-03-30 13:40 UTC, shaulgo commented on website/docs/plugins_api/VideoPlugin.mdx
> +#### This option is no longer in available, if used the same behavior will remain. disableDownload should be set in the mediaSettings
```suggestion
#### disableDownload should be set in the mediaSettings of the editor.
```

2021-03-30 13:40 UTC, shaulgo commented on packages/viewer/web/src/RichContentViewer.tsx
> +    const disableDownload = uiSettings?.disableDownload ?? uiSettings?.disableRightClick;
```suggestion
    const disableDownload = config[VIDEO_TYPE]?.disableDownload || uiSettings?.disableRightClick;
```

2021-03-30 13:40 UTC, shaulgo commented on packages/viewer/web/src/RichContentViewer.tsx
> +    const disableVideoDownload = config[VIDEO_TYPE]?.disableDownload;
```suggestion
```

2021-03-30 13:40 UTC, shaulgo commented on packages/ricos-common/web/src/RicosEngine.tsx
> +    const disableRightClick = mediaSettings?.disableRightClick ?? disableDownload;
```suggestion
    const disableDownload = mediaSettings?.disableRightClick || mediaSettings?.disableDownload;
```

2021-03-30 14:51 UTC, shaulgo commented on e2e/tests/media.e2e.js
> +    it('should toggle download option', () => {
remove this duplicate

2021-03-30 14:55 UTC, shaulgo approved these changes

2021-03-30 14:55 UTC, shaulgo commented on e2e/tests/media.e2e.js
> +it.skip('add a soundcloud URL', function() {
remove this duplicate

2021-03-30 14:55 UTC, shaulgo commented on packages/viewer/web/src/RichContentViewer.tsx
> +    const disableDownload = config[VIDEO_TYPE]?.disableDownload || uiSettings?.disableRightClick;
```suggestion
    const disableDownload = config[VIDEO_TYPE]?.disableDownload || uiSettings?.disableRightClick || uiSettings?.disableDownload;
```

2021-04-04 08:20 UTC, closed without merging