translations-remount fix
wix/ricos pull request #2259
Opened 2021-03-03 15:02 UTC by justame

2021-03-03 17:40 UTC, shaulgo commented on packages/ricos-viewer/web/src/RicosViewer.tsx
> +import { RicosEngine, shouldRenderChild } from 'ricos-common';
can't we delete the localeStrategy?

2021-03-03 19:37 UTC, oded-soffrin commented on packages/ricos-viewer/web/src/RicosViewer.tsx
> +import { RicosEngine, shouldRenderChild } from 'ricos-common';
Still used in editor

2021-03-03 19:38 UTC, oded-soffrin commented on packages/ricos-viewer/web/src/RicosViewer.tsx
> -    if (this.getLocale() !== 'en') {
@justame no longer needed?

2021-03-03 20:09 UTC, shaulgo commented on packages/ricos-viewer/web/src/RicosViewer.tsx
> +import { RicosEngine, shouldRenderChild } from 'ricos-common';
So we need two places that load the locale?

2021-03-03 20:26 UTC, oded-soffrin commented on packages/ricos-viewer/web/src/RicosViewer.tsx
> +import { RicosEngine, shouldRenderChild } from 'ricos-common';
we don't need two places, but if this is what we want, editor should do what the viewer is doing in this PR before we can delete it.

2021-03-03 20:27 UTC, oded-soffrin commented on packages/ricos-viewer/web/src/RicosViewer.tsx
> -    if (this.getLocale() !== 'en') {
Did you check if it doesn't have performance degradation?

2021-03-03 21:25 UTC, justame commented on packages/ricos-viewer/web/src/RicosViewer.tsx
> -    if (this.getLocale() !== 'en') {
I haven't checked if there is performance degradation.
I did notice that If you change the locale in the runtime the translations do not update, so the viewer will render the initial locale that was defined.
Ricos Viewer(locale:he) => click a button and change locale to en => translations stay hebrew.

2021-03-04 08:20 UTC, oded-soffrin commented on packages/ricos-viewer/web/src/RicosViewer.tsx
> -    if (this.getLocale() !== 'en') {
I understand. Not sure we have such use-case of updating translation in realtime outside the example app, but let's verify the performance before merging

2021-03-04 08:21 UTC, oded-soffrin commented on packages/ricos-viewer/web/src/RicosViewer.tsx
> +import { RicosEngine, shouldRenderChild } from 'ricos-common';
also, I believe the usage in withi18next is not ideal. we had another remount mechanism there, and we wrap the whole editor/viewer with conusmer, instead of creating many small consumers for every place translation is needed

2021-03-07 15:53 UTC, oded-soffrin commented on packages/common/web/src/Utils/withI18n.tsx
> +      const { locale, localeResource } = await this.getResourceByLocale(this.props.locale);
minor: not needed if locale is 'en' (redundant call)

2021-03-08 08:09 UTC, oded-soffrin commented
for visibility, this changes breaks the full screen behavior on viewer, since it's assuming re-mount (see [loadEditorModalAfterLocaleResourceIsLoadedToPreventRemountHackFromBreakingModal](https://github.com/wix/ricos/blob/master/packages/ricos-viewer/web/src/modals/fullscreen/FullscreenProvider.tsx#L57)

There was no test coverage and we only found it in the last minute

@justame to add test on fullscreen in non-english language for viewer
@mharsat do we have a test on non-english for editor modal? in case of similar improvements in the future

2021-03-08 08:10 UTC, oded-soffrin requested changes
Fix full screen in non-english

2021-03-08 09:33 UTC, mharsat commented
@oded-soffrin [render external modal in rtl](https://wixeyes.applitools.com/app/baselines/k~!7f68d511-7055-4f8d-b7ef-aa3fd4767490~!b3e35531-3d00-4ffc-858f-741205599629~!3d5c0fe5-d877-4b23-aea2-a5b6d046d5ef~!148cG7CZUs3TD9yhy5zv2bQq5pXFQjvbygpaXRTI_IU_~!/00000251787171709961/steps/5/edit?accountId=X3Sruf7w5kCEbUEEu1ooeQ~~)

2021-03-09 11:56 UTC, justame commented
All checks are green, should I update the changelog?

2021-03-09 16:04 UTC, merged