[editor-common] anchor - add config to handle element preview
wix/ricos pull request #2293
Opened 2021-03-10 15:30 UTC by noamtwix

2021-03-14 10:53 UTC, shaulgo commented on examples/main/shared/editor/EditorPlugins.tsx
> +    // linkTypes: {
what about docs?

2021-03-14 16:08 UTC, shaulgo requested changes

2021-03-14 16:08 UTC, shaulgo commented on website/docs/plugins_api/LinkPlugin.mdx
> +anchor configuration for customize the preview element that shown in anchor panel.
```suggestion
Anchor configuration to customize the preview elements shown in the anchor panel.
```

2021-03-15 10:47 UTC, noamtwix commented on examples/main/shared/editor/EditorPlugins.tsx
> +    //     previewElement: block => {
send only `anchorType` and `data`

2021-03-17 19:20 UTC, shaulgo commented on website/docs/plugins_api/LinkPlugin.mdx
> +`type` - block type e.g. "atomic", "unstyled
is there need for both anchorType and type? 
Probably anchorType is enough? But in the api it's better called type?

2021-03-17 19:21 UTC, shaulgo commented on website/docs/plugins_api/LinkPlugin.mdx
>  ### `linkTypes`
```suggestion
### `Anchor`
```

2021-03-17 19:24 UTC, shaulgo commented on packages/editor-common/web/src/Components/AnchorComponents/AnchorableElement.jsx
> +    const blockPreviewElement = blockPreview?.({
```suggestion
    const blockPreviewElements = blockPreview?.({
```

2021-03-21 09:17 UTC, merged