[toolbars] - new package toolbars-new
wix/ricos pull request #2328
Opened 2021-03-30 09:28 UTC by noamtwix

2021-05-31 10:16 UTC, maimonav commented on packages/toolbars-new/web/src/Toolbar/buttonsListCreator.js
> +    action: 'Bold',
```suggestion
    action: 'bold',
```

2021-05-31 10:16 UTC, maimonav commented on packages/toolbars-new/web/src/Toolbar/buttonsListCreator.js
> +    action: 'Bold',
And for all the rest..:)

2021-08-02 09:57 UTC, shaulgo requested changes

2021-08-02 09:57 UTC, shaulgo commented on examples/main/package.json
> +    "wix-rich-content-toolbars-new": "8.47.15"
opt-in

2021-08-02 09:57 UTC, shaulgo commented on examples/main/shared/editor/Editor.tsx
> +  TranslationFunction,
cleanup file

2021-08-02 09:57 UTC, shaulgo commented on examples/main/shared/editor/EditorPlugins.tsx
> +  formattingToolbarButtons: [
cleanup

2021-08-02 09:57 UTC, shaulgo commented on packages/common/web/src/types/editorCommandsType.ts
> +  RICOS_INDENT_TYPE,
seprate pr for editor commands

2021-08-02 09:57 UTC, shaulgo commented on packages/editor-common/web/src/Utils/overflowUtils.ts
> +  }
remove safety

2021-08-02 09:57 UTC, shaulgo commented on packages/editor-common/web/src/Utils/overflowUtils.ts
> +export const isElementOutOfWindow = (element: HTMLElement): boolean | number | undefined => {
1. new pr
2. elementOverflowWithEditor => {top:number, bottom:....}

2021-08-02 09:57 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/I18nRichContentEditor.tsx
> +  removeToolbarFocus = () => this.editor.removeToolbarFocus();
not needed for formatting

2021-08-09 10:00 UTC, shaulgo requested changes

2021-08-11 10:57 UTC, shaulgo requested changes

2021-08-11 10:57 UTC, shaulgo commented on packages/ricos-editor/web/src/RicosEditor.tsx
> +import LinkToolbar from './toolbars/LinkToolbar';
dynamic import

2021-08-11 10:57 UTC, shaulgo commented on packages/ricos-editor/web/src/RicosEditor.tsx
> +import LinkToolbar from './toolbars/LinkToolbar';
search for import(

2021-08-11 11:33 UTC, noamtwix commented on packages/editor/web/src/RichContentEditor/I18nRichContentEditor.tsx
> +  getInnerRCERenderedIn = () => this.editor.getInnerRCERenderedIn();
fixed

2021-08-24 08:30 UTC, shaulgo requested changes

2021-08-24 08:30 UTC, shaulgo commented on packages/ricos-editor/web/src/RicosEditor.tsx
> +  setEditor = (ref: RichContentEditor) => {
cleanup

2021-08-24 08:30 UTC, shaulgo commented on packages/ricos-editor/web/src/RicosEditor.tsx
> +        this.setState({ textFormattingToolbarModule });
```suggestion
      ).then({default} => {
        this.setState({ TextFormattingToolbar: default });
```

2021-08-24 08:30 UTC, shaulgo commented on packages/ricos-editor/web/src/RicosEditor.tsx
> +      }
```suggestion
       hideFormattingToolbar = editorCommands.getSelection().getIsCollapsed && editorCommands.hasLinkInSelection();
```

2021-08-24 08:30 UTC, shaulgo commented on packages/ricos-editor/web/src/RicosEditor.tsx
> +      }
and goes into function

2021-08-24 08:30 UTC, shaulgo commented on packages/ricos-editor/web/src/RicosEditor.tsx
> +    const onToolbarButtonClick = (
```suggestion
    const createOnToolbarButtonClick = (toolbarType) => (
```

2021-08-25 13:17 UTC, noamtwix commented on packages/ricos-editor/web/src/RicosEditor.tsx
> +      }
fixed

2021-08-25 13:18 UTC, noamtwix commented on packages/ricos-editor/web/src/RicosEditor.tsx
> +        this.setState({ textFormattingToolbarModule });
fixed

2021-08-25 13:18 UTC, noamtwix commented on packages/ricos-editor/web/src/RicosEditor.tsx
> +  setEditor = (ref: RichContentEditor) => {
fixed

2021-08-29 12:20 UTC, shaulgo commented on examples/main/package.json
> +    "wix-rich-content-toolbars-new": "8.50.2"
we can't have changes in the example app

2021-08-29 12:22 UTC, shaulgo commented on examples/main/shared/editor/Editor.tsx
> +            _rcProps={{ helpers: this.helpers }}
also needs to remove

2021-08-29 14:42 UTC, noamtwix commented on examples/main/package.json
> +    "wix-rich-content-toolbars-new": "8.50.2"
fixed

2021-08-29 14:42 UTC, noamtwix commented on examples/main/shared/editor/Editor.tsx
> +            _rcProps={{ helpers: this.helpers }}
fixed

2021-08-30 12:31 UTC, merged