[file-upload] fix: responsive width style
wix/ricos pull request #2330
Opened 2021-03-30 11:19 UTC by tamrat-bay

2021-04-01 09:21 UTC, tamrat-bay commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
> +  shouldUpdateWidth = () => {
shouldUpdateWidth = (currentWidth)

2021-04-01 09:22 UTC, tamrat-bay commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
> +    if (this.shouldUpdateWidth) {
this.shouldUpdateWidth(currentWidth)

2021-04-19 07:35 UTC, maimonav commented
@tamrat-bay Please update branch from master, to see updated tests results

2021-04-19 07:37 UTC, maimonav commented on bundle-analyzer/bundlesSizesBaseline.json
> +  "wix-rich-content-plugin-file-upload": 270,
Would it be possible to avoid this increment?

2021-04-19 07:45 UTC, maimonav commented on packages/plugin-file-upload/web/statics/styles/file-upload-viewer.scss
> +    border: 1px solid rgba($color: #f64d43, $alpha: 1);
Please Check that it doesn't change anything.

2021-04-19 07:47 UTC, maimonav commented on packages/plugin-file-upload/web/statics/styles/file-upload-viewer.scss
> +
Please check if it's possible to not render the element

2021-04-19 07:51 UTC, maimonav commented on packages/ricos-editor/web/src/RicosEditor.spec.tsx
> +      (global as any).window.ResizeObserver = class {
Check if this can be altered to `(global as any).ResizeObserver ...`

2021-04-19 07:58 UTC, maimonav commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
> +  breakPoints = { firstBreak: 320, secondBreak: 140, thirdBreak: 100 };
`const breakPoints..` oustide of class.

2021-04-19 08:16 UTC, maimonav commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
> +            [this.styles.file_upload_type_icon_second_break]: this.isBreakingPoint(
If you like it,
style={isBreakingPoint(..)?{alignContent:'center'}:{}}
Or
style={isBreakingPoint(..)&&{alignContent:'center'}}

2021-04-19 08:17 UTC, maimonav commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
> +            [this.styles.file_upload_type_icon_second_break]: this.isBreakingPoint(
If you don't change it, change `file_upload_type_icon_second_break` to `file_upload_type_icon_third_break`

2021-04-19 08:25 UTC, maimonav commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
> +  breakPoints = { firstBreak: 320, secondBreak: 140, thirdBreak: 100 };
Change it to `resizeWidths`
resizeWidths = { first: 320,....};

2021-04-19 08:34 UTC, maimonav commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
> +            !this.isBreakingPoint(this.breakPoints.firstBreak) && <DownloadIcon />
Change `isBreakingPoint` `isInWidthRange`

2021-04-19 08:36 UTC, maimonav commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
> +                  [this.styles.displayNone]: this.isBreakingPoint(this.breakPoints.secondBreak),
Do not render component

2021-04-19 08:39 UTC, maimonav commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
>  import classnames from 'classnames';
Make sure to update all break-points to resize width's naming

2021-04-19 08:41 UTC, maimonav commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
> +          [this.styles.file_upload_link_second_break]: this.isBreakingPoint(
Fix this

2021-04-19 08:45 UTC, maimonav commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
> +    const tooltipContent = this.isBreakingPoint(this.breakPoints.firstBreak)
Suggestion: `content={this.isBreakingPoint(this.breakPoints.firstBreak) && componentData.name}`

2021-04-19 08:50 UTC, maimonav commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
>  import classnames from 'classnames';
Add unobserve to componentWillUnmount

2021-04-19 08:50 UTC, maimonav commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
>  import classnames from 'classnames';
Add debounce

2021-04-19 08:58 UTC, maimonav commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
> +                    [this.styles.file_upload_extension_first_break]: this.isBreakingPoint(
`file_upload_extension_margins`, and for all the rest, please rewrite their names

2021-04-19 09:04 UTC, maimonav commented on packages/plugin-file-upload/web/statics/styles/file-upload-viewer.scss
>    flex-flow: column wrap;
&.width_two{
	align-content: center;
}
Do it for all, and remove other classes.

2021-04-19 09:05 UTC, maimonav requested changes
Please follow the comments

2021-04-20 14:26 UTC, maimonav commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
> +          className={classnames(styles.file_upload_type_icon, {
`styles.file_upload_type_icon` or `this.styles.file_upload_type_icon`?

2021-04-20 14:35 UTC, maimonav commented
![Screen Shot 2021-04-20 at 17 34 23](https://user-images.githubusercontent.com/26568665/115414383-a8c24080-a1fe-11eb-9a13-50d1e0c5cf6c.png)
Taken from of file upload in table test, file upload only visible in viewer & editor

2021-04-20 14:38 UTC, maimonav commented
When you fix the file-upload in table issue, make sure to go over the tests and update new tests baselines (of course after you've seen that the new behaviors in tests are as expected).

2021-04-20 14:38 UTC, maimonav commented on bundle-analyzer/bundlesSizesBaseline.json
> +  "wix-rich-content-plugin-file-upload": 270,
Did you discover what is the reason for this increment?

2021-04-20 15:02 UTC, tamrat-bay commented on bundle-analyzer/bundlesSizesBaseline.json
> +  "wix-rich-content-plugin-file-upload": 270,
I'm importing the tooltip component which increases the bundle

2021-04-21 08:32 UTC, tamrat-bay commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
> +          className={classnames(styles.file_upload_type_icon, {
this.styles.file_upload_type_icon

2021-04-29 07:53 UTC, maimonav commented on e2e/tests/plugins.e2e.js
> +        plugins: [plugins.accordion, plugins.embedsPreset, plugins.textPlugins],
@tamrat-bay If you check the table tests, you will see that the inline toolbar is missing a few plugins, so you need to to the table plugin tests the missing plugins as well.

2021-04-29 07:54 UTC, maimonav requested changes
@tamrat-bay Please update branch from master, check the tests, I've update all tests that were as expected, one test of table is failing due to missing plugins.

2021-05-02 13:46 UTC, merged