gallery schema
wix/ricos pull request #2506
Opened 2021-05-13 11:54 UTC by talevy17

2021-07-04 14:46 UTC, talevy17 commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +  google.protobuf.Int32Value gallery_size_px = 2;
item_target_size

2021-07-04 14:46 UTC, talevy17 commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +  google.protobuf.DoubleValue cube_ratio = 4;
item_ratio

2021-07-04 14:46 UTC, talevy17 commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +  google.protobuf.BoolValue one_row = 3;
horizontal_scroll

2021-07-04 14:46 UTC, talevy17 commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +  google.protobuf.BoolValue is_vertical = 6;
layout_orientation: rows\columns

2021-07-04 14:46 UTC, talevy17 commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +  google.protobuf.Int32Value number_of_images_per_row = 7;
images_per_row

2021-07-04 14:46 UTC, talevy17 commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +  google.protobuf.Int32Value thumbnail_spacings = 9;
next to thumbnails_alignment

2021-07-04 14:46 UTC, talevy17 commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +  google.protobuf.StringValue cube_type = 10;
item_crop: true\false

2021-07-18 08:51 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +message Layouting {
This message is global. We want to move message definitions inside the message it is used in.

2021-07-18 09:10 UTC, shaulgo requested changes

2021-07-18 09:10 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +  Media poster = 7;
what is poster?

2021-07-18 09:10 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
>    google.protobuf.StringValue type = 4;
maybe enum?

2021-07-18 09:10 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
>    google.protobuf.StringValue url = 3;
Why do we need both url and item_id?

2021-07-18 09:10 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
>    google.protobuf.BoolValue selected = 4;
what does this mean?

2021-07-18 09:10 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
>    google.protobuf.BoolValue disableExpand = 5;
1. this should be with _. 
2. there is another disable_expand in gallery data.

2021-07-18 09:12 UTC, talevy17 commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +  Media poster = 7;
it's the video thumbnail, we called it poster since PG calls it poster, can be converted though

2021-07-18 09:15 UTC, talevy17 commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
>    google.protobuf.StringValue url = 3;
if the same image is uploaded more than once to a gallery we need the id to distinguish

2021-07-18 09:15 UTC, shaulgo commented
Yes, let's change it to thumbnail. But we also need to think if we want to
arrange it differently. As it relates only to video. Let's discuss after
you finish with all the other changes.

On Sun, Jul 18, 2021 at 12:12 PM Tal Levy ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> <https://github.com/wix/ricos/pull/2506#discussion_r671810981>:
>
> >    google.protobuf.Int32Value height = 1;
>    google.protobuf.Int32Value width = 2;
>    google.protobuf.StringValue title = 3;
>    google.protobuf.StringValue type = 4;
> +  google.protobuf.StringValue altText = 5;
> +  Link link = 6;
> +  Media poster = 7;
>
> it's the video thumbnail, we called it poster since PG calls it poster,
> can be converted though
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/wix/ricos/pull/2506#discussion_r671810981>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAW3OPBPE6J4Q57B6ALIH6LTYKLITANCNFSM442NQ3KA>
> .
>

2021-07-18 09:16 UTC, talevy17 commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
>    google.protobuf.BoolValue selected = 4;
it's an inner state from gallery settings, shouldnt be saved in content but got tangled in there, I'll try get rid of it

2021-07-18 09:17 UTC, shaulgo commented
why? Is this something the PG needs?
Maybe the index of the picture is enough?

On Sun, Jul 18, 2021 at 12:15 PM Tal Levy ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> <https://github.com/wix/ricos/pull/2506#discussion_r671811329>:
>
> >    google.protobuf.StringValue item_id = 2;
>    google.protobuf.StringValue url = 3;
>
> if the same image is uploaded more than once to a gallery we need the id
> to distinguish
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/wix/ricos/pull/2506#discussion_r671811329>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAW3OPGNZS5HVHA4UHFAHS3TYKLSXANCNFSM442NQ3KA>
> .
>

2021-07-18 09:19 UTC, talevy17 commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
>    google.protobuf.StringValue url = 3;
@shaulgo its also a part of PG items scheme

2021-07-20 07:33 UTC, shaulgo requested changes

2021-07-20 07:33 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +      enum Orientation {
rows,columns

2021-07-20 07:33 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +    message Layouting {
```suggestion
    message Layout {
```

2021-07-20 07:33 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +      enum Layout {
```suggestion
      enum Type {
```

2021-07-20 07:33 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +      google.protobuf.StringValue crop = 3;
this should be the enum?

2021-07-20 07:33 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +  message Config {
what is this?

2021-07-20 07:37 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +    }
Look at media from common proto. (like in image, video... proto).
We have here 2 medias (thumbnail and video)

2021-07-20 08:21 UTC, talevy17 commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +      google.protobuf.StringValue crop = 3;
yup

2021-07-20 12:43 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +      Type layout = 1;
if you leave it like here in the data it would be layout.layout = grid
```suggestion
      Type type = 1;
```

2021-07-20 12:56 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +    message Thumbnails {
```suggestion
	// relevant only when layout has thumbnails
    message Thumbnails {
```

2021-07-20 13:26 UTC, talevy17 commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +      Type layout = 1;
fixed

2021-07-20 13:26 UTC, talevy17 commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +    message Thumbnails {
added comment

2021-07-22 08:18 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +      google.protobuf.FloatValue spacings = 2;
float or int?
```suggestion
      google.protobuf.FloatValue spacing = 2;
```

2021-07-22 08:43 UTC, talevy17 commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +      google.protobuf.FloatValue spacings = 2;
1. Nitzan thought it was confusing that 5 looks like 10 (since each image has a 5 margin) so we divide it by 2, which makes it a float - alternatively we can save the int and divide on runtime if you think its better.
2. its the left and right margin of a thumbnail.

2021-07-22 08:46 UTC, shaulgo commented
yes, let's save the int

On Thu, Jul 22, 2021 at 11:44 AM Tal Levy ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> <https://github.com/wix/ricos/pull/2506#discussion_r674608425>:
>
> > +      google.protobuf.Int32Value target_size = 1;
> +      google.protobuf.DoubleValue ratio = 2;
> +      Crop crop = 3;
> +      google.protobuf.Int32Value margin = 4;
> +    }
> +
> +    // relevant only when has thumbnails
> +    message Thumbnails {
> +      enum Alignment {
> +        TOP = 0;
> +        RIGHT = 1;
> +        BOTTOM = 2;
> +        LEFT = 3;
> +      }
> +      Alignment alignment = 1;
> +      google.protobuf.FloatValue spacings = 2;
>
>
>    1. Nitzan thought it was confusing that 5 looks like 10 (since each
>    image has a 5 margin) so we divide it by 2, which makes it a float -
>    alternatively we can save the int and divide on runtime if you think its
>    better.
>    2. its the left and right margin of a thumbnail.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wix/ricos/pull/2506#discussion_r674608425>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAW3OPANHMP5ZC5V4LKT33DTY7K5TANCNFSM442NQ3KA>
> .
>

2021-07-22 10:04 UTC, mharsat requested changes

2021-07-22 10:04 UTC, mharsat commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +    ItemStyling item_styling = 2;
`item_style`?

2021-07-22 10:04 UTC, mharsat commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +  message Styles {
`Style` single

2021-07-22 10:50 UTC, talevy17 commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +      Media data = 1;
I'll replace

2021-07-22 10:50 UTC, talevy17 commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +    google.protobuf.StringValue altText = 4;
yup

2021-07-22 10:51 UTC, talevy17 commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +        COLLAGE = 0;
that's our default

2021-07-22 10:55 UTC, talevy17 commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +      }
the PG term is a boolean isVertical
We thought it was a bit confusing since it might create confusion with horizontalScroll.
it actually refers to ordering the items by rows or columns

2021-07-22 10:55 UTC, talevy17 commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +    ItemStyling item_styling = 2;
changing

2021-07-22 10:55 UTC, talevy17 commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +  message Styles {
done

2021-07-22 13:06 UTC, mharsat commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +        COLLAGE = 0;
In proto the 0th enum is the default value
I guess that `COLLAGE` is the 0th value in the PG mapping, the question is whether we should follow PG numbering or comply with proto rules
It means that galleries created without specifying the layout explicitly will be collages

2021-07-22 13:16 UTC, mharsat commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +      }
> it actually refers to ordering the items by rows or columns

Sounds like you're suggesting `Order` and @shaulgo is in for it

2021-07-25 16:20 UTC, lxgreen commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +    message Video {
consider using `nodes` field that may contain nodes of `{ type: Node_Type.IMAGE, ... }` and `{ type: Node_Type.VIDEO, ...}` instead of `Items`

2021-07-25 16:23 UTC, lxgreen commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +    message Video {
this allows to add more item types to gallery in the future, without schema changes

2021-07-25 16:28 UTC, lxgreen requested changes
Items => nodes

2021-07-26 07:00 UTC, mharsat commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +    message Video {
That's a superb idea but are we actually planning to render inner nodes as image plugin & video plugin components?
Otherwise we'd be misusing the nodes mechanism with a schema that doesn't represent the structure in Tiptap

2021-07-29 08:46 UTC, talevy17 commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +        COLLAGE = 0;
mainly when a gallery is created we provide it with our default styles (which is the GRID styles)
I think swapping the layout numbers could be confusing

2021-07-29 08:54 UTC, mharsat commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +        COLLAGE = 0;
You make the call, just notice that gallery nodes will default to collages
@shaulgo

2021-07-29 13:40 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +      google.protobuf.FloatValue spacings = 2;
1. int
2. change to spacing

2021-07-29 13:41 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +    message Thumbnails {
@mharsat Do you know if the comments need to be in the same line or above?

2021-07-29 13:56 UTC, mharsat commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +    message Thumbnails {
Both would work - [guidelines](https://bo.wix.com/wix-docs/rnd/platformization-guidelines/protobuf#platformization-guidelines_protobuf_comments), I tended to prefer same line in our schema

2021-07-29 14:00 UTC, mharsat commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +    message Thumbnails {
btw the comments are actually documentation describing the messages/fields so it should be phrased accordingly. So the comment above should be replaced with a descriptive one

2021-07-29 14:00 UTC, shaulgo commented
I think that everywhere I saw it in our schema was the same line. So unless
it's very long, let's keep it that way

On Thu, Jul 29, 2021 at 4:56 PM Matan Harsat ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> <https://github.com/wix/ricos/pull/2506#discussion_r679175725>:
>
> > +      Orientation orientation = 3;
> +      google.protobuf.Int32Value items_per_row = 4;
> +    }
> +
> +    message ItemStyling {
> +      enum Crop {
> +        FILL = 0;
> +        FIT = 1;
> +      }
> +      google.protobuf.Int32Value target_size = 1;
> +      google.protobuf.DoubleValue ratio = 2;
> +      Crop crop = 3;
> +      google.protobuf.Int32Value margin = 4;
> +    }
> +
> +    message Thumbnails {
>
> Both would work - guidelines
> <https://bo.wix.com/wix-docs/rnd/platformization-guidelines/protobuf#platformization-guidelines_protobuf_comments>,
> I tended to prefer same line in our schema
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wix/ricos/pull/2506#discussion_r679175725>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAW3OPCP3PF3R33OUPE6UP3T2FM2HANCNFSM442NQ3KA>
> .
>

2021-07-29 14:10 UTC, mharsat commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +    message Thumbnails {
Oh that's a comment on a message, not a field
Looks like that's used as documentation in OS version, not in Wix Docs
In this case I think above the message is the proper location for the comment

2021-07-29 14:15 UTC, talevy17 commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +      google.protobuf.FloatValue spacings = 2;
done

2021-07-29 14:47 UTC, talevy17 commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +    message Thumbnails {
@shaulgo keeping it above the message then

2021-07-29 15:08 UTC, shaulgo commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +        COLLAGE = 0;
Let's keep it like the pg. I think it will keep it more simple. Otherwise we will need to map between the values (although this might happen in the future. But default's can also change). 
When adding a gallery we need to add our defaults for anything that isn't an enum. And we should probably add for enum's as well. I don't think we should rely on the default of enums in most places.

2021-07-30 07:04 UTC, mharsat commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_gallery.proto
> +        COLLAGE = 0;
np just remember that we use string enums, so Styles_Layout_Type.COLLAGE is not 0, it's COLLAGE. So if we need some mapping for PG values we'll need to create it separately

2021-08-01 15:58 UTC, shaulgo commented on packages/plugin-gallery/web/src/components/gallery-settings-modal.js
> +    const componentData = this.props.pubsub.get('componentData');
check with dana about her work on pubsub

2021-08-01 16:21 UTC, shaulgo commented on packages/ricos-content/web/src/converters/draft/toDraft/migration-content-with-key-and-bullet.json
> +            "itemsPerRow": 3
nomberOfColumns

2021-08-01 16:26 UTC, shaulgo commented on packages/ricos-content/web/src/converters/draft/toDraft/migration-content-with-key-and-bullet.json
> +            "alignment": "BOTTOM",
```suggestion
            "placement": "BOTTOM",
```

2021-08-02 07:36 UTC, talevy17 commented on packages/ricos-content/web/src/converters/draft/toDraft/migration-content-with-key-and-bullet.json
> +            "itemsPerRow": 3
done

2021-08-02 07:36 UTC, talevy17 commented on packages/ricos-content/web/src/converters/draft/toDraft/migration-content-with-key-and-bullet.json
> +            "alignment": "BOTTOM",
done

2021-08-12 18:23 UTC, merged