[exampleApp] remove RichContent legacy, use only Ricos components
wix/ricos pull request #2518
Opened 2021-05-19 08:59 UTC by maimonav

2021-05-19 17:01 UTC, mharsat requested changes
Amazing, we lost some extra pounds there!

2021-05-19 17:01 UTC, mharsat commented on packages/ricos-common/web/src/RicosTypes.ts
> +    Pick<RichContentViewerProps, 'addAnchors' | 'experiments'> {
Wait is this actually supported directly on `RicosViewer`?

2021-05-20 08:18 UTC, maimonav commented on packages/ricos-common/web/src/RicosTypes.ts
> +    Pick<RichContentViewerProps, 'addAnchors' | 'experiments'> {
No, experiments should passed trough _rcProps, fixed it.

2021-05-20 08:30 UTC, maimonav commented on examples/main/shared/editor/Editor.tsx
> +              getToolbarSettings: this.config.getToolbarSettings,
`getToolbarSettings` is being used to in rendering the toolbars.
`uiSettings` is being used also, but we can remove it's so important.

2021-05-20 08:51 UTC, mharsat commented on examples/main/shared/editor/Editor.tsx
> +              getToolbarSettings: this.config.getToolbarSettings,
I didn't explain myself well, I meant we can probably remove a lot of code from `EditorPlugins` & `ViewerPlugins` and simplify things

2021-05-20 09:25 UTC, maimonav commented on examples/main/shared/editor/Editor.tsx
> +              getToolbarSettings: this.config.getToolbarSettings,
Yeah probably, but due to more urgent tasks, I will merge this for now, we'll get to it, someday :)

2021-05-20 09:26 UTC, maimonav commented
@mharsat Anything else?

2021-05-20 09:40 UTC, mharsat approved these changes

2021-05-20 09:40 UTC, merged