[content+schema] improve: Node Style
wix/ricos pull request #2520
Opened 2021-05-19 15:12 UTC by Barackos

2021-05-19 17:23 UTC, lxgreen requested changes

2021-05-19 17:23 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +    message Style {
same here

2021-05-19 17:23 UTC, lxgreen commented on packages/ricos-content/web/src/converters/nodeUtils.ts
> +  style?: Node_Style
i think `style` should be parameter of `createNode` as any node can have it now

2021-05-19 19:27 UTC, oded-soffrin commented
I don't see any test changes, what i'm curious about is what happen if we take existing rich content with previous location of styles and convert to draftjs content, will it break?

also, I think a test that does convert from draft to rich content and back
`convertToDraftContent(convertToRichContent(draftContent))`
will cover a lot of the flow
(if not existing already)

2021-05-20 06:44 UTC, mharsat commented
@oded-soffrin looks like tests weren't updated yet, and so unit tests are failing accordingly.

Converting existing content won't break, I suggested we start by adding the new `styles` without removing the existing `textStyles` (@Barackos make sure you cover the toDraft direction too).

Our `toDraft` [tests](https://github.com/wix/ricos/blob/9d3e23914b94b7d9b126c654d0c0aebc295af919/packages/ricos-content/web/src/converters/draft/toDraft/toDraft.spec.ts#L115-L116) do exactly that, convert a complex content back and forth to make sure no important changes are made

2021-05-20 06:58 UTC, oded-soffrin commented
> Converting existing content won't break, I suggested we start by adding the new `styles` without removing the existing `textStyles` (@Barackos make sure you cover the toDraft direction too).

not sure I understand. you mean keep in 'textStyles' in the schema itself ?

2021-05-20 08:36 UTC, Barackos commented on packages/ricos-content/web/src/converters/nodeUtils.ts
> +  style?: Node_Style
Modified `createNode` so it will be responsible for style creation, however not sure we can completely remove this param from `createParagraphNode` - it is called from `fromDraft`, and the style has to be provided somehow

2021-05-20 10:44 UTC, Barackos reviewed
@mharsat @oded-soffrin @lxgreen fixed unit-tests, kindly have a look again.
@oded-soffrin We thought to keep `textStyle` at its place to avoid breaking change, but we can discuss it again

2021-05-20 10:44 UTC, Barackos commented on packages/ricos-content/web/statics/json/migratedFixtures/migration-content.json
>        }
This is a good sign 😄

2021-05-23 06:30 UTC, oded-soffrin commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/rich_content.proto
> +    google.protobuf.StringValue paddingTop = 1;
proto notation should be `padding_top`

2021-05-23 06:31 UTC, oded-soffrin commented
Did we end up leaving `padding_top` in TextStyle as well ?

2021-05-23 06:33 UTC, oded-soffrin commented on packages/ricos-content/web/statics/json/migratedFixtures/migration-content.json
>        }
> @mharsat @oded-soffrin @lxgreen fixed unit-tests, kindly have a look again.
> @oded-soffrin We thought to keep `textStyle` at its place to avoid breaking change, but we can discuss it again

if we keep it in textStyle when will we ever be able to remove it? I believe now is the time. @lxgreen wdyt?

2021-05-23 07:02 UTC, mharsat commented on packages/ricos-content/web/statics/json/migratedFixtures/migration-content.json
>        }
Did we open for  Wix employees?
If not then for sure let's remove it

2021-05-23 16:30 UTC, Barackos commented on packages/ricos-content/web/statics/json/migratedFixtures/migration-content.json
>        }
Following our discussion - removed `paddingTop` & `paddingBottom` from `TextStyle`

2021-05-24 09:14 UTC, lxgreen requested changes

2021-05-24 09:14 UTC, lxgreen commented on packages/ricos-content/web/src/converters/proseMirror/fromProseMirror/fromProseMirror.ts
> +  // return { ...newValue, ...(attrs ? { [dataField]: attrs } : {}) };
```suggestion
```

2021-05-24 09:14 UTC, lxgreen commented on packages/ricos-content/web/src/converters/proseMirror/toProseMirror/__tests__/toProseMirror.spec.ts
> +    // expect(proseDocument).toEqual(migrationContentProse);
```suggestion
```

2021-05-24 09:14 UTC, lxgreen commented on packages/ricos-content/web/src/converters/proseMirror/toProseMirror/toProseMirror.ts
> +  if (isNode(newValue) && newValue?.style) {
```suggestion
  if (isNode(newValue) && newValue.style) {
```

2021-05-24 09:14 UTC, lxgreen commented on packages/ricos-content/web/src/converters/proseMirror/toProseMirror/toProseMirror.ts
> +  if (isNode(newValue) && newValue?.style) {
if isNode(newValue) === true, it is for sure defined, right?

2021-05-24 09:14 UTC, lxgreen commented on packages/ricos-content/web/src/converters/proseMirror/toProseMirror/toProseMirror.ts
> +    if (dataFields.length) {
```suggestion
    if (dataFields.length > 0) {
```

2021-05-24 09:14 UTC, lxgreen commented on packages/ricos-content/web/src/converters/proseMirror/toProseMirror/toProseMirror.ts
> +      .filter(key => !!FIELDS_MAP[key]) // ['nodes', 'paragraphData']
```suggestion
      .filter(key => !!FIELDS_MAP[key] && key.includes('Data'))
```

2021-05-24 09:14 UTC, lxgreen commented on packages/ricos-content/web/src/converters/proseMirror/toProseMirror/toProseMirror.ts
> +      .filter(key => key.includes('Data')); // ['paragraphData']
```suggestion
```

2021-05-24 09:14 UTC, lxgreen commented on packages/ricos-content/web/src/converters/proseMirror/fromProseMirror/fromProseMirror.ts
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
```suggestion
```

2021-05-24 09:30 UTC, Barackos commented on packages/ricos-content/web/src/converters/proseMirror/toProseMirror/toProseMirror.ts
> +      .filter(key => key.includes('Data')); // ['paragraphData']
I was worried it is too implicit to count on `Data` in the field name.
FIELDS_MAP assures that it is a Data field that will be added to `attrs`, while just having `Data` in string doesn't guarantee it, theoretically

2021-05-24 09:40 UTC, mharsat requested changes

2021-05-24 09:40 UTC, mharsat commented on packages/ricos-content/web/src/converters/draft/fromDraft/fromDraft.ts
> +    );
using lodash.merge here isn't necessary, the final step in `fromDraft` is `RichContent.fromJSON(content)` that creates a legal `RichContent` object (`undefined` fields will be created here anyway)

2021-05-24 09:40 UTC, mharsat commented on packages/ricos-content/web/src/converters/nodeUtils.ts
> +  );
Same here with merge, all `fromXXX` methods run though `RichContent.fromJSON`

2021-05-24 09:40 UTC, mharsat commented on packages/ricos-content/web/src/converters/proseMirror/fromProseMirror/fromProseMirror.ts
> +  );
Please separate this into a new function, `convertDataField` has a single responsibility to rename `attrs` to the correct RichContent data field name. More functionality should be added as different function calls in `convertValue`

2021-05-24 09:40 UTC, mharsat commented on packages/ricos-content/web/src/converters/proseMirror/toProseMirror/toProseMirror.ts
> +      newValue = merge({ [dataFields[0]]: { style } }, rest);
If you need the relevant data field you can reuse `DATA_FIELDS_MAP` from `fromProseMirror` (hoist it to the utils file)

2021-05-24 09:40 UTC, mharsat commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/rich_content.proto
> +    NodeStyle style = 20;
If we're already breaking, maybe move `style` to index 4

2021-05-24 11:40 UTC, mharsat approved these changes

2021-05-24 11:40 UTC, mharsat commented on CHANGELOG.md
> +  - [#2520](https://github.com/wix-incubator/rich-content/pull/2520) `NodeStyle` of node: `paddingTop`, `paddingBottom`, `backgroundColor`
Not really clear for anyone that's unfamiliar with the changes, and includes a bit too many details. I don't think a changelog is a must here, but if you do add it I'd go for something simpler like - added a `style` property to `Node` representing node-level styles

2021-05-24 11:40 UTC, mharsat commented on packages/ricos-content/web/src/converters/proseMirror/toProseMirror/toProseMirror.ts
> +    }
This could be extracted to a new function like the other condition clauses

2021-05-24 11:40 UTC, mharsat commented on packages/ricos-content/web/src/converters/nodeUtils.ts
> +  );
Why was this resolved? Should be the same as the other merge cases

2021-05-24 12:22 UTC, merged

2021-05-24 12:41 UTC, Barackos commented on packages/ricos-content/web/src/converters/nodeUtils.ts
> +  );
Missed this one, fixing it here #2535