[ricos-content] feat(ContentAPI): Modify
wix/ricos pull request #2567
Opened 2021-05-31 15:07 UTC by Barackos

2021-06-01 13:17 UTC, lxgreen requested changes

2021-06-01 13:17 UTC, lxgreen commented on packages/ricos-content/web/src/RicosContentAPI/modify.spec.ts
> +    expect(actual).not.toEqual(content);
```suggestion
```

2021-06-01 13:17 UTC, lxgreen commented on packages/ricos-content/web/src/RicosContentAPI/modify.spec.ts
> +    expect(actual).not.toEqual(content);
what's the point?

2021-06-01 13:17 UTC, lxgreen commented on packages/ricos-content/web/src/RicosContentAPI/modify.spec.ts
> +import rawContent from '../../statics/json/migratedFixtures/migration-content.json';
i'd take a smaller content and create the modified version as well

2021-06-01 13:17 UTC, lxgreen commented on packages/ricos-content/web/src/RicosContentAPI/modify.spec.ts
> +    const expected = cloneDeep(content);
this is considered bad practice in testing -- modifying data in the same way the tested function does

2021-06-01 13:17 UTC, lxgreen commented on packages/ricos-content/web/src/RicosContentAPI/modify.spec.ts
> +    const expected = cloneDeep(content);
same here

2021-06-01 13:17 UTC, lxgreen commented on packages/ricos-content/web/src/RicosContentAPI/modify.ts
> +    const cleverFold = T.fold<Node, Node>((value, forest) => {
why to recreate the fold func each time? i'd move it out and call `foldTree`, like its couterpart `unfoldTree`

2021-06-01 18:48 UTC, lxgreen requested changes
last cycle, promise!

2021-06-01 18:48 UTC, lxgreen commented on packages/ricos-content/web/src/RicosContentAPI/modify.spec.ts
> +import rawContent from '../../statics/json/modifyFixtures/images-dividers.json';
everything in /statics is copied to /dist and bundled. it's better to move fixtures to /tests

2021-06-01 18:48 UTC, lxgreen commented on packages/ricos-content/web/src/RicosContentAPI/modify.spec.ts
> +    expect(compare(actual, expected, { ignoredKeys: ['key'] })).toEqual({});
wuuuut? no no
i meant, the 
```js
expect(actual).toStrictEqual(expected);
```
is enough for test. The `compare` is buggy itself, and we are should try to decrease complexity in tests.

2021-06-01 18:48 UTC, lxgreen commented on packages/ricos-content/web/src/RicosContentAPI/modify.ts
> +  set: (setter: ModifierSetter) => RichContent;
nah, dedicated type for `node => node` ? better no

2021-06-01 18:48 UTC, lxgreen commented on packages/ricos-content/web/src/RicosContentAPI/modify.ts
> +  })(tree);
```suggestion
// import { curry } from 'lodash/fp';
// import { pipe } from 'fp-ts/lib/function';

const toArray = item => isArray(item) ? item : [item];

const modifyByKey = curry((keysToSet: string[], setter: (node: Node) => Node | Node[], node: Node) =>
  keysToSet.includes(node.key) ? setter(node) : node);

const mergeWith = curry((prefix, suffix) => [...prefix, ...suffix]);

const foldTree = (tree: T.Tree<Node>, setter: ModifierSetter, keysToSet: string[]) =>
  T.fold<Node, Node>((root, forest) => ({
    ...root,
    nodes: forest.reduce((modifiedForest, node) =>
      pipe(node, modifyByKey(keysToSet, setter), toArray, mergeWith(modifiedForest)), [] as Node[])
  }))(tree);

```

2021-06-01 18:48 UTC, lxgreen commented on packages/ricos-content/web/src/RicosContentAPI/modify.ts
> +  })(tree);
a bit more fun

2021-06-02 05:58 UTC, Barackos commented on packages/ricos-content/web/src/RicosContentAPI/modify.ts
> +  })(tree);
Wow! 🎉

2021-06-02 07:42 UTC, merged