[ricos-editor] feat(callbacks): onToolbarButtonClick
wix/ricos pull request #2585
Opened 2021-06-03 10:48 UTC by Barackos

2021-06-10 20:41 UTC, lxgreen requested changes

2021-06-10 20:41 UTC, lxgreen commented on packages/editor-common/web/src/Components/InlineToolbarButton.tsx
> +      value: !isLastAddStep || children ? undefined : String(!isActive),
i don't understand this line. very confusing

2021-06-10 20:41 UTC, lxgreen commented on packages/editor-common/web/src/Components/InlineToolbarButton.tsx
> +  pluginType?: string;
the `InlineToolbarButton` is actually used outside, as a base for custom buttons in external toolbars (e.g. wix-data). The BI props are gonna complicate its API, even if they are optional. I suggest to move these props to a HOC and wrap the button, should be simple. Such HOC may come handy in the future for other components.

2021-06-10 20:41 UTC, lxgreen commented on packages/editor-common/web/src/Components/LinkComponents/LinkButton.jsx
> +LinkButton.dataHook = dataHook;
what's this property for?

2021-06-10 20:41 UTC, lxgreen commented on packages/editor-common/web/src/Components/LinkComponents/LinkButton.jsx
> +  helpers: PropTypes.object,
looks like this couple of props added to many components. HOC can help

2021-06-10 20:41 UTC, lxgreen commented on packages/editor-common/web/src/Utils/draftUtils.ts
> +    .getType();
hmm
we have tens of duplications of these lines. not sure what to do about it. we have to refactor the whole draft api usages across the whole codebase. we're lucky all this is gonna be removed this year.

2021-06-10 20:41 UTC, lxgreen commented on packages/editor/web/src/RichContentEditor/Toolbars/buttons/utils/createTextBlockStyleButton.jsx
> +          onClick={event => this.setBlockStyle(event, textForHooks)}
please move the function to const

2021-06-10 20:41 UTC, lxgreen commented on packages/editor/web/src/RichContentEditor/Toolbars/buttons/utils/createTextAlignmentButton.jsx
> +      const { onClick, helpers, getEditorState, setEditorState } = this.props;
please consider HOC for all the cases where you modify the `onClick`.

2021-06-10 20:42 UTC, lxgreen commented
tldr -- try to HOC as much as possible to decrease duplication

2021-06-14 08:53 UTC, Barackos commented on packages/editor-common/web/src/Components/InlineToolbarButton.tsx
> +      value: !isLastAddStep || children ? undefined : String(!isActive),
removing this logic. turned out to be unnecessary

2021-06-17 08:06 UTC, merged