[ui-components] refactor: moved actionbuttons
wix/ricos pull request #2643
Opened 2021-06-23 11:59 UTC by tamrat-bay

2021-06-23 13:59 UTC, tamrat-bay commented on packages/ui-components/web/statics/styles/action-buttons.scss
> +  line-height: 40px;
remove line. height

2021-07-14 09:02 UTC, tamrat-bay commented on packages/ui-components/web/statics/styles/button.scss
> +  @extend.small_btn_font_size;
make default to 16px and 14 as var

2021-07-14 11:42 UTC, shaulgo requested changes

2021-07-14 11:42 UTC, shaulgo commented on packages/plugin-commons/web/src/Components/ColorPicker/CustomColorPickerDialog.jsx
> +          saveBtnDataHook={'colorPickerUpdateButton'}
no need to pass dataHook. It should have it hard coded for the actionButtons. Change the test accordingly

2021-07-14 11:42 UTC, shaulgo commented on packages/plugin-video/web/src/toolbar/mediaURLInputModal.tsx
> +        buttonSize={BUTTON_SIZE.medium}
Does urlInputModal have more then one button size?

2021-07-14 11:42 UTC, shaulgo commented on packages/ui-components/web/src/Components/ActionButtons.tsx
> +  selected = true,
```suggestion
  disableSave,
```

2021-07-14 12:52 UTC, tamrat-bay commented on packages/plugin-video/web/src/toolbar/mediaURLInputModal.tsx
> +        buttonSize={BUTTON_SIZE.medium}
Yes

2021-07-15 13:38 UTC, merged