[file-upload] polish(docs): privacy config
wix/ricos pull request #2662
Opened 2021-06-30 13:54 UTC by Barackos

2021-07-01 13:05 UTC, mharsat commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_file.proto
> +  Privacy privacy = 6;
I think `privacy` should be part of the `FileSource` or `Media` types.

1. It's paired to the source as it describes how it should be resolved
2. Once we decide to support private media for more types of media we'd want a general enum for it (prevent future break)

@shaulgo WDYT?

2021-07-01 13:08 UTC, mharsat commented on packages/ricos-content/web/src/converters/draft/toDraft/convertDraftPluginData.ts
> +  if (!privacy || (privacy as FileData_Privacy) === 'UNSET') {
```ts
privacy === FileData_Privacy.UNSET
```

2021-07-01 13:09 UTC, mharsat commented on packages/ricos-content/web/src/converters/draft/fromDraft/convertRicosPluginData.ts
> +  data.privacy = (data.privacy?.toUpperCase() || 'UNSET') as MediaPrivacy;
```ts
FileData_Privacy.UNSET
```

2021-07-01 13:16 UTC, Barackos commented on packages/ricos-content/web/src/converters/draft/toDraft/convertDraftPluginData.ts
> +  if (!privacy || (privacy as FileData_Privacy) === 'UNSET') {
TS error, but got the idea, will do it a little different:
```js
(privacy as string) === FileData_Privacy.UNSET
```

![Screen Shot 2021-07-01 at 16 13 16](https://user-images.githubusercontent.com/22775305/124130551-9169c400-da87-11eb-9d2f-0c9816f7ce5b.png)

2021-07-04 11:53 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_file.proto
> +  Privacy privacy = 6;
I agree. But I need to understand the use case better. Let's talk about it. Maybe custom src is already enough.

2021-07-27 08:07 UTC, mharsat requested changes

2021-07-27 08:07 UTC, mharsat commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/common.proto
> +        google.protobuf.StringValue custom = 2 [deprecated = true]; // Custom id (string)
Nice usage of the deprecated option!
This requires a change to our `generateSchema` script. It currently removes any field option, we should change the regex to remove only wix options/validations

2021-07-27 08:07 UTC, mharsat commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/common.proto
> +        google.protobuf.StringValue json = 4; // Custom string for consumers with an ex-schematic source object
```suggestion
        google.protobuf.StringValue json = 4; // For custom string values or string objects
```

2021-07-27 08:07 UTC, mharsat commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/common.proto
> +        google.protobuf.StringValue custom = 2 [deprecated = true]; // Custom id (string)
```suggestion
        google.protobuf.StringValue custom = 2 [deprecated = true]; // Custom ID
```

2021-07-27 10:35 UTC, mharsat approved these changes
LGTM 🎉

2021-07-29 12:29 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/common.proto
> +        google.protobuf.StringValue custom = 2 [deprecated = true]; // Custom id (string)
do we need to deprecate it? did anyone use this plugin?

2021-07-29 12:30 UTC, shaulgo commented on website/docs/plugins_api/FileUploadPlugin.mdx
> +  privacy?: 'public' | 'private';
maybe private = true/false

2021-07-29 12:34 UTC, shaulgo commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/common.proto
> +        google.protobuf.StringValue json = 4; // For custom string values or string objects
is json used?

2021-07-29 12:34 UTC, shaulgo commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/common.proto
> +    enum Privacy {
why not private: bool?

2021-07-29 12:55 UTC, Barackos commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/common.proto
> +    enum Privacy {
I'll update Schema 👍🏻.

However we should keep `privacy: 'public' | 'private'` in draft, due to its existence in current contents. I'll address it in the converters

2021-07-29 12:56 UTC, Barackos commented on packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/common.proto
> +        google.protobuf.StringValue json = 4; // For custom string values or string objects
Not in the converters. We wanted to allow consumers to add customizations of their choice, but only for the new schema.

2021-07-29 14:12 UTC, Barackos commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/common.proto
> +        google.protobuf.StringValue custom = 2 [deprecated = true]; // Custom id (string)
Yup, e.g. WixData

2021-08-01 07:28 UTC, lxgreen approved these changes

2021-08-01 10:43 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/common.proto
> +        google.protobuf.StringValue custom = 2 [deprecated = true]; // Custom id (string)
I mean if we can find out if there is a site that is using it?

2021-08-01 15:39 UTC, merged