[ricos-schema] collapsible-list schema
wix/ricos pull request #2680
Opened 2021-07-05 15:54 UTC by maimonav

2021-07-06 06:51 UTC, oded-soffrin commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_collapsible_list.proto
> +        COLLAPSED = 2;
thought, maybe change semantic here to make it clearer:
DefaultExpandedItems {
   FIRST = 0;
   ALL = 1;
   NONE = 2;
}

2021-07-21 11:30 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +        COLLAPSIBLE_LIST_PAIR_ITEM = 22;
@oded-soffrin  @maimonav 
Why do this need to be Nodes? This makes them "global" type.
I thought it would something like so:
collapsibleData.items[0].title.nodes
collapsibleData.items[0].content.nodes

2021-07-21 11:33 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +        COLLAPSIBLE_LIST_PAIR_ITEM = 22;
If we do that, we are breaking the "node in node" structure, don't you think? @shaulgo

2021-07-21 11:35 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +        COLLAPSIBLE_LIST_PAIR_ITEM = 22;
Similar to the way @mharsat has implemented the LIST_ITEM node.

2021-07-21 11:37 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +        COLLAPSIBLE_LIST_PAIR_ITEM = 22;
Plus, it gives us the possibility, in the future, to add data to the pair/item, features such as styles and design that are planned for Collapsible phase 2.

2021-07-21 11:53 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +        COLLAPSIBLE_LIST_PAIR_ITEM = 22;
1. We could still add the data in title/content.
2. I don't understand the node in node structure. What are the benefits?

2021-07-21 12:11 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +        COLLAPSIBLE_LIST_PAIR_ITEM = 22;
I think that the first benefit, is consistency through the schema, instead of saving nodes inside the NodeData, we can avoid it and put it in the nodes array, just like all other Nodes.
And I'm not entirely sure how we are going to render each Node using TipTap, so that can be answered later when we reach that point.

2021-07-21 12:49 UTC, mharsat commented on packages/ricos-content/web/src/converters/draft/fromDraft/fromDraft.ts
> +            : [];
Let's keep `parseAtomicBlock` as lean an generic as possible.
All plugin specific logic should be moved to some designated handler

2021-08-19 14:57 UTC, maimonav commented on packages/ricos-content/web/src/converters/draft/fromDraft/fromDraft.ts
> +            : [];
Done.

2021-08-22 15:01 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_collapsible_list.proto
> +        COLLAPSED = 2;
@shaulgo @mharsat WDYT?

2021-08-22 16:29 UTC, mharsat commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_collapsible_list.proto
> +        COLLAPSED = 2;
I'm in favor, it makes it easier to understand.
I do suggest changing terminology. We don't handle state in the saved content to `ExpandState` doesn't fit. Default values are related to consumer configs so `DefaultExpandedItems` doesn't work either.
If I understand correctly this setting sets the initial expanded items state per list, so I'd go for `InitialExpandedItems`

2021-08-22 16:55 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +        COLLAPSIBLE_ITEM = 21;
it is breaking change to modify the index of previously existing field. here, embed was 22, now it is 25. schema extension should always be appending to end

2021-08-22 17:00 UTC, lxgreen requested changes
please fix the breaking

2021-08-22 17:00 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +        EmbedData embed_data = 22;
also here

2021-08-23 07:06 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +        COLLAPSIBLE_ITEM = 21;
Sure, thanks

2021-08-23 07:12 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_collapsible_list.proto
> +        COLLAPSED = 2;
@mharsat Good points, agree.

2021-08-23 08:21 UTC, maimonav commented
@lxgreen Done, anything else?

2021-08-23 09:37 UTC, mharsat approved these changes
LGTM 🔥

2021-08-23 09:37 UTC, mharsat commented on bundle-analyzer/bundlesSizesBaseline.json
> +  "ricos-editor-with-plugins": 1099,
Is this only schema changes?

2021-08-23 09:38 UTC, maimonav commented on bundle-analyzer/bundlesSizesBaseline.json
> +  "ricos-editor-with-plugins": 1099,
Yes.

2021-08-23 09:51 UTC, maimonav commented on packages/ricos-content/web/src/converters/draft/fromDraft/fromDraft.ts
> +            id: generateId(),
It's possible, but then we will have two pairs of nodes that contains the same key:
(COLLAPSIBLE_ITEM_TITLE & FIRST NESTED NODE, COLLAPSIBLE_ITEM_BODY & FIRST NESTED NODE)
It's best to keep it unique :)

2021-08-23 10:11 UTC, lxgreen requested changes

2021-08-23 10:11 UTC, lxgreen commented on packages/ricos-content/web/src/converters/html/toHtml/toHtml.ts
> +  return isFragment
i think the whole suffix/prefix thing is redundant here. why would we try to **format** html while conversion to html? formatting is unrelated to conversion, as it is matter of visual representation vs data structure. Actually, suffix/prefix become `\n` textual nodes in html, which later complicates parsing
@mharsat @maimonav

2021-08-23 10:34 UTC, maimonav commented on packages/ricos-content/web/src/converters/html/toHtml/toHtml.ts
> +  return isFragment
If I understand you correctly, you're referring to formatting html in **general** and not regarding this changes.
What I've done is to allow to parse collapsible to html (IMO, we need to define the html representation of every plugin first), but this can be done later and I'm sure that we will have changes in the future.
Regarding your subject, I'm not really familiar with the usage of this converters, who is using it and how? @lxgreen @mharsat

2021-08-23 10:42 UTC, lxgreen commented on packages/ricos-content/web/src/converters/html/toHtml/toHtml.ts
> +  return isFragment
right, my question is addressed to @mharsat, and it is not related directly to these changes. 

just wrote it down now, before i forget it.

2021-08-23 11:13 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_collapsible_list.proto
> +        COLLAPSED = 2;
ya this looks good 
InitialExpandedItems {
  FIRST = 0;
  ALL = 1;
  NONE = 2;
}

2021-08-23 11:14 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_collapsible_list.proto
> +        COLLAPSED = 2;
Great, it's implemented already :)

2021-08-23 11:18 UTC, shaulgo commented on bundle-analyzer/bundlesSizesBaseline.json
> +  "ricos-editor-with-plugins": 1099,
This pr is small. Where does this originate from?

2021-08-23 11:31 UTC, mharsat commented on packages/ricos-content/web/src/converters/html/toHtml/toHtml.ts
> +  return isFragment
I agree that formatting can be separated from the conversion, especially if it's growing.
Initially the idea was to match the existing HTML baseline, like we do with all converters (as we get it from RichText). We can have a different task for separating this

2021-08-23 11:52 UTC, mharsat commented on packages/ricos-content/web/src/converters/draft/toDraft/convertDraftPluginData.ts
> +import { toDraft } from './toDraft';
I think the bundle issue comes from here.
`convertDraftPluginData.ts` is part of the `toDraftData` bundle - a leaner version containing only the plugin conversion functions, instead of the whole `toDraft` logic. It's used in every `create<PLUGIN_NAME>Data.ts` file, that might explain why we see the increase only in the `rce-with-plugins` & `ricos-editor-with-plugins` bundles, and not in the schema bundle or the non-plugin rce/ricos-editor bundles.

@maimonav please consider if we can work around this somehow in the plugins, this will rise again when table schema is ready.
Also, a new `toDraftData` bundle in our analyzer can help prevent this in the future

@lxgreen @shaulgo

2021-08-23 17:34 UTC, shaulgo commented on bundle-analyzer/bundlesSizesBaseline.json
> +  "rce-with-plugins": 1051,
@oded-soffrin When you feel better. We need to discuss.

2021-08-23 18:12 UTC, mharsat commented on packages/ricos-content/web/src/converters/draft/toDraft/convertDraftPluginData.ts
> +import { toDraft } from './toDraft';
Updating that @maimonav is trying to solve by dynamically loading the `toDraftData` bundle. It can generally improve performance and reduce even the existing bundle size. All that is left is to verify that editor commands can load this data asynchronously

2021-08-23 18:13 UTC, mharsat commented on bundle-analyzer/bundlesSizesBaseline.json
> +  "rce-with-plugins": 1051,
Notice the `toDraft` discussion above ⬆️

2021-08-24 10:09 UTC, maimonav commented on packages/ricos-content/web/src/converters/draft/toDraft/convertDraftPluginData.ts
> +import { toDraft } from './toDraft';
@mharsat Correct, but after discussing it with Shaul, we are not sure it's the right move.

2021-08-25 11:52 UTC, maimonav commented
@oded-soffrin @shaulgo @mharsat Please take a look again, bundle size grew a bit, but way better than before.

2021-08-25 13:07 UTC, mharsat commented
> @oded-soffrin @shaulgo @mharsat Please take a second look, bundle size grew a bit, but way better than before.

I think the editor's bundle size should not grow for all kinds of rich content just because of 2 very advanced plugins.
If dynamic loading is off the table we should consider a different approach that narrows this increase only to contents/consumers that use collapsible. Could be achieved by importing `toDraft` from the collapsible package, or maybe by using loadable.

2021-08-25 13:20 UTC, shaulgo commented
> > @oded-soffrin @shaulgo @mharsat Please take a second look, bundle size grew a bit, but way better than before.
> 
> I think the editor's bundle size should not grow for all kinds of rich content just because of 2 very advanced plugins.
> If dynamic loading is off the table we should consider a different approach that narrows this increase only to contents/consumers that use collapsible. Could be achieved by importing `toDraft` from the collapsible package, or maybe by using loadable.

As I understand it this growth is mainly the support of inner rce. If so, it's acceptable by me at the moment. We will definitely do more work on this in the future.
@maimonav please rebase the table schema pr on this one. And let's see how much the bundle grows when we have both collapsible and table.

2021-08-25 14:29 UTC, merged