[ricos-schema] add table schema
wix/ricos pull request #2705
Opened 2021-07-12 12:05 UTC by danarish4

2021-08-19 11:48 UTC, shaulgo requested changes

2021-08-19 11:48 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_table.proto
> +  repeated int32 colsWidth = 2;
```suggestion
  repeated int32 colsWidthRatio = 2;
```

2021-08-19 11:48 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_table.proto
> +  repeated int32 colsMinWidth = 4;
Dimensions

2021-08-19 11:48 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_table_cell.proto
> +    google.protobuf.StringValue vertical_align = 1;
enum top,center...

2021-08-19 11:48 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_table_cell.proto
> +  message Border {
```suggestion
  message BorderColor {
```

2021-08-25 14:42 UTC, maimonav commented on packages/ricos-content/web/src/converters/plainText/toPlainText/complexPlainText.ts
> +
Reminder to add toPlainText support for Table plugin.

2021-08-25 14:42 UTC, maimonav commented on packages/ricos-content/web/src/converters/html/toHtml/__tests__/complexContentHtml.html
> +<p><br /></p>
Reminder to add toHtml support for Table plugin.

2021-08-25 15:35 UTC, maimonav commented on packages/ricos-content/web/src/converters/draft/fromDraft/getRicosEntityData.ts
> +    : entity;
Refactor and add collapsible support as well

2021-08-29 08:46 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_table_cell.proto
> +    google.protobuf.StringValue bottom = 4;
Sure

2021-08-29 09:57 UTC, maimonav commented
@mharsat Please take a second look, I've updated the changes that you've requested.
@oded-soffrin @shaulgo anything else?

2021-08-29 10:45 UTC, mharsat approved these changes

2021-08-29 10:45 UTC, mharsat commented on packages/ricos-content/web/src/converters/draft/fromDraft/fromDraft.ts
>    }
Aren't these table types something we can reuse from the table plugin?

2021-08-29 10:45 UTC, mharsat commented on packages/ricos-content/web/src/converters/draft/fromDraft/fromDraft.ts
> +            backgroundColor: cell.style?.backgroundColor,
I think COLOR_HEX validation requires uppercase

2021-08-29 10:45 UTC, mharsat commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_table_cell.proto
>      google.protobuf.StringValue background_color = 2;
Isn't this COLOR_HEX too?

2021-08-29 11:48 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_table_cell.proto
>      google.protobuf.StringValue background_color = 2;
Yes, thanks

2021-08-29 11:53 UTC, maimonav commented on packages/ricos-content/web/src/converters/draft/fromDraft/fromDraft.ts
> +            backgroundColor: cell.style?.backgroundColor,
Do you know where we can confirm it?

2021-08-29 12:03 UTC, oded-soffrin commented on packages/ricos-content/web/src/converters/html/toHtml/__tests__/complexContentHtml.html
> +<p><br /></p>
Interesting. This could probably be resolved with <table><<tr><td> tags, and general toHTML conversion of RichContent. let add as a different task , not in this PR scope

2021-08-29 12:03 UTC, oded-soffrin commented on packages/ricos-content/web/src/converters/plainText/toPlainText/complexPlainText.ts
> +
not in this PR scope, let's add as a different task

2021-08-29 12:04 UTC, oded-soffrin commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +        TableData table_data = 23;
I'm somewhat confused which node goes with which data
TABLE_ROW -> TableData
&
TABLE_CELL -> TableCellData?

2021-08-29 12:07 UTC, maimonav commented on packages/ricos-content/web/src/converters/draft/fromDraft/fromDraft.ts
>    }
No.
Currently, there is no type Cell that can be exported, we can always add it of course.
I believe that when we rewrite this plugin to Tiptap(among other plugins), we will use the schema types for all plugins.

2021-08-29 13:00 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +        TableData table_data = 23;
TableData contains Dimensions & ContainerData
TableCellData contains CellStyle & BorderColors
You can take a look at their proto files.

2021-08-29 14:39 UTC, maimonav commented on packages/ricos-content/web/src/converters/draft/fromDraft/fromDraft.ts
> +            backgroundColor: cell.style?.backgroundColor,
Correct, done.

2021-08-30 08:22 UTC, oded-soffrin commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +        TableData table_data = 23;
This I understood, what I didn't is which node goes with which data.
does node type table_row is the one expected to have tableData?
there some kind of mismatch here, or maybe I misunderstood

2021-08-30 08:23 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +        TableData table_data = 23;
TABLE_ROW has no data, only TABLE & TABLE_ROW

2021-08-30 08:33 UTC, mharsat commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +        TableData table_data = 23;
* TABLE & TABLE_CELL

2021-08-30 08:34 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +        TableData table_data = 23;
Yes yes sorry :)

2021-08-30 08:43 UTC, oded-soffrin commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +        TableData table_data = 23;
I see, and it was already existing on (21) I missed that. got it.

2021-08-30 11:07 UTC, maimonav approved these changes

2021-08-30 16:07 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_table.proto
> +  google.protobuf.BoolValue row_header = 3;
Maybe header?

2021-08-30 16:12 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_table.proto
> +  google.protobuf.BoolValue row_header = 3;
Sure, agree

2021-08-30 17:22 UTC, merged