[button] finalize schema
wix/ricos pull request #2759
Opened 2021-07-21 10:49 UTC by maimonav

2021-07-21 11:59 UTC, shaulgo requested changes

2021-07-21 11:59 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_button.proto
> +            google.protobuf.Int32Value border_radius = 2; // number of pixels
```suggestion
            google.protobuf.StringValue text = 1; // hex color
            google.protobuf.StringValue border = 2; // hex color
            google.protobuf.StringValue background = 3; // hex color
        }

        message Border {
            google.protobuf.Int32Value width = 1; // number of pixels
            google.protobuf.Int32Value radius = 2; // number of pixels
```

2021-07-21 11:59 UTC, shaulgo commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_button.proto
> +        BorderStyles border_styles = 1;
```suggestion
        BorderStyles border = 1;
```

2021-07-21 14:28 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_button.proto
> +            google.protobuf.Int32Value border_radius = 2; // number of pixels
Done.

2021-07-21 14:28 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_button.proto
> +        BorderStyles border_styles = 1;
Done.

2021-07-21 14:28 UTC, maimonav commented
@shaulgo Anything else?

2021-09-23 10:45 UTC, oded-soffrin approved these changes

2021-09-23 10:46 UTC, merged