[ricos-schema] gif schema
wix/ricos pull request #2777
Opened 2021-07-25 14:20 UTC by maimonav

2021-07-26 07:05 UTC, mharsat requested changes

2021-07-26 07:05 UTC, mharsat commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gif.proto
>  }
Let's think if we want to make changes to `GIFSource` too before finalizing

2021-07-27 08:58 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gif.proto
>  }
What changes do you have in mind?

2021-07-27 12:13 UTC, shaulgo requested changes

2021-07-27 13:20 UTC, mharsat commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gif.proto
>  }
@shaulgo and I were thinking of reorganizing the different GIF URLs. Maybe using the common `Media` message

2021-07-27 13:21 UTC, mharsat commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gif.proto
>  }
And then have a `source` and `downsizedSource`?

2021-07-27 18:44 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gif.proto
>  }
Please take a look @mharsat @shaulgo

2021-07-28 07:19 UTC, mharsat approved these changes
Looks great!

2021-07-28 07:19 UTC, mharsat commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gif.proto
> +    google.protobuf.StringValue still = 3;
Lat's have some fun with validations 🚀

```suggestion
    google.protobuf.StringValue gif = 1 [(wix.api.format) = WEB_URL];
    google.protobuf.StringValue mp4 = 2 [(wix.api.format) = WEB_URL];
    google.protobuf.StringValue still = 3 [(wix.api.format) = WEB_URL];
```

2021-07-28 07:22 UTC, mharsat commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gif.proto
> +    google.protobuf.StringValue still = 3;
It's not trivial that gif/mp4 are URLs here, so the validation can help.
Also documenting `GIFData` would be divine

2021-07-28 07:45 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gif.proto
> +    google.protobuf.StringValue still = 3;
Is this Wix public api? (open source concern)

2021-07-28 08:01 UTC, mharsat commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gif.proto
> +    google.protobuf.StringValue still = 3;
Nope, it's removed in the generated open source proto

2021-07-28 08:02 UTC, mharsat commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gif.proto
> +    google.protobuf.StringValue still = 3;
https://github.com/wix/ricos/blob/4986671018e89b544344771815287bd1367cdfd7/packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto#L128-L129

2021-07-28 11:47 UTC, merged