add capabilities to editor commands (indent, line spacing, save state…
wix/ricos pull request #2807
Opened 2021-08-02 13:35 UTC by noamtwix

…, save selection)

2021-08-02 14:15 UTC, maimonav requested changes

2021-08-02 14:15 UTC, maimonav commented on packages/common/web/src/types/editorCommandsType.ts
> +export interface DecorationsDataMap {
Is it needed?

2021-08-02 14:15 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/EditorCommands.ts
> +    loadSelectionState,
I know it has no difference, but can you please change it to look like all other functions in the editorState object? (declare the function inside the object)

2021-08-02 14:15 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/EditorCommands.ts
> +const spaceAfter = 'padding-bottom';
It might be better to define it in a different file and export it, or if you only use it in the `getBlockSpacing`, I would use it there and not declare it as a global var.

2021-08-02 14:15 UTC, maimonav commented on packages/common/web/src/types/editorCommandsType.ts
> +  getBlockSpacing: () => any;
Can you create a type for it?

2021-08-02 16:32 UTC, noamtwix commented on packages/common/web/src/types/editorCommandsType.ts
> +export type ColorType = typeof RICOS_TEXT_COLOR_TYPE | typeof RICOS_TEXT_HIGHLIGHT_TYPE;
yes

2021-08-02 16:32 UTC, noamtwix commented on packages/common/web/src/types/editorCommandsType.ts
> +export interface DecorationsDataMap {
yes

2021-08-02 17:30 UTC, noamtwix commented on packages/common/web/src/types/editorCommandsType.ts
> +  getBlockSpacing: () => any;
no

2021-08-03 07:06 UTC, maimonav commented on packages/common/web/src/types/editorCommandsType.ts
> +export type ColorType = typeof RICOS_TEXT_COLOR_TYPE | typeof RICOS_TEXT_HIGHLIGHT_TYPE;
Ok, but this file is the type of the EditorCommands, if you need this type elsewhere, you should move it to type file in this package (common), and export if from there, and use wherever you need.

2021-08-03 07:07 UTC, maimonav commented on packages/common/web/src/types/editorCommandsType.ts
> +export interface DecorationsDataMap {
Same here :)

2021-08-03 07:08 UTC, maimonav commented on packages/common/web/src/types/editorCommandsType.ts
> +  getBlockSpacing: () => any;
Ok, why?

2021-08-03 08:47 UTC, maimonav approved these changes
Looks good, just a kind reminder - create a type for `getBlockSpacing` when you use it in the toolbar :)

2021-08-03 08:51 UTC, merged