feat/ custom font size
wix/ricos pull request #2811
Opened 2021-08-02 15:49 UTC by talevy17

2021-08-12 10:50 UTC, shaulgo requested changes

2021-08-12 10:50 UTC, shaulgo commented on packages/common/web/src/types/editorCommandsType.ts
> +  getFontSize: () => number | undefined;
window.getComputedStyle(document.getElementById("foo")).fontSize;

2021-08-12 10:50 UTC, shaulgo commented on packages/ricos-content/web/src/converters/draft/fromDraft/getTextNodes.ts
> +const getComplexDecoration = {
dynamicDecorationGetters

2021-08-12 10:50 UTC, shaulgo commented on packages/ricos-content/web/src/converters/draft/fromDraft/getTextNodes.ts
> +  ['FG', 'BG', 'font-size'].includes(decorationType);
```suggestion
```

2021-08-12 10:50 UTC, shaulgo commented on packages/ricos-content/web/src/converters/draft/fromDraft/getTextNodes.ts
> +      if (!isComplexDecorationType(type)) {
delete schema validation

2021-08-12 10:50 UTC, shaulgo commented on packages/ricos-content/web/src/converters/draft/fromDraft/getTextNodes.ts
> +      fontSize: value,
let's think if we want to save as an object. Maybe we will want more then px units

2021-08-22 15:56 UTC, shaulgo requested changes

2021-08-22 15:56 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/utils/fontSizeUtils.ts
> +  'header-one': '32',
move defaults to theme

2021-08-22 15:56 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/utils/fontSizeUtils.ts
> +  return themeData?.customStyles?.[draftToRicosCustomStyles[type]] || defaultFontSizes[type];
get font size

2021-08-22 15:56 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/EditorCommands.ts
> +    getFontSize: () => getFontSize(getEditorState(), themeData),
No need to pass all the theme

2021-08-22 15:56 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/utils/fontSizeUtils.ts
> +};
use from draftUtils

2021-08-22 15:56 UTC, shaulgo commented on packages/viewer/web/src/inlineStyleMapper.tsx
> +};
add util safeJsonParse

2021-08-22 15:56 UTC, shaulgo commented on packages/viewer/web/src/inlineStyleMapper.tsx
> +        .filter(range => !!parseStyle(range.style))
!!safeJsonParse(range.style)?.['font-size']

2021-08-23 08:50 UTC, talevy17 commented on packages/editor/web/src/RichContentEditor/utils/fontSizeUtils.ts
> +  return themeData?.customStyles?.[draftToRicosCustomStyles[type]] || defaultFontSizes[type];
done

2021-08-23 08:50 UTC, talevy17 commented on packages/editor/web/src/RichContentEditor/EditorCommands.ts
> +    getFontSize: () => getFontSize(getEditorState(), themeData),
passing only customStyles

2021-08-23 08:51 UTC, talevy17 commented on packages/editor/web/src/RichContentEditor/utils/fontSizeUtils.ts
> +};
moved to `inlineStyleUtils`

2021-08-23 08:51 UTC, talevy17 commented on packages/viewer/web/src/inlineStyleMapper.tsx
> +};
done

2021-08-23 08:51 UTC, talevy17 commented on packages/viewer/web/src/inlineStyleMapper.tsx
> +        .filter(range => !!parseStyle(range.style))
done

2021-08-23 08:53 UTC, talevy17 commented on packages/editor/web/src/RichContentEditor/utils/fontSizeUtils.ts
> +  'header-one': '32',
@Barackos thinks that adding the defaults to `customStyles` abuses the idea of `customStyles` (i.e defaults are not custom) - injecting the defaults with `CSSProperties` is possible but not worth the effort according to him

2021-09-01 09:07 UTC, shaulgo requested changes

2021-09-01 09:07 UTC, shaulgo commented on packages/editor-common/web/src/Utils/inlineStyleUtils.js
> +export const removeCurrentInlineStyle = (editorState, styleSelectionPredicate) => {
check if can be with color

2021-09-01 09:07 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/EditorCommands.ts
> +  RicosCustomStyles,
remove

2021-09-01 09:07 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/EditorCommands.ts
>      triggerDecoration: type => {
check if 
```suggestion
    triggerDecoration: (type: string) => {
```

2021-09-01 09:07 UTC, shaulgo commented on packages/viewer/web/src/inlineStyleMapper.tsx
> +const fontSizeInlineStyleMapper = raw => {
add color

2021-09-09 10:00 UTC, shaulgo commented on packages/common/web/src/Utils/viewerUtils.tsx
> +export const parseStyleByType = (style: string, type: CustomInlineStyleType) => {
`keyof INLINE_STYLE_TYPES` should also work. So either use it here or use it to define the type. But if you still define the type make sure to have them next to each other.

2021-09-09 10:30 UTC, shaulgo approved these changes

2021-09-09 10:30 UTC, shaulgo commented on packages/common/web/src/Utils/viewerUtils.tsx
> +export const getDynamicStyleParser = {
if you make a function you name it with a verb. If it's an object let's name it dynamicStyleParsers

2021-09-09 10:30 UTC, shaulgo commented on packages/ricos-common/web/src/pluginsStrategy/pluginsStrategy.spec.ts
> +    expect(result.inlineStyleMappers.length).toEqual(0);
remove

2021-09-09 10:30 UTC, shaulgo commented on e2e/tests/__snapshots__/plugins.e2e.ts.snap
> +exports[`plugins > spoiler > check text spoilers in editor and reveal it in viewer #0`] =
delete

2021-09-09 11:23 UTC, merged