[tiptap-editor] type fixes
wix/ricos pull request #2823
Opened 2021-08-04 11:28 UTC by Barackos

2021-08-04 18:02 UTC, lxgreen requested changes

2021-08-04 18:02 UTC, lxgreen commented on packages/common/web/src/types/tiptapTypes.ts
> +export interface ExtensionTypeToConfig {
```
CreateExtension<P> = (params: P) => RicosTiptapExtension
```

2021-08-05 16:00 UTC, mharsat commented on packages/editor-common/web/src/Utils/tiptap/types.ts
>  ) => RicosTiptapExtension<T>;
`RicosTiptapExtension` is unnecessary

```suggestion
export type CreateExtension<T extends RicosExtension> = (
  params: CreateExtensionParams<T>
) => T;
```

2021-08-05 16:02 UTC, mharsat commented on packages/editor-common/web/src/Utils/tiptap/extensionCreators.ts
> +export interface RicosGenericExtensionConfig extends ExtensionConfig {
Here too, avoid using generic, it doesn't represent what you're looking for and is confusing in the context of typescript

2021-08-23 11:37 UTC, Barackos commented
Implemented differently in #2833. Closing

2021-08-23 11:37 UTC, closed without merging