[editor-common] fix: default target value
wix/ricos pull request #2828
Opened 2021-08-05 11:21 UTC by maimonav

2021-08-11 08:18 UTC, shaulgo requested changes

2021-08-11 08:18 UTC, shaulgo commented on packages/common/web/src/test/linkConverters.spec.ts
> +  it('should convert target undefined to true', () => {
This is very unintuitive with the name of the function.

2021-08-11 08:21 UTC, maimonav commented on packages/plugin-gallery/web/src/components/gallery-controls/gallery-image-settings.js
>        uiSettings,
I'm not sure if it always was that way, but it has been like that for a while.

2021-08-11 08:22 UTC, maimonav commented on packages/common/web/src/test/linkConverters.spec.ts
> +  it('should convert target undefined to true', () => {
This is the default result, if target isn't defined then by default it's true.

2021-08-11 10:56 UTC, shaulgo commented on packages/common/web/src/test/linkConverters.spec.ts
> +  it('should convert target undefined to true', () => {
I don't love it. But this should will be removed when we migrate completely to new schema?

2021-08-11 11:21 UTC, maimonav commented on packages/common/web/src/test/linkConverters.spec.ts
> +  it('should convert target undefined to true', () => {
No, this is needed for the link panels.

2021-08-15 07:54 UTC, shaulgo approved these changes

2021-08-15 08:11 UTC, merged