[ricos-content] feat: Translatables API
wix/ricos pull request #2844
Opened 2021-08-10 11:15 UTC by Barackos

2021-08-12 21:33 UTC, lxgreen commented on packages/ricos-content/web/src/TranslatableAPI/apply/applyTranslatables.ts
> +// !Barak: the two lines below this one is comment we should have for our non-fp friends. Don't delete them!
later, please remove all the lines with `!Barak`

2021-08-13 13:45 UTC, lxgreen commented on packages/ricos-content/web/src/TranslatableAPI/apply/applyTranslatables.ts
> +// Such util should be added to fp-utils.
for example [Lens.fromPath](https://gcanti.github.io/monocle-ts/modules/index.ts.html#frompath-static-method)

2021-08-13 14:47 UTC, lxgreen commented on packages/ricos-content/web/src/TranslatableAPI/extract/pluginsToTranslatables.ts
> +  fieldsToTranslatables(node, ['buttonData.text']);
also here, these string paths hold schema-related knowledge. we can have it as is, but we want build failure when the schema changes.

2021-08-13 19:11 UTC, Barackos commented on packages/ricos-content/web/src/TranslatableAPI/apply/applyTranslatables.spec.ts
> +    console.log(JSON.stringify(RichContent.toJSON(result)));
yup, it's a dummy test for the purpose of development so I could see live results through `yarn test --watch`.
will be removed

2021-08-16 07:33 UTC, Barackos commented on packages/ricos-content/web/lib/translate.ts
> +export { applyTranslatables } from './../src/TranslatableAPI/apply/applyTranslatables';
Dilemma. `fromTranslatables` sounds like creating a `RichContent` object from `Translatables[]`. But we actually apply those translatables to an existing `RichContent` object.

2021-08-16 08:44 UTC, lxgreen commented on packages/ricos-content/web/src/TranslatableAPI/extract/fieldsToTranslatables.ts
> +  K1 extends keyof Node,
this should move to fp-utils

2021-08-18 16:32 UTC, Barackos commented on packages/ricos-content/web/src/RicosContentAPI/extract.ts
> +  new TraversalExtractor<T>(fromTraversable(T.tree)<T>(), unfoldTree(nodes));
@lxgreen This thing helps when using the `filter`, it gets aware for `NonTextualNode` and `TextualNode` - it prevented build error in some occasions

2021-08-18 18:31 UTC, lxgreen requested changes
i'm still looking to improve the FP, don't merge yet

2021-08-19 09:53 UTC, merged