[docs]: improve loadable & viewer docs
wix/ricos pull request #2951
Opened 2021-10-03 07:57 UTC by danarish4

2021-10-03 15:42 UTC, shaulgo requested changes

2021-10-03 15:42 UTC, shaulgo commented on website/docs/plugins_api/LoadablePlugins.mdx
> +npm i @loadable/component
Users don't need to manually install. 
Add to dependencies in package.json.

2021-10-03 15:42 UTC, shaulgo commented on website/docs/ricos/adding-a-viewer.mdx
> +Note: viewer plugins have different import. you should import plugins from `viewer` entry for reduce bundle size
```suggestion
**Important Note:** Viewer plugins are imported from `[plugin]/viewer`. Editor plugins are imported from `[plugin]`. (see viewer example below)
```

2021-10-04 09:13 UTC, danarish4 commented on website/docs/plugins_api/LoadablePlugins.mdx
> +npm i @loadable/component
Its a peer dependency for all plugins

2021-10-10 11:56 UTC, merged