[schema + content] RichContent UUID
wix/ricos pull request #3061
Opened 2021-11-03 14:45 UTC by Barackos

2021-11-04 06:41 UTC, oded-soffrin commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +    google.protobuf.StringValue uuid = 4;
Just a thought - why not calling it id? (Uuid is implemention detail)
Cant i store content with id "my-content"?

2021-11-04 10:34 UTC, Barackos commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +    google.protobuf.StringValue uuid = 4;
Convinced 😄 changing to id.
Regarding "my-content" - currently you can. I thought about adding an ID validator that enforces our format, but we should discuss whether we want to limit consumers (developers) to modify the id as they wish? (considering that we're open source)

2021-11-04 10:34 UTC, Barackos commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +    google.protobuf.StringValue uuid = 4;
@lxgreen

2021-11-08 16:41 UTC, lxgreen requested changes
beyond all the renaming and refactoring, we have to make sure we handle **every** content generation way, and ID is being added to DraftContent and RichContent.

2021-11-08 16:41 UTC, lxgreen commented on packages/editor/web/lib/editorStateConversion.ts
> +const addViables = (obj, version) => pipe(addVersion(obj, version), addID);
```suggestion
const addMetadata = (obj, version) => pipe(addVersion(obj, version), addID);
```

2021-11-08 16:41 UTC, lxgreen commented on packages/editor/web/lib/editorStateConversion.ts
> +const addViables = (obj, version) => pipe(addVersion(obj, version), addID);
fp-ts is useless unless you add type annotations

2021-11-08 16:41 UTC, lxgreen commented on packages/editor/web/test/editorStateConversion.spec.js
> +    expect(compare(rawData, raw, { ignoredKeys: ['ID'] })).toStrictEqual({});
```suggestion
const { VERSION: __, ID: _, ...rawData } = convertToRaw(editorState.getCurrentContent());
expect(rawData).toEqual(raw);
```

2021-11-08 16:41 UTC, lxgreen commented on packages/ricos-content/web/src/converters/draft/toDraft/toDraft.ts
> +import { v4 as uuidv4 } from 'uuid';
```suggestion
import { v4 as uuid } from 'uuid';
```

2021-11-08 16:41 UTC, lxgreen commented on packages/ricos-content/web/src/converters/nodeUtils.ts
> +} = {}): Metadata => ({
```suggestion
export const initializeMetadata = (version?: number, id?: string): Metadata => ({
```

2021-11-08 16:41 UTC, lxgreen commented on packages/ricos-content/web/src/converters/nodeUtils.ts
> +  id,
```suggestion
  id: id || uuid(),
```

2021-11-08 16:41 UTC, lxgreen commented on packages/ricos-content/web/src/duplicate/duplicate.spec.ts
> +import { duplicate } from './duplicate';
the duplicate API should be moved to `/RicosContentAPI` dir like modify, exract, builder

2021-11-08 16:41 UTC, lxgreen commented on packages/ricos-editor/web/src/utils/enforceContentID.ts
> +import { v4 as uuidv4 } from 'uuid';
```suggestion
import { v4 as uuid } from 'uuid';
```

2021-11-08 16:41 UTC, lxgreen commented on packages/editor-common/web/src/index.ts
> +export const emptyDraftContent: () => DraftContent = () => ({
```suggestion
export const getEmptyDraftContent: () => DraftContent = () => ({
```

2021-11-08 16:41 UTC, lxgreen commented on packages/tiptap-editor/web/src/content-utils/toTiptap/toTiptap.ts
> +import { v4 as uuidv4 } from 'uuid';
```suggestion
import { v4 as uuid } from 'uuid';
```

2021-11-08 16:41 UTC, lxgreen commented on packages/tiptap-editor/web/src/content-utils/fromTiptap/fromTiptap.ts
> +  metadata: attrs?.metadata || initializeMetadata({ id: attrs?.metadata?.id }),
if the 2nd part of `||` is executed -- means `attrs?.metadata` is falsy. thus, there's no way that `attrs?.metadata?.id` exists. 
it is equivalent to `initializeMetadata({ id: false })`

2021-11-08 17:56 UTC, Barackos commented on packages/ricos-content/web/src/converters/nodeUtils.ts
> +} = {}): Metadata => ({
We have 2 use cases (`fromDraft` & `fromTiptap`) where we want to provide id only.
Separating the parameters would require calling this function like that:
`initializeMetadata(undefined, id)`. I find it less attractive ;) why 2 parameters and not an object?

2021-11-08 18:03 UTC, Barackos commented on packages/editor/web/lib/editorStateConversion.ts
> +const addViables = (obj, version) => pipe(addVersion(obj, version), addID);
`obj` in this file can be both `ContentState` and `EditorState`. We might need to remove some non-working code from this file, as it is required before I give `obj` a type

2021-11-09 08:23 UTC, lxgreen commented on packages/editor/web/lib/editorStateConversion.ts
> +const addVersion = (obj, version: string): typeof obj => {
obj is actually DraftContent?

2021-11-11 08:38 UTC, Barackos commented on packages/editor/web/lib/editorStateConversion.ts
> +const addVersion = (obj, version: string): typeof obj => {
`DraftContent` | `EditorState`

2021-11-17 12:40 UTC, lxgreen approved these changes

2021-11-17 13:58 UTC, merged