[ricos-content] improve(extract API): extraction by type
wix/ricos pull request #3074
Opened 2021-11-07 14:06 UTC by Barackos

2021-11-07 15:18 UTC, lxgreen requested changes

2021-11-07 15:18 UTC, lxgreen commented on packages/ricos-content/web/src/RicosContentAPI/extract-by-type.ts
> +    .join('\n');
`join('\n')` is very application domain logic, why not just array? also, this code ignores the fact that new line symbol is [platform dependent](https://stackoverflow.com/questions/10864486/node-js-constant-for-platform-specific-new-line).

2021-11-07 15:18 UTC, lxgreen commented on packages/ricos-content/web/src/RicosContentAPI/extract-by-type.ts
> +    .map(node => node.textData?.text)
all this could be written as 
```
extract(content.nodes).map(({ textData }) => textData?.text || '').get()
```

explanation: `textData` exists on TEXT nodes only, and `get()` filters falsy results internally.

2021-11-07 15:18 UTC, lxgreen commented on packages/ricos-content/web/src/RicosContentAPI/extract-by-type.ts
> +import { RichContent, Node_Type, Node, Media } from 'ricos-schema';
what's the point to include this in the content API core level? it is more relevant to an application like velo

2021-11-07 15:21 UTC, Barackos commented on packages/ricos-content/web/src/RicosContentAPI/extract-by-type.ts
> +    .join('\n');
no real reason. convinced

2021-11-07 15:24 UTC, Barackos commented on packages/ricos-content/web/src/RicosContentAPI/extract-by-type.ts
> +import { RichContent, Node_Type, Node, Media } from 'ricos-schema';
consider it as an explicit api to do things. Velo is one consumer. But we also have services that may want it, so it is unrelated to velo specifically

2021-11-07 15:27 UTC, lxgreen commented on packages/ricos-content/web/src/RicosContentAPI/extract-by-type.ts
> +import { RichContent, Node_Type, Node, Media } from 'ricos-schema';
then let's call it like `application-wrappers` instead of velo, but keep them separately

2021-11-07 15:35 UTC, Barackos commented on packages/ricos-content/web/src/RicosContentAPI/extract-by-type.ts
> +import { RichContent, Node_Type, Node, Media } from 'ricos-schema';
You mean, a lib with the name `application-wrappers`? or separate libs for each use case?

2021-11-08 14:31 UTC, lxgreen commented on packages/ricos-content/web/src/RicosContentAPI/extract-by-type.ts
> +import { RichContent, Node_Type, Node, Media } from 'ricos-schema';
a lib with the name `application-wrappers`

2021-11-11 14:31 UTC, merged