[ricos-content] feature: metadata-utils
wix/ricos pull request #3147
Opened 2021-11-21 17:59 UTC by Barackos

### Changes
- `duplicate` -> `duplicateContent` (entry remains the same)
    - unused files removed

### New utility functions
- `createEmptyContent`
    - entry: `ricos-content/libs/Content`
- `ensureContentId`
    - entry: `ricos-content/libs/metadata-ops`
- `extractIdFromContent`
    - entry: `ricos-content/libs/metadata-ops`

2021-11-21 20:12 UTC, lxgreen requested changes

2021-11-21 20:12 UTC, lxgreen commented on packages/ricos-content/web/src/RicosContentAPI/createEmptyContent.spec.ts
> +    expect(newContent.metadata?.version).toBeTruthy();
it would be easy to inject timestamp and id generators into `createEmptyContent` initialization, if we design it according to dependency injection principle (like we do for content builder). 
If it is too many changes, leave it as is 😕

2021-11-21 20:12 UTC, lxgreen commented on packages/ricos-content/web/src/RicosContentAPI/metadata-utils.ts
> +const addId: AddID = content => merge(cloneDeep(content), { metadata: { id: uuid() } });
```suggestion
const addId = (content: RichContent): RichContent => merge(cloneDeep(content), { metadata: { id: uuid() } });
```

2021-11-21 20:12 UTC, lxgreen commented on packages/ricos-content/web/src/RicosContentAPI/metadata-utils.ts
> +const addId: AddID = content => merge(cloneDeep(content), { metadata: { id: uuid() } });
thumb rule: a function type definition should be like math definition:
```
fn: Input => Output
```
aliases such as AddID make them less readable and confusing (every time i see it, i think the "AddID" is an object or class)

2021-11-21 20:12 UTC, lxgreen commented on packages/ricos-content/web/src/RicosContentAPI/metadata-utils.ts
> +export const duplicateContent = addId;
could we name the `addId` just `duplicateContent` and export it directly?

2021-11-21 20:12 UTC, lxgreen commented on packages/ricos-content/web/src/RicosContentAPI/metadata-utils.ts
> +  content ? (content.metadata?.id ? content : addId(content)) : createEmptyContent();
not readable, please refactor

2021-11-22 10:37 UTC, Barackos commented on packages/ricos-content/web/lib/duplicate.ts
> +export { duplicateContent } from '../src/RicosContentAPI/metadata-utils';
```suggestion
export { duplicate } from '../src/RicosContentAPI/metadata-utils';
```

2021-11-22 10:37 UTC, Barackos commented on packages/ricos-content/web/src/converters/nodeUtils.ts
> +  updatedTimestamp: getUpdatedTimestamp?.() || new Date(),
change to variables

2021-11-22 10:37 UTC, Barackos commented on packages/ricos-content/web/src/RicosContentAPI/metadata-utils.ts
> +  merge(cloneDeep(content), { metadata: { id: uuid() } });
Separate functionality (adder of ID + duplicator).
Also remove `merge`
```suggestion
 { ...cloneDeep(content), metadata: { ...content.metadata, id: uuid() } };
```

2021-11-22 10:59 UTC, Barackos commented on packages/ricos-content/web/src/RicosContentAPI/metadata-utils.ts
> +  metadata: initializeMetadata({ ...(metadata || {}), id: uuid() }),
@lxgreen version is a required field in `metadata`

2021-11-22 13:04 UTC, merged