[monitoring] fix: contentId not sent in some events
wix/ricos pull request #3254
Opened 2021-12-13 16:26 UTC by Barackos

2021-12-16 08:09 UTC, lxgreen requested changes

2021-12-16 08:09 UTC, lxgreen commented on examples/main/shared/editor/Editor.tsx
> +    const onPluginAction: OnPluginAction = async (...args) => console.log(...args);
degraded type?

2021-12-16 08:09 UTC, lxgreen commented on packages/common/web/src/types/biCallbacksTypes.ts
> +export interface biCallbackParams {
naming -- interface should be in CapitalCase

2021-12-16 08:09 UTC, lxgreen commented on packages/ricos-common/web/src/utils.ts
> +export const applyGenericParams = (getContentId: () => string | undefined) => props => {
whose props are these `props`? do we already have their type definition? if yes -- it is worth using

2021-12-17 17:15 UTC, Barackos commented on packages/ricos-common/web/src/utils.ts
> +export const applyGenericParams = (getContentId: () => string | undefined) => props => {
We'll have to get back to it. Technically these are `RichContentProps`, which are later destructed into `RicosModal` props, however `RicosModal` is not aware of them, causing build errors

2021-12-17 20:43 UTC, merged