feat/pdf viewer 2.0
wix/ricos pull request #3370
Opened 2022-01-09 11:26 UTC by talevy17

2022-02-02 13:53 UTC, danarish4 commented on packages/plugin-file-upload/web/src/createFileUploadPlugin.ts
>      }),
why did you pass all of this? 
` anchorTarget,
      relValue,
      uiSettings,
      isMobile,
      experiments`

2022-02-02 13:53 UTC, danarish4 commented on packages/plugin-file-upload/web/src/createFileUploadPlugin.ts
>      ...rest,
I don't think this is necessary

2022-02-02 13:58 UTC, talevy17 commented on packages/plugin-file-upload/web/src/createFileUploadPlugin.ts
>      ...rest,
`anchorTarget` and `relValue` are indeed unnecessary, `isMobile` and `experiments` are needed for the settings modal and the plugin viewer

2022-02-02 15:59 UTC, talevy17 commented on packages/plugin-file-upload/web/src/createFileUploadPlugin.ts
>      }),
removed unnecessary fields.

2022-02-06 08:26 UTC, danarish4 commented on packages/plugin-commons/web/src/Utils/mediaPluginsDataBuilders.ts
> +    const fileData = { ...componentData, ...data, error, tempData: undefined };
are we still using tempData ? 
I think we should not support it anymore

2022-02-06 09:21 UTC, talevy17 commented on packages/plugin-commons/web/src/Utils/mediaPluginsDataBuilders.ts
> +    const fileData = { ...componentData, ...data, error, tempData: undefined };
we should and we will in the upload functionality revamp (:

2022-02-21 10:25 UTC, danarish4 commented on packages/plugin-commons/web/src/Utils/mediaPluginsDataBuilders.ts
> +    const fileData = { ...componentData, ...data, error, tempData: undefined };
revert file

2022-02-21 10:33 UTC, danarish4 commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
> +    if (this.didPDFSettingsChange(nextComponentData, componentData) && adobeAPIKey) {
move to PDFViewer component

2022-02-21 10:34 UTC, danarish4 commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
> +  didPDFSettingsChange = (nextComponentData, componentData) => {
move to PDFViewer component

2022-02-21 10:39 UTC, danarish4 commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
> +            <>
wrap with div with the classname file_upload_container

2022-02-21 11:36 UTC, danarish4 requested changes

2022-02-21 15:36 UTC, talevy17 commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
> +    if (this.didPDFSettingsChange(nextComponentData, componentData) && adobeAPIKey) {
done

2022-02-21 15:36 UTC, talevy17 commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
> +  didPDFSettingsChange = (nextComponentData, componentData) => {
done

2022-02-21 15:36 UTC, talevy17 commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
> +            <>
done

2022-02-21 15:37 UTC, talevy17 commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
> +            <>
done

2022-02-21 15:37 UTC, talevy17 commented on packages/plugin-file-upload/web/src/pdfViewer/pdfIframeSandbox.tsx
> +import React, { useState } from 'react';
done

2022-02-21 15:37 UTC, talevy17 commented on packages/plugin-file-upload/web/src/pdfViewer/pdfViewer.tsx
> +}
moved to pdfConsts

2022-03-03 09:00 UTC, danarish4 commented on packages/plugin-file-upload/web/src/file-upload-viewer.jsx
> +              dataHook={dataHook}
not needed

2022-03-09 15:30 UTC, merged

2022-03-17 08:29 UTC, talevy17 commented on packages/ui-components/web/src/Components/SelectionList.tsx
> +      optionsData.filter(optionData => optionData.selected)?.[0].item as Record<string, string>
@tamrat-bay great catch, I see you pushed the change, thanks !