[ricos-editor] feat(essentials-models) command, node, content WIP
wix/ricos pull request #3457
Opened 2022-02-02 10:05 UTC by maimonav

2022-02-03 09:43 UTC, maimonav commented on packages/ricos-editor/web/src/models/ricos-content.ts
> +export interface IRicosNode<RefinedNodeType extends RefinedNode> {
IRicosNode => RicosNode

2022-02-03 10:05 UTC, maimonav commented on packages/ricos-editor/web/src/models/ricos-content.ts
> +}
Merge them into one, remove containerData & textData

export interface RicosContentNode<DT> extends RicosNode<RefinedNode>{
	getData
	setData
}

2022-02-03 10:07 UTC, maimonav commented on packages/ricos-editor/web/src/models/ricos-paragraph-node.tsx
> +    const nodes: TextNode[] = data.map(textData => generateTextNode(textData));
Create RicosTextNode as Domain entity & RicosTextNodeFactory & RicosTextNodesAgg and RicosParagraphNodesAgg will use it.

2022-02-03 10:09 UTC, maimonav commented on packages/ricos-editor/web/src/models/ricos-paragraph-node.tsx
> +  constructor(props: Props) {
props to parameters (node, selected)

2022-02-03 10:18 UTC, maimonav commented on packages/ricos-editor/web/src/models/ricos-content.ts
> +  selected: boolean;
move selected to impl
add getSelected, setSelected

2022-02-03 10:19 UTC, maimonav commented on packages/ricos-editor/web/src/models/ricos-content.ts
> +  selected: boolean;
static of(paragraphNode) : RicosParagraphNode
private constructor

2022-02-03 10:21 UTC, maimonav commented on packages/ricos-editor/web/src/models/ricos-paragraph-nodes.tsx
> +import type { IRicosNodes } from './ricos-content';
change to ts in all files

2022-02-03 10:22 UTC, maimonav commented on packages/ricos-editor/web/src/models/ricos-paragraph-nodes.tsx
> +    const paragraphNodes = nodes.map(node => new RicosParagraphNode({ node, selected: false }));
RicosParagraphNodeFactory

2022-02-03 10:27 UTC, maimonav commented on packages/ricos-editor/web/src/models/ricos-paragraph-nodes.tsx
> +  }
RicosParagraphNodes.of(nodes: ParagraphNode[]) : RicosParagraphNodes
private constructor(RicosParagraphNode[])

2022-02-03 10:30 UTC, maimonav commented on packages/ricos-editor/web/src/models/ricos-paragraph-nodes.tsx
> +    return this;
const nodes = this.nodes.filter(predicate);
return new privateConstructor

2022-02-03 10:32 UTC, maimonav commented on packages/ricos-editor/web/src/models/ricos-paragraph-nodes.tsx
> +    return this;
https://github.com/wix/ricos/blob/7f53795805b96956951ca70d1e55c4aea7f5a6e4/packages/tiptap-editor/web/src/models/Extensions.ts#L62-L70

2022-02-03 10:35 UTC, maimonav commented on packages/ricos-editor/web/src/models/ricos-paragraph-nodes.tsx
> +    throw new Error('Method not implemented.');
use filter

2022-02-03 17:42 UTC, maimonav commented on packages/ricos-editor/web/src/models/ricos-paragraph-node.tsx
> +    const nodes: TextNode[] = data.map(textData => generateTextNode(textData));
Changed to getTextNode & setTextNode

2022-02-06 08:41 UTC, lxgreen requested changes

2022-02-06 08:41 UTC, lxgreen commented on packages/ricos-editor/web/src/models/ricos-content.ts
> +  // might need to declare abstract class with static "of" method
`RicosNode` is gonna extend `Pointed` interface (the one with `of` method). I'm on it.

2022-02-06 08:41 UTC, lxgreen commented on packages/ricos-editor/web/src/models/ricos-node-factory.ts
> +export class RicosNodeFactory implements IRicosNodeFactory<RefinedNode> {
factory should be as stupid as possible:
```
// the generic factory parametrized by RefinedNode and Pointed derivatives.
// In this case, it is just to call  the `of` exposed by the K.
interface RicosNodeFactory<T extends RefinedNode, K extends Pointed> {
  create(node: T): K;
}


export class RicosParagraphNodeFactory implements RicosNodeFactory<ParagraphNode, RicosParagraphNode> {
  create(node: ParagraphNode) {
    return RicosParagraphNode.of(node);
}
```

2022-02-06 08:41 UTC, lxgreen commented on packages/ricos-editor/web/src/models/ricos-paragraph-node.ts
> +const generateTextNode = (textData: TextData): TextNode => ({
factory

2022-02-06 08:41 UTC, lxgreen commented on packages/ricos-editor/web/src/models/ricos-paragraph-node.ts
> +    return this.node.nodes;
should expose aggregate of `RicosTextNode`, not the nodes

2022-02-06 08:41 UTC, lxgreen commented on packages/ricos-editor/web/src/models/ricos-paragraph-node.ts
> +  setTextNodes(nodes: TextNode[]): void {
this should be handled by `RicosTextNodes` (`RicosTextNode` aggregate)

2022-02-06 08:41 UTC, lxgreen commented on packages/ricos-editor/web/src/models/ricos-paragraph-nodes.ts
> +    const factory = new RicosNodeFactory();
should be injected via parameters rather instantiated. this way, it is easy to replace the implementation

2022-02-06 08:41 UTC, lxgreen commented on packages/ricos-editor/web/src/models/ricos-paragraph-nodes.ts
> +    const factory = new RicosNodeFactory();
the factory should be a class private property, every method should use it

2022-02-06 08:41 UTC, lxgreen commented on packages/ricos-editor/web/src/models/ricos-text-nodes.ts
> +  // how to impl update & delete? there is no id for text node
let's talk about it today ;)

2022-02-06 09:20 UTC, maimonav commented on packages/ricos-content/web/src/types/node-data-refined-types.ts
> +  (!!data.anchorData ||
Decoration might have no data

2022-02-08 12:39 UTC, maimonav commented on packages/ricos-editor/web/src/models/RicosParagraphNodes/ricos-paragraph-node.ts
> +    return RicosTextNodes.of(this.node.nodes);
new => property

2022-02-08 12:46 UTC, maimonav commented on packages/ricos-editor/web/src/models/draft-ricos-node-repository.ts
> +  constructor(editorState: EditorState) {
See if needed

2022-02-13 21:12 UTC, lxgreen requested changes

2022-02-13 21:12 UTC, lxgreen commented on packages/ricos-editor/web/src/models/RicosTextNodes/ricos-text-nodes.ts
> +    const ricosNodesDescriptors = nodes.map(node => descriptorFactory.create(node));
this way, we get factory from outside **not** via constructor, and we just pass it further via constructor.

2022-02-13 21:12 UTC, lxgreen commented on packages/ricos-editor/web/src/models/RicosTextNodes/ricos-text-nodes.ts
> +    return new RicosTextNodes(descriptors);
```suggestion
    // after you fix factory... 
    return new RicosTextNodes(this.descriptors.insert(this.factory.create(node)), this.factory);
```

2022-02-13 21:16 UTC, lxgreen commented
review summary:
- please move all implementations outside `models` (as name suggests, it is supposed to contain only models -- interfaces)
- see the comments regarding the factory injection and factory composition
- let's decide on naming conventions (private variable and interface prefixes)

2022-02-20 14:50 UTC, maimonav commented on packages/ricos-editor/web/src/content-modification/nodes/ricos-nodes.ts
> +export class RicosTrackedNodes<TNode extends RefinedNode, TRicosNode extends RicosNode<TNode>>
Rename TrackedNodes?

2022-02-20 14:50 UTC, maimonav commented on packages/ricos-editor/web/src/content-modification/nodes/ricos-nodes.ts
> +  static withMapper<TNode extends RefinedNode, TRicosNode extends RicosNode<TNode>>(
Rename Mapper?

2022-02-20 15:37 UTC, maimonav commented on packages/ricos-editor/web/src/models/command.ts
> +
Create `ricos-commands` & `wix-ricos-commands` packages.

2022-02-22 11:23 UTC, maimonav commented on packages/ricos-editor/web/src/content-modification/services/draft-content-repository.ts
> +import { toDraft } from 'ricos-content/libs/toDraft';
@lxgreen The bundle increment is due to these two, we either dynamically import them or need to implement node-converter for paragraph & text.

2022-02-23 10:04 UTC, lxgreen commented on packages/ricos-editor/web/src/content-modification/services/draft-content-repository.ts
> +import { toDraft } from 'ricos-content/libs/toDraft';
> to implement node-converter for paragraph & text
i strongly suggest we do this. then, the code is clean and detached from legacy

2022-02-23 12:28 UTC, maimonav commented
@lxgreen after dynamic loading of converters, the bundle size still impacted:
ricos-editor-no-modal: 883KB => 895KB
ricos-editor-with-plugins: 1095KB => 1109KB
ricos-editor: 883KB => 895KB
The change is about ~13KB, which I believe this is a result of usages of ricos-schema, but I'm not sure, this will need to be investigated.
Nevertheless, I think it's ok and that this change is not an issue.
WDYT?

2022-02-23 17:55 UTC, merged