audio schema
wix/ricos pull request #3461
Opened 2022-02-02 21:33 UTC by tamrat-bay

2022-02-06 11:33 UTC, danarish4 commented on packages/common/web/src/types/editorCommandsType.ts
> +  RICOS_AUDIO_TYPE,
we dont need both `RICOS_AUDIO_TYPE` & `AUDIO_TYPE`
This is a new plugin, we don't need to create an "old version type" for it
please remove AUDIO_TYPE and let's stick only to RICOS_AUDIO_TYPE

2022-02-06 11:33 UTC, danarish4 commented on packages/common/web/src/types/editorCommandsType.ts
> +  [AUDIO_TYPE]?: any;
```suggestion
```

2022-02-06 11:33 UTC, danarish4 commented on packages/common/web/src/types/pluginTypes.ts
> +  AUDIO_TYPE,
```suggestion
```

2022-02-06 11:33 UTC, danarish4 commented on packages/common/web/src/types/pluginTypes.ts
> +  [AUDIO_TYPE]?: CreatePluginData<AudioData>;
```suggestion
```

2022-02-06 11:37 UTC, danarish4 commented on packages/common/web/src/types/pluginTypes.ts
> +  | typeof AUDIO_TYPE
```suggestion
  | typeof RICOS_AUDIO_TYPE
```

2022-02-06 11:39 UTC, danarish4 commented on packages/plugin-audio/web/src/defaults.ts
>  export const DEFAULTS = Object.freeze({
please remove also below comments

`// export const theme = (
//   colors: PaletteColors,
//   utils: ThemeUtils,
//   customStyles: RicosCustomStyles = {}
// ) => {};`

2022-02-06 11:39 UTC, danarish4 commented on packages/plugin-audio/web/src/editor.ts
>      // theme,
```suggestion
```

2022-02-06 11:40 UTC, danarish4 commented on packages/plugin-audio/web/src/modals.ts
>  // import AudioModal from './components/audio-modal';
remove this file

2022-02-06 11:40 UTC, danarish4 commented on packages/ricos-content/web/src/RicosContentAPI/extract.spec.ts
> +        // 'AUDIO',
if you are not use it - please remove

2022-02-06 11:42 UTC, danarish4 commented on packages/ricos-content/web/src/comparision/compare.ts
> +  'isCustomAudio',
Why do you want to ignore it? I am not sure this is necessary here

2022-02-06 11:42 UTC, danarish4 commented on packages/ricos-content/web/src/consts.ts
> +export const AUDIO_TYPE = 'wix-draft-plugin-audio';
```suggestion
```

2022-02-06 11:42 UTC, danarish4 commented on packages/ricos-content/web/src/converters/draft/consts.ts
> +  AUDIO_TYPE,
```suggestion
```

2022-02-06 11:43 UTC, danarish4 commented on packages/ricos-content/web/src/converters/draft/consts.ts
> +  [AUDIO_TYPE]: Node_Type.AUDIO,
```suggestion
```

2022-02-06 11:43 UTC, danarish4 commented on packages/ricos-content/web/src/converters/draft/consts.ts
> +  [AUDIO_TYPE]: AUDIO_TYPE,
```suggestion
```

2022-02-06 11:43 UTC, danarish4 commented on packages/ricos-content/web/src/converters/draft/consts.ts
> +  [AUDIO_TYPE]: RICOS_AUDIO_TYPE,
```suggestion
```

2022-02-06 11:44 UTC, danarish4 commented on packages/ricos-content/web/src/converters/draft/fromDraft/consts.ts
> +  AUDIO_TYPE,
```suggestion
  RICOS_AUDIO_TYPE,
```

2022-02-06 11:45 UTC, danarish4 commented on packages/ricos-content/web/src/converters/draft/fromDraft/consts.ts
> +  [AUDIO_TYPE]: AudioData,
```suggestion
  [RICOS_AUDIO_TYPE]: AudioData,
```

2022-02-06 11:45 UTC, danarish4 commented on packages/ricos-content/web/src/converters/draft/fromDraft/convertRicosPluginData.ts
> +  AUDIO_TYPE,
```suggestion
  RICOS_AUDIO_TYPE,
```

2022-02-06 11:45 UTC, danarish4 commented on packages/ricos-content/web/src/converters/draft/fromDraft/convertRicosPluginData.ts
> +    [AUDIO_TYPE]: convertAudioData,
```suggestion
    [RICOS_AUDIO_TYPE]: convertAudioData,
```

2022-02-06 11:47 UTC, danarish4 commented on packages/ricos-content/web/src/converters/draft/fromDraft/convertRicosPluginData.ts
> +  src?: string | AudioComponentData;
AudioComponentData is not the right type here

2022-02-06 11:53 UTC, danarish4 commented on packages/ricos-content/web/src/converters/draft/fromDraft/convertRicosPluginData.ts
> +  if (typeof data.src === 'string') {
why do you need to distinguish between them? 
this is a new plugin- the best way is to build its data as similar as possible so `src` field will be the same in draft & ricos

2022-02-06 11:54 UTC, danarish4 commented on packages/ricos-content/web/src/converters/draft/fromDraft/convertRicosPluginData.ts
> +  data.audio.duration = data.duration;
We need to create `audio` field also in draft and then there will not be a difference

2022-02-06 11:56 UTC, danarish4 commented on packages/ricos-content/web/src/converters/draft/toDraft/convertDraftPluginData.ts
> +  const audioSrc = data.audio?.src;
not sure if the convertor is necessary

2022-02-06 11:57 UTC, danarish4 commented on packages/ricos-editor/web/src/utils/editorCommandsTestsUtil.ts
>    RICOS_POLL_TYPE,
please remove all comments

2022-02-07 13:13 UTC, justame commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_audio.proto
> +  google.protobuf.BoolValue disable_download = 3;
downloadable maybe? or something like that?

2022-02-07 13:19 UTC, tamrat-bay commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_audio.proto
> +  google.protobuf.BoolValue disable_download = 3;
I wanted to maintain the same convection as in other plugins

![image](https://user-images.githubusercontent.com/54495324/152795495-31117b92-fb1c-4851-86b0-acd8df59ea88.png)

2022-02-07 13:34 UTC, danarish4 commented on CHANGELOG.md
> +- `video`
```suggestion
- `audio-plugin`
```

2022-02-07 13:35 UTC, danarish4 commented on packages/plugin-audio/web/src/defaults.ts
> -// export const theme = (
remove comments

2022-02-07 13:35 UTC, danarish4 commented on packages/plugin-audio/web/src/modals.ts
>  // import AudioModal from './components/audio-modal';
remove file

2022-02-07 13:36 UTC, danarish4 commented on packages/plugin-audio/web/src/modals.ts
>  // import AudioModal from './components/audio-modal';
dalete file

2022-02-07 13:39 UTC, danarish4 commented on packages/ricos-content/web/src/converters/draft/fromDraft/convertRicosPluginData.ts
> +    [AUDIO_TYPE]: data,
remove - this will crash because data is not a function.. and you don't need convertor anyway

2022-02-07 13:39 UTC, danarish4 commented on packages/ricos-content/web/src/converters/draft/toDraft/convertDraftPluginData.ts
> +    [Node_Type.AUDIO]: data,
remove

2022-02-07 13:49 UTC, danarish4 requested changes
Did you check if it works well? (now it crashes) 
Toggle `useNewContent` and see if the data looks as expected

2022-02-07 14:40 UTC, maimonav commented on packages/ricos-content/web/src/types/mediaUploadTypes.ts
> +}
Please check if you can reuse the generated types from ricos-schema

2022-02-07 16:12 UTC, maimonav requested changes
Please follow the comments, thanks :)

2022-02-08 07:02 UTC, tamrat-bay commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_audio.proto
> +  google.protobuf.StringValue cover_image = 4;
`cover_image : FileSource`  Fits better

2022-02-13 13:23 UTC, danarish4 commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_audio.proto
> +  FileSource cover_image = 4;
why not `thumbnail` instead of `cover_image` ? (consistent with link preview)

2022-02-13 14:41 UTC, merged

2022-02-13 15:33 UTC, maimonav commented
@tamrat-bay Did you follow all comments?