[schema] feat: add pdfData to file plugin schema
wix/ricos pull request #3478
Opened 2022-02-06 15:21 UTC by talevy17

2022-02-06 15:47 UTC, danarish4 commented on packages/ricos-content/web/src/converters/draft/toDraft/convertDraftPluginData.ts
> +    viewMode && ((data.pdfData.viewMode as string) = viewMode.toLowerCase());
why this is different in draft? lets do it upper case both in draft&ricos schema

2022-02-06 15:50 UTC, danarish4 commented on packages/ricos-content/web/src/types/mediaUploadTypes.ts
> +  size?: string | number;
what is the size for ?

2022-02-07 07:46 UTC, talevy17 commented on packages/ricos-content/web/src/types/mediaUploadTypes.ts
> +  size?: string | number;
we keep file size in our schema but it was missing in the typescript type for some reason

2022-02-07 07:50 UTC, talevy17 commented on packages/ricos-content/web/src/converters/draft/toDraft/convertDraftPluginData.ts
> +    viewMode && ((data.pdfData.viewMode as string) = viewMode.toLowerCase());
done

2022-02-07 08:25 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_file.proto
> +    enum ViewModes {
`ViewModes` ==> `ViewMode` :)

2022-02-07 08:27 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_file.proto
> +  message PDFData {
This is more of a settings than data, WDYT about `PDFSettings`? @talevy17

2022-02-07 08:28 UTC, maimonav commented on packages/ricos-content/web/src/types/mediaUploadTypes.ts
> +
Can you reuse the types generated from ricos-schema?

2022-02-07 08:35 UTC, talevy17 commented on packages/ricos-content/web/src/types/mediaUploadTypes.ts
> +
I'll remove it from this PR and check in the usage if we can use the schema types.

2022-02-07 08:36 UTC, talevy17 commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_file.proto
> +  message PDFData {
I like it, we overuse the term _Data anyways 👍

2022-02-07 08:36 UTC, maimonav requested changes
Hey :), please take a look at the comments.
BTW, can you please add a test that checks the conversion fromDraft & toDraft?
Thanks

2022-02-07 09:07 UTC, talevy17 commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_file.proto
> +    enum ViewModes {
done

2022-02-09 08:22 UTC, maimonav commented on packages/ricos-content/web/src/types/mediaUploadTypes.ts
> +
Did it work?

2022-02-09 08:33 UTC, maimonav commented on packages/ricos-content/web/src/types/mediaUploadTypes.ts
> +export interface PDFData {
PDFData => PDFSettings :)

2022-02-09 08:45 UTC, talevy17 commented on packages/ricos-content/web/src/types/mediaUploadTypes.ts
> +
didn't break in compile time, so I guess it did

2022-02-09 08:47 UTC, talevy17 commented on packages/ricos-content/web/src/types/mediaUploadTypes.ts
> +export interface PDFData {
I'm taking this type from the schema, should have been deleted (:

2022-02-09 08:49 UTC, maimonav commented on packages/ricos-content/web/src/types/mediaUploadTypes.ts
> +export interface PDFData {
Great!

2022-02-09 08:50 UTC, maimonav approved these changes
LGTM 🔥

2022-02-09 10:45 UTC, merged