[*] move models to ricos-types, fix selection d-e-s-t, use toolbars-v2 with detach commands
wix/ricos pull request #3562
Opened 2022-02-24 13:44 UTC by maimonav

2022-02-24 13:49 UTC, lxgreen commented on packages/ricos-editor/web/src/content-modification/command-runner.spec.ts
> +import type { CommandDescriptor, RicosNodesRepository, DescriptorManager } from 'ricos-types';
👍

2022-02-24 13:50 UTC, lxgreen commented on packages/ricos-editor/web/src/content-modification/command-runner.ts
> +  CommandRunner,
CommandRunner is internal as well

2022-02-24 13:55 UTC, lxgreen commented on packages/ricos-editor/web/src/content-modification/commands/core-commands.ts
> +import { setBold, unsetBold, toggleBold } from './bold';
looks like `set`, `unset`, `toggle` could be refactored to

```ts
interface ToggleCommand<TDecoration> {
  set(paragraphs, decoration: TDecoration);
  unset(paragraphs, decoration: TDecoration);
  toggle(paragraphs, decoration: TDecoration);
}
```
and implemented once. Then any decoration-related command could use this logic.

2022-02-24 13:57 UTC, lxgreen commented on packages/ricos-editor/web/src/content-modification/nodes/ricos-node-descriptor.ts
> +import type { RicosNode, IRicosNodeDescriptor, RicosNodeMetadata } from 'ricos-types';
`IRicosNodeDescriptor`, `RicosNodeMetadata` are internal -- should not be exposed

2022-02-24 13:57 UTC, lxgreen commented on packages/ricos-editor/web/src/content-modification/nodes/ricos-node-descriptors.ts
> +import type { RicosNode, IRicosNodeDescriptors } from 'ricos-types';
`IRicosNodeDescriptors` is internal

2022-02-24 13:58 UTC, lxgreen commented on packages/ricos-editor/web/src/content-modification/services/draft-content-repository-mock.ts
> +  IDraftEditorStateTranslator,
`IDraftEditorStateTranslator` is internal

2022-02-24 13:59 UTC, lxgreen commented on packages/ricos-types/web/src/index.ts
> +export * from './models';
only public types that are necessary to define command are supposed to be exposed via `ricos-types`

2022-02-24 14:00 UTC, lxgreen commented on packages/toolbars-v2/web/src/toolbarItemConfig/draftToolbarItemConfigDetachCommands.ts
> +// import { ContentResolver } from './ContentResolver';
where did this file come from?

2022-02-24 14:01 UTC, lxgreen requested changes
please see comments

2022-02-27 11:38 UTC, maimonav commented on packages/toolbars-v2/web/src/toolbarItemConfig/draftToolbarItemConfigDetachCommands.ts
> +// import { ContentResolver } from './ContentResolver';
That's where I've defined buttons that uses new commands, let's go over it today.

2022-02-27 11:49 UTC, maimonav commented on packages/ricos-editor/web/src/content-modification/commands/core-commands.ts
> +import { setBold, unsetBold, toggleBold } from './bold';
We can make create setDecoration, unsetDecoration & toggleDecoration, and can pass decoration to it,  let's discuss it today.

2022-02-27 14:42 UTC, merged