infra/ upload functionality refactor
wix/ricos pull request #3572
Opened 2022-02-28 15:38 UTC by talevy17

2022-04-04 10:53 UTC, danarish4 commented on examples/storybook/src/shared/utils/fileUploadUtil.ts
> +const error = { key: 0, msg: 'error uploading file' };
is it used?

2022-04-04 11:27 UTC, talevy17 commented on examples/storybook/src/shared/utils/fileUploadUtil.ts
> +const error = { key: 0, msg: 'error uploading file' };
only when I'm debugging error handling, can be removed (:

2022-04-06 13:43 UTC, danarish4 requested changes

2022-04-12 08:20 UTC, talevy17 commented on packages/plugin-commons/web/src/Utils/generateInsertPluginButtonProps.ts
> +    if (getUploader && mediaPluginService) {
we need it for type checking (ts can get annoying)

2022-04-19 12:45 UTC, talevy17 commented on packages/plugin-gallery/web/src/components/gallery-settings-modal.js
> +  handleFilesAddedWithIndex = index => {
use UpdateService instead.
updateData is deprecated.

2022-04-19 12:45 UTC, talevy17 commented on packages/plugin-gallery/web/src/components/gallery-settings-modal.js
> +              {({ uploadService }) => (
```suggestion
              {({ uploadService, updateService }) => (
```
```suggestion
              {({ uploadService }) => (
```

2022-04-19 12:45 UTC, talevy17 commented on packages/plugin-gallery/web/src/components/gallery-settings-modal.js
> +              {({ uploadService }) => (
```suggestion
              {({ uploadService, updateService }) => (
```
```suggestion
              {({ uploadService }) => (
```

2022-04-19 12:45 UTC, talevy17 commented on packages/plugin-gallery/web/src/gallery-component.jsx
> +      {!error && (isLoading || componentData.loading) && (
check that items cannot be saved with 'loading' in the content

2022-04-19 12:45 UTC, talevy17 commented on packages/plugin-gallery/web/src/gallery-component.jsx
> +      {!error && (isLoading || componentData.loading) && (
check that items cannot be saved with 'loading' in the content

2022-04-19 12:45 UTC, talevy17 commented on packages/plugin-gallery/web/src/toolbar/galleryPluginService.ts
> +    // const fileType = getGalleryFileType(file.type);
TODO: revert when PG fix bug.

2022-04-19 12:45 UTC, talevy17 commented on packages/plugin-gallery/web/src/toolbar/galleryPluginService.ts
> +    // const fileType = getGalleryFileType(file.type);
TODO: revert when PG fix bug.

2022-04-19 12:45 UTC, talevy17 commented on packages/plugin-image/web/src/image-component.jsx
> +          dataUrl={this.props.tempData?.dataUrl || componentData.dataUrl}
```suggestion
          dataUrl={this.props.tempData?.dataUrl || componentData.tempData.dataUrl}
```
```suggestion
          dataUrl={this.props.tempData?.dataUrl || componentData.dataUrl}
```

2022-04-19 12:45 UTC, talevy17 commented on packages/plugin-image/web/src/image-component.jsx
> +          dataUrl={this.props.tempData?.dataUrl || componentData.dataUrl}
```suggestion
          dataUrl={this.props.tempData?.dataUrl || componentData.tempData.dataUrl}
```
```suggestion
          dataUrl={this.props.tempData?.dataUrl || componentData.dataUrl}
```

2022-04-19 12:45 UTC, talevy17 commented on packages/plugin-video/web/src/toolbar/videoUploadModal.jsx
> +          this.props.componentData
can't use componentData directly.

get from Pubsub or from getComponentData (withModalBaseActions).

2022-04-19 12:45 UTC, talevy17 commented on packages/plugin-video/web/src/toolbar/videoUploadModal.jsx
> +          this.props.componentData
can't use componentData directly.

get from Pubsub or from getComponentData (withModalBaseActions).

2022-04-24 09:15 UTC, merged

2022-04-24 12:07 UTC, justame commented on packages/ricos-common/web/src/UploadContext/ErrorNotifier.tsx
> +const ErrorToast = React.lazy(() => import('wix-rich-content-editor/libs/ErrorToast'));
the name ErrorToast indicates that it's only for errors. if so, great.