[ricos-content-query] new content query service
wix/ricos pull request #3828
Opened 2022-05-04 15:06 UTC by noamtwix

2022-05-08 12:50 UTC, lxgreen requested changes

2022-05-08 12:50 UTC, lxgreen commented on packages/ricos-content-query/web/package.json
> +  "devDependencies": {
redundant -- all devDeps should go to root package.json
p.s. i know it is copy/paste from modals

2022-05-08 12:50 UTC, lxgreen commented on packages/ricos-content-query/web/package.json
> +    "react-popper": "2.2.5",
later we should remove it and use modals service

2022-05-08 12:50 UTC, lxgreen commented on packages/ricos-content-query/web/src/index.ts
> +export { ContentQueryProvider } from './utils/ContentQueryProvider';
all these imports are core `content-query` package functionality. so, it should not reside under `/utils`

2022-05-08 12:50 UTC, lxgreen commented on packages/ricos-content-query/web/statics/styles/drawer.scss
> +.overlay {
why all these CSS files here?

2022-05-08 12:50 UTC, lxgreen commented on packages/toolbars-v3/web/src/components/buttons/LinkButton/LinkButton.tsx
> -export default withToolbarContext(LinkButton);
👍

2022-05-08 12:50 UTC, lxgreen commented on packages/ricos-content-query/web/src/utils/ContentQueryContext.tsx
> +});
```suggestion
export const ContentQueryContext = React.createContext<ContentQueryService>(contentQueryService);
```

2022-05-08 12:50 UTC, lxgreen commented on packages/ricos-content-query/web/src/utils/ContentQueryContext.tsx
> +});
`ContentQueryContextValue` is redundant type if this context exposes a single service

2022-05-08 12:50 UTC, lxgreen commented on packages/ricos-content-query/web/src/utils/ContentQueryProvider.tsx
> +  return <RicosContextConsumer>{() => <>{children}</>}</RicosContextConsumer>;
this should expose provider that accepts editor instance and initializes your service. the `RicosContextConsumer` usage is completely meaningless here

2022-05-18 13:57 UTC, lxgreen requested changes
added 19 comments for now, let's continue after you fix them.

2022-05-18 13:57 UTC, lxgreen commented on packages/ricos-content-query/web/src/ContentQueryProvider.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
please stop with any, use real types

2022-05-18 13:57 UTC, lxgreen commented on packages/ricos-content-query/web/src/ContentQueryService.ts
> +    this.editor = null;
constructor should initialize editor

2022-05-18 13:57 UTC, lxgreen commented on packages/ricos-content-query/web/src/ContentQueryService.ts
> +  public setEditor(editor) {
redundant

2022-05-18 13:57 UTC, lxgreen commented on packages/ricos-content-query/web/src/ContentQueryService.ts
> +  public getExtract() {
Please add type annotations for every function. 

The `getExtract` name is not clear, find out better name and reasonable API.

Also, return value of `Something | boolean` is bad practice.

2022-05-18 13:57 UTC, lxgreen commented on packages/ricos-content-query/web/src/withContentQueryContext.tsx
> +        {contexts => <WrappedComponent {...props} contentQueryContext={contexts} />}
```suggestion
        {contexts => <WrappedComponent {...props} contentQuery={contexts} />}
```

2022-05-18 13:57 UTC, lxgreen commented on packages/ricos-content/web/src/index.ts
> +export { Extractor } from './extractor-infra';
you don't need it, just use `typeof extract` in your interface

2022-05-18 13:57 UTC, lxgreen commented on packages/tiptap-editor/web/src/components/RichContentAdapter/RichContentAdapter.tsx
> +          endKey: selectedNodes[selectedNodes.length - 1].attrs.id,
maybe just return `[selected node ids]`?

2022-05-18 13:57 UTC, lxgreen commented on packages/toolbars-v3/web/src/components/buttons/LinkButton/anchorAdapter.ts
> +}
this is bad type definition, as it prone to errors. this type allows to have valid objects like
```ts
{
	key: undefined,
	type: 'DIVIDER',
	anchorType: 'Noam is the King!',
	text: '',
	data: { items: [ { url: 'wix.com' } ] }
}
```

the better type should:
- define mandatory fields as _mandatory_
- define field types as concrete as possible, e.g. `'IMAGE' | 'GALLERY'` instead of `string`
- reuse schema-derived types like Link, Media, etc from `ricos-schema`
- validate that `type` field value matches `data` field

Example: 
```ts

type AnchorableImage = {
	id: string;
	type: Node_Type.IMAGE;
	anchorType: AnchorType; // you should define this type as well
	imageData: ImageData; // from schema
};

type AnchorableGallery = {
	id: string;
	type: Node_Type.GALLERY;
	anchorType: AnchorType;
	galleryData: GalleryData; // from schema
};

type AnchorableNode = AnchorableImage | AnchorableGallery | ... ;
```

Also, "key" and "block" are draftjs terms. All the new code should be based on RichContent schema terms.

2022-05-18 13:57 UTC, lxgreen commented on packages/toolbars-v3/web/src/components/buttons/LinkButton/anchorAdapter.ts
> +
these should be [type guards](https://isme2n.gitbooks.io/typescript/content/docs/types/typeGuard.html#user-defined-type-guards) like:

```ts
const isAnchorableImage = (node: AnchorableNode): node is AnchorableImage => {
	// isImageData is another type guard
	return node.type === Node_Type.IMAGE && !!node.id && isImageData(node.imageData);
} 

```

2022-05-18 13:57 UTC, lxgreen commented on packages/toolbars-v3/web/src/components/buttons/LinkButton/anchorAdapter.ts
> +
then you can combine guards to figure out things you want like `isAnchorableTextNode`

2022-05-18 13:57 UTC, lxgreen commented on packages/toolbars-v3/web/src/components/buttons/LinkButton/anchorAdapter.ts
> +import { Node_Type } from 'ricos-schema';
this file is huge. please move types to dedicated file

2022-05-18 13:57 UTC, lxgreen commented on packages/toolbars-v3/web/src/components/buttons/LinkButton/anchorAdapter.ts
> +  // eslint-disable-next-line fp/no-loops
no way! stop using loops

2022-05-18 13:57 UTC, lxgreen commented on packages/toolbars-v3/web/src/components/buttons/LinkButton/anchorAdapter.ts
> +const isAnchorableNode = ({ type }: { type: string }) =>
bad API, please use `Node` instead of `{ type }` in signature.

2022-05-18 13:57 UTC, lxgreen commented on packages/toolbars-v3/web/src/components/buttons/LinkButton/anchorAdapter.ts
> +const isWrappingNode = (type: string) => type === Node_Type.BLOCKQUOTE;
type is not just a string

2022-05-18 13:57 UTC, lxgreen commented on packages/toolbars-v3/web/src/components/buttons/LinkButton/anchorAdapter.ts
> +const isNotSelectedNode = selectedNodeId => data => {
bad API, you should never do negative API. please implement `isSelectedNode`, then use it with negation.

2022-05-18 13:57 UTC, lxgreen commented on packages/toolbars-v3/web/src/components/buttons/LinkButton/anchorAdapter.ts
> +    .filter(isNotSelectedNode(selectedNodeId));
```suggestion
    .filter(and([
    	isAnchorableNode,
    	isEmptyTextNodes,
    	not(isSelectedNode(selectedNodeId))
    ]))
    .get();
```

2022-05-18 13:57 UTC, lxgreen commented on packages/toolbars-v3/web/src/components/buttons/LinkButton/anchorAdapter.ts
> +    .filter(isNotSelectedNode(selectedNodeId));
there are `and`, `or`, `not` methods in `ricos-content` for such chaining.

2022-05-18 13:57 UTC, lxgreen commented on packages/toolbars-v3/web/src/components/buttons/LinkButton/anchorAdapter.ts
> +
pretty sure these consts and maps already exist somewhere, please reuse

2022-05-18 13:57 UTC, lxgreen commented on packages/toolbars-v3/web/src/components/buttons/LinkButton/anchorAdapter.ts
> +const mapTypesAndIndexes = (block, typesWithIndexes) => {
"indices", not "indexes"

2022-05-26 14:09 UTC, noamtwix commented on packages/ricos-content-query/web/src/ContentQueryProvider.tsx
> +import React, { useContext } from 'react';
follow `RicosContextProvider`

2022-05-26 14:13 UTC, noamtwix commented on packages/ricos-content-query/web/src/ContentQueryService.ts
> +    if (!this.editor) return null;
throw error (ref: PluginAddButtonCollisionError)

2022-05-26 14:25 UTC, noamtwix commented on packages/toolbars-v3/web/src/components/buttons/LinkButton/anchorAdapter.ts
> +import { not } from 'fp-ts/Predicate';
add fp-ts to package.json (ref: ricos-content)

2022-05-26 14:32 UTC, noamtwix commented on packages/toolbars-v3/web/src/components/buttons/LinkButton/anchorAdapter.ts
> +  let anchorableNodes: Node[] = contentExtractor
check list items id

2022-05-26 14:40 UTC, noamtwix commented on packages/toolbars-v3/web/src/toolbarItemConfig/tiptapToolbarItemConfig.ts
> +          if (linkData.url) {
insertLink
insertAnchor
removeLink
removeAnchor

2022-05-29 11:31 UTC, merged

2022-08-10 15:06 UTC, justame commented on packages/tiptap-editor/web/src/components/RichContentAdapter/RichContentAdapter.tsx
> +          endKey: selectedNodes[selectedNodes.length - 1].attrs.id,
why the first selected node? what happens when selection is empty? 
selectedNodes === []