[tiptap] toggle blockquote in more than one line
wix/ricos pull request #3837
Opened 2022-05-09 08:58 UTC by noamtwix

2022-05-09 12:42 UTC, lxgreen requested changes
in addition to code-related comments, please pay attention to the following points:
- do we want to apply quote on empty paragraphs that wrap any atomic plugin?
- can/should we filter nodes better than just `isTextNode` criteria?
- there's Node API that exposes `isText`, `isBlock` methods

2022-05-09 12:42 UTC, lxgreen commented on packages/tiptap-extensions/web/src/blockquote.ts
> +              return true;
this whole fragment is not readable. please divide it to smaller functions with meaningful names and provide comments if this is still hard to understand. example:
```ts
const nodes: any = [];
doc.nodesBetween(from, to, node => {
	const id = node.attrs.id;
	if (!id) return false;
	nodes.push(node);
});
```

could be more readable:

```ts
const isTextNode = (node: "NodeTypeToFigureOut"): boolean => !node.attrs.id;

const getSelectedTextContainers = (doc: "DocType", from: number, to: number): "NodeTypeToFigureOut"[] => {
	const selectedNodes = [];
	doc.nodesBetween(from, to, n => {
		if(isTextNode(n)) {
			return false;
		}
		selectedNodes.push(n);
	});
	return selectedNodes;
};
```

2022-05-12 08:11 UTC, lxgreen requested changes

2022-05-12 08:11 UTC, lxgreen commented on packages/tiptap-extensions/web/src/blockquote.ts
> +                .run();
what you see above, is called **curried** functions, named after mathematician [Haskell Curry](https://en.wikipedia.org/wiki/Currying#History). The command chain is much readable since the arrows `=>` are not there anymore -- this is the core of declarative approach when you say WHAT to do instead of HOW to do. 
Please pay attention to name meaningfulness and reasonable functions -- each of them has single responsibility and is independent.

2022-05-12 13:19 UTC, noamtwix commented on packages/tiptap-extensions/web/src/blockquote.ts
> +  const { pos } = nodesWithPos[0];
I'm pretty sure it is.
Because the nodes we are checking are the nodes of the selection

2022-05-15 12:48 UTC, merged