[tiptap] add video button
wix/ricos pull request #3852
Opened 2022-05-12 13:47 UTC by danarish4

2022-05-16 07:52 UTC, maimonav commented on packages/plugin-video/web/src/modals/InsertModal.tsx
> +    const editorCommands = editorCommandsContext.getEditorCommands();
Use new EditorContext

2022-05-16 07:52 UTC, maimonav commented on packages/plugin-video/web/src/modals/InsertModal.tsx
> +        {({ uploadService, updateService }) => (
useContext

2022-05-16 07:56 UTC, maimonav commented on packages/plugin-video/web/src/types.ts
> +export const videoModals = {
maybe extract to different file

2022-05-16 07:58 UTC, maimonav requested changes
Please merge with master, summary changes:
 - contexts
 - getAddButtons - dynamic reconfigure - similar to tiptapExtensions

2022-05-19 08:40 UTC, maimonav commented on packages/plugin-video/web/src/modals/InsertModal.tsx
> +export default withRicosContext()(withModalContext(withTiptapEditorContext(InsertModal)));
Suggestion:
You can use useContext Hook instead of add all contexts data as props

2022-05-19 08:44 UTC, maimonav commented on packages/plugin-video/web/src/getAddButtons.tsx
> +  const {
Are you going to refactor `getAddButtons` function in a different PR? (what we discussed, similar to tiptapExtensions reconfigure)

2022-05-19 08:46 UTC, danarish4 commented on packages/plugin-video/web/src/getAddButtons.tsx
> +  const {
yep different pr

2022-05-19 08:46 UTC, danarish4 commented on packages/plugin-video/web/src/modals/InsertModal.tsx
> +export default withRicosContext()(withModalContext(withTiptapEditorContext(InsertModal)));
I'll do it for all modals in different pr :)

2022-05-19 08:47 UTC, maimonav approved these changes

2022-05-19 08:48 UTC, merged