fix documentStyle converter and schema
wix/ricos pull request #3879
Opened 2022-05-19 15:12 UTC by talevy17

2022-05-19 15:59 UTC, maimonav commented
@talevy17 Please add unit tests to document style conversion methods, and when you're done, please make sure you update schema in wix-ricos and services ([schema changes flow](https://bo.wix.com/pages/wix-ricos/docs/for-developers/schema-changes))

2022-05-22 09:08 UTC, maimonav commented on packages/ricos-content/web/statics/json/migratedFixtures/migration-content.json
> +        "paddingBottom": "3px"
A thought:
Do we want to make allow unit's customization to padding's as well as font-size?

2022-05-22 09:49 UTC, talevy17 commented on packages/ricos-content/web/statics/json/migratedFixtures/migration-content.json
> +        "paddingBottom": "3px"
@maimonav  could be, but it would require changing `NodeStyle` which is already in production

2022-05-22 12:13 UTC, lxgreen requested changes

2022-05-22 12:13 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +    google.protobuf.StringValue line_height = 3;
why line height is not part of node style?

2022-05-22 13:05 UTC, lxgreen commented on packages/ricos-content/web/statics/json/migratedFixtures/migration-content.json
> +        "paddingBottom": "3px"
hmm
never saw padding definition in `em` -- it is usually either `px` or `%`
`em` means "current font size" -- do we want padding that depends on font size?

2022-05-22 13:27 UTC, talevy17 commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto
> +    google.protobuf.StringValue line_height = 3;
I stayed in line with the `[nodeStyle](https://github.com/wix/ricos/blob/master/packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/rich_content.proto#L93:L93)` property of a node, which doesn't include line-height 

line-height is defined inside `[textStyle](https://github.com/wix/ricos/blob/master/packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/common.proto#L17:L17)` 

I think the reason here was to separate the properties logically (nodeStyle refers to the entire node as one - i.e top and bottom margins, while textStyle applies properties on the text itself)

2022-05-22 14:01 UTC, maimonav commented on packages/ricos-content/web/statics/json/migratedFixtures/migration-content.json
> +        "paddingBottom": "3px"
It's supported by html though, you can set padding with `em` units, just checked it to be sure.
Either way, It's not important now, we'll address it if it's needed.

2022-05-23 09:29 UTC, talevy17 commented on packages/ricos-content/web/src/converters/draft/fromDraft/fromDraft.ts
> +      style.split(/(px)/g).length >= 2 ? style.split(/(px)/g) : style.split(/(em)/g);
done.

2022-05-23 09:29 UTC, talevy17 commented on packages/ricos-content/web/src/converters/draft/fromDraft/fromDraft.ts
> +        const lineHeight = (styles as any)['line-height'];
done.

2022-05-25 08:36 UTC, merged