[toolbars-v3] data hooks
wix/ricos pull request #3990
Opened 2022-06-07 07:57 UTC by noamtwix

2022-06-07 13:08 UTC, noamtwix commented on packages/toolbars-v3/web/src/components/SizeCalculator/SizeCalculator.tsx
> +  visible: JSX.Element[];
use ComponentType

2022-06-12 15:03 UTC, oded-soffrin commented
@noamtwix @lxgreen  please ping me when this is merged

2022-06-12 19:08 UTC, lxgreen requested changes

2022-06-12 19:08 UTC, lxgreen commented on packages/toolbars-v3/web/src/models/toolbarButtonsTypes.ts
> +export interface IToolbarButtons {
i can't see what's the responsibility of this aggregate.

`getButtonByIndex`, `isEmpty` are just utility methods;
`addButton` accepts **entity** that this aggregate supposed to **abstract** from user.

i suggest to stop using these models in visible/overflow calculation as it only complicates things. make them responsible to get you elements with/without dataHook, and use them only there. this will distill interfaces better, and will help you to find a good name.

2022-06-12 19:08 UTC, lxgreen commented on packages/toolbars-v3/web/src/models/toolbarButtonsTypes.ts
> +  renderComponent: () => JSX.Element;
worth to check if all occurrences of `JSX.Element` can be replaced with `ReactElement` type. It is more convenient, as JSX talks about certain HTML-in-JS templating mechanism.

2022-06-14 06:57 UTC, merged