[tiptap] reconfigure plugins by deprecated helpers
wix/ricos pull request #3995
Opened 2022-06-07 10:53 UTC by danarish4

2022-06-07 11:14 UTC, lxgreen requested changes

2022-06-07 11:14 UTC, lxgreen commented on packages/ricos-editor/web/src/utils/deprecateHelpers.ts
> +  plugins.configure(GALLERY_TYPE, { handleFileUpload, handleFileSelection });
it is better to keep this info in specific plugin, i.e. you call 
```ts
plugins.configure({ handleFileUpload, handleFileSelection });
``` 
and `ImagePlugin` + `GalleryPlugin` entities know what to do with it. In the future we may need to pass additional stuff to plugins, and each one will know its requirements exactly.

2022-06-07 11:14 UTC, lxgreen commented on packages/ricos-plugins/web/src/editorPlugin.ts
> +    Object.keys(config).forEach(key => (this.plugin.config[key] = config[key]));
does `{ ...this.plugin.config, ...config }` do the same?

2022-06-07 11:14 UTC, lxgreen commented on packages/ricos-plugins/web/src/editorPlugins.ts
> +    return this.plugins.filter(plugin => plugin.getType() === type)[0]?.configure(config) || {};
this will become agnostic to type:
```ts
this.plugins.forEach(p => p.configure?.(config))
```

2022-06-07 11:14 UTC, lxgreen commented on packages/ricos-editor/web/src/utils/deprecateHelpers.ts
> +export const deprecateHelpers = (helpers: Helpers = {}, plugins: EditorPlugins) => {
the name `deprecateHelpers` does not match the function purpose

2022-06-07 11:42 UTC, danarish4 commented on packages/ricos-plugins/web/src/editorPlugin.ts
> +    Object.keys(config).forEach(key => (this.plugin.config[key] = config[key]));
no because it create a new instance of config and I need to reconfigure the existing instance

2022-06-08 08:13 UTC, lxgreen requested changes

2022-06-08 08:13 UTC, lxgreen commented on packages/ricos-plugins/web/src/editorPlugin.ts
> +    }
it's complicated 🤔 

don't you just need to override the `plugin.config` with `mergedConfig` value?

2022-06-08 08:13 UTC, lxgreen commented on packages/ricos-types/web/src/pluginTypes.ts
> +  reconfigure?: (config: PluginConfig, additionalConfig) => Record<string, any>;
```suggestion
  reconfigure?: (config: PluginConfig, additionalConfig) => PluginConfig;
```

2022-06-08 08:21 UTC, danarish4 commented on packages/ricos-plugins/web/src/editorPlugin.ts
> +    }
no, because it creates a new instance of config and I need to reconfigure the existing instance

2022-06-08 09:12 UTC, closed without merging