[ricos-editor/toolbars-v3] add wrapper to addpluginmenu & move folder to toolbars-v3
wix/ricos pull request #4006
Opened 2022-06-08 12:16 UTC by tamrat-bay

2022-06-08 13:28 UTC, maimonav commented on packages/ricos-editor/web/src/toolbars/FloatingPluginMenu/AddPluginMenuHorizontal.tsx
> +interface Props {
Move to toolbars-v3 package

2022-06-08 13:50 UTC, maimonav commented on packages/ricos-editor/web/src/toolbars/FloatingPluginMenu/consts.ts
> +const PLUGIN_MENU_MODAL_ID = 'pluginMenu';
WDYT about exporting this from ricos-modals?

2022-06-12 12:08 UTC, maimonav requested changes

2022-06-12 12:08 UTC, maimonav commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/AddPluginMenuWrapper.tsx
> +  plugins: any;
why any?

2022-06-12 12:08 UTC, maimonav commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/FloatingAddPluginMenu.tsx
> +  const PLUGIN_MENU_MODAL_ID = 'pluginMenu';
Please import it and remove this

2022-06-12 12:08 UTC, maimonav commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/consts.ts
> +export default PLUGIN_MENU_MODAL_ID;
Please remvove default export
Also, is this modal_id is going to be imported only from toolbars-v3 or from other packages as well?
If so, it might not be a good place to declare it

2022-06-12 12:50 UTC, tamrat-bay commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/AddPluginMenuHorizontal.tsx
> +  plugins: any;
The type of plugins is in - ricos-plugins 
imposing it causes circular dependency

2022-06-12 13:49 UTC, tamrat-bay commented on packages/ricos-editor/web/src/toolbars/FloatingPluginMenu/consts.ts
> +const PLUGIN_MENU_MODAL_ID = 'pluginMenu';
We only use it for FloatingAddPluginMenu.tsx, AddPluginMenuWrapper.tsx and AddPluginMenuHorizontal.tsx
and they all located in toolbars-v3

I don't see where else we can use it

2022-06-12 14:55 UTC, maimonav commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/AddPluginMenuHorizontal.tsx
> +  plugins: any;
Ok, let's keep it that way for now - need to figure out how to organize ricos-plugins & toolbars-v3, toolbars-v3 is becoming the new common package @danarish4 @noamtwix @lxgreen

2022-06-12 14:57 UTC, maimonav commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/AddPluginMenuHorizontal.tsx
> +const content = Content.create<Node[]>([]);
Let's put inside HorizontalComponent

2022-06-12 15:01 UTC, maimonav commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/AddPluginMenuHorizontal.tsx
> +  const renderers = {};
Consider changing it to functional (use reduce)

2022-06-12 15:04 UTC, maimonav commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/AddPluginMenuWrapper.tsx
> +  helpers = {},
Remove helpers default value

2022-06-12 15:05 UTC, maimonav commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/AddPluginMenuWrapper.tsx
> +  component: (props: any) => JSX.Element;
Let's add type

2022-06-12 15:11 UTC, maimonav commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/consts.ts
> +export interface IPluginMenuButtonClick {
extract to `FloatingPluginMenu/types.ts` or  `FloatingPluginMenu/plugin-menu-button-click.ts`.

2022-06-12 15:11 UTC, maimonav requested changes
Follow the comments

2022-06-13 07:47 UTC, maimonav commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/AddPluginMenuHorizontal.tsx
> +  const renderers = plugins
NICE!!

2022-06-13 07:48 UTC, maimonav approved these changes
Looks great 🔥

2022-06-13 07:51 UTC, merged