[toolbars-v3] fix: isVisible function
wix/ricos pull request #4030
Opened 2022-06-12 18:11 UTC by noamtwix

2022-06-12 18:27 UTC, lxgreen requested changes

2022-06-12 18:27 UTC, lxgreen commented on packages/ricos-editor/web/src/tiptap/RicosToolbars.tsx
> +          isVisible={selection =>
please move function definition out of prop. this causes lots of redundant renders

2022-06-12 18:27 UTC, lxgreen commented on packages/ricos-editor/web/src/tiptap/RicosToolbars.tsx
> +          isVisible={selection => this.isLinkInCollapsedSelection(selection, editor)}
also here

2022-06-12 18:27 UTC, lxgreen commented on packages/ricos-editor/web/src/toolbars/PluginToolbar.tsx
> +        isVisible={selection => isNodeSelection(selection)}
and here

2022-06-12 19:17 UTC, lxgreen requested changes
more declarative, please

2022-06-12 19:17 UTC, lxgreen commented on packages/ricos-editor/web/src/toolbars/PluginToolbar.tsx
> +        isVisible={this.pluginToolbarIsVisibleFunction}
```suggestion
        isVisible={isNodeSelection}
```

2022-06-12 19:17 UTC, lxgreen commented on packages/ricos-editor/web/src/toolbars/PluginToolbar.tsx
> +        isVisible={this.pluginToolbarIsVisibleFunction}
worth to check if it works like that

2022-06-12 19:17 UTC, lxgreen commented on packages/ricos-editor/web/src/tiptap/RicosToolbars.tsx
> +    !this.isSelectionCollapsed(selection) && isTextSelection(selection);
```suggestion
  formattingToolbarIsVisibleFunction = and(not(this.isSelectionCollapsed), isTextSelection)
```

2022-06-12 19:17 UTC, lxgreen commented on packages/ricos-editor/web/src/tiptap/RicosToolbars.tsx
> +  linkToolbarIsVisibleFunction = (selection: Selection) =>
note for all the visibility functions -- what a naming! how about `isXXXToolbarVisible`?

2022-06-13 06:40 UTC, noamtwix commented on packages/ricos-editor/web/src/tiptap/RicosToolbars.tsx
> +    !this.isSelectionCollapsed(selection) && isTextSelection(selection);
why is it better to do this?

2022-06-14 10:29 UTC, merged