[ricos-converters] feat: add missing node converters
wix/ricos pull request #4065
Opened 2022-06-23 14:05 UTC by shlomo-gangul

2022-06-28 13:55 UTC, maimonav requested changes
Please follow my comments, you need to go over all node converters and double check if they contain content/nodes, if so you need to convert them as well, using visit method, check paragraph-converter [visit](https://github.com/wix/ricos/blob/master/packages/ricos-converters/web/src/nodes/paragraph-converter.ts#L21) method usage for example.

2022-06-28 13:55 UTC, maimonav commented on packages/ricos-converters/web/src/nodes/blockquote-converter.spec.ts
> -import type { BlockquoteNode } from 'ricos-content';
Please revert all change in this file, unneeded

2022-06-28 13:55 UTC, maimonav commented on packages/ricos-converters/web/src/nodes/bulleted-list-converter.spec.ts
> +    content: [] as [],
Please check schema of bulleted list, it contains content/nodes

2022-06-28 13:55 UTC, maimonav commented on packages/ricos-converters/web/src/nodes/code-block-converter.ts
> +      content: [],
Again, code-block node contains nodes , similar to bulleted-list

2022-07-03 18:40 UTC, oded-soffrin commented
I was trying to see why the e2e fails, but it seem that it has to do with converting

Tracking back the failing test ("allow to apply indent on multiple text blocks") on the example app (https://rich-content-nodeconverters.surge.sh/#!!)
i've taken the test content (/e2e/tests/fixtures/text-blocks.json) and converted from draft to prose - and oops the list is gone
![image](https://user-images.githubusercontent.com/1297297/177052969-df3cfaea-137c-407e-8d5c-24f6598b198d.png)

![image](https://user-images.githubusercontent.com/1297297/177052978-4af77c13-03cb-42a5-9bc0-89c8481fb791.png)

we can probably have unit test that check the convertion before finding it in e2e

2022-07-04 11:11 UTC, maimonav commented on packages/ricos-converters/web/src/nodes/bulleted-list-converter.spec.ts
> +    content: [],
Test nested nodes

2022-07-04 11:13 UTC, maimonav commented on packages/ricos-converters/web/src/nodes/code-block-converter.spec.ts
> +    nodes: [],
Test text nodes

2022-07-04 11:47 UTC, maimonav commented on packages/ricos-converters/web/src/nodes/collapsible-list-converters.spec.ts
> +    content: [] as [],
Test nested nodes

2022-07-04 11:52 UTC, maimonav commented on packages/ricos-converters/web/src/nodes/list-converter.spec.ts
> +    content: [] as ParagraphNode[],
Test nested nodes

2022-07-04 11:53 UTC, maimonav commented on packages/ricos-converters/web/src/nodes/ordered-list-converter.spec.ts
> +    content: [] as ListItemNode[],
Test nested nodes

2022-07-04 11:56 UTC, maimonav commented on packages/ricos-converters/web/src/nodes/ordered-list-converter.ts
> +    convert: (node: OrderedListNode) => ({
add visit usage

2022-07-04 11:56 UTC, maimonav commented on packages/ricos-converters/web/src/nodes/ordered-list-converter.ts
> +    convert: (node: TiptapNode) => {
also here

2022-07-04 11:56 UTC, maimonav commented on packages/ricos-converters/web/src/nodes/paragraph-converter.spec.ts
> +    content: [],
Test nested nodes

2022-07-04 11:58 UTC, maimonav commented on packages/ricos-converters/web/src/nodes/table-converter.spec.ts
> +            content: [],
Test nested nodes

2022-07-04 11:58 UTC, maimonav commented on packages/ricos-converters/web/src/nodes/table-converter.spec.ts
> +            content: [],
Test nested nodes

2022-07-04 11:59 UTC, maimonav requested changes
Follow my comments :)

2022-07-06 14:13 UTC, shlomo-gangul commented
> 

done

2022-07-06 14:39 UTC, maimonav requested changes
Looks great 🔥 
Please update changelog.

2022-07-06 14:55 UTC, maimonav commented on CHANGELOG.md
> +
It's `## :house: Internal`, and there is already a section in here, take a look below.

2022-07-06 14:56 UTC, maimonav commented on CHANGELOG.md
> +
![Uploading Screen Shot 2022-07-06 at 17.55.58.png…]()

2022-07-06 15:13 UTC, maimonav approved these changes

2022-07-06 15:42 UTC, merged