Tiptap modals UI
wix/ricos pull request #4179
Opened 2022-07-13 09:37 UTC by shlomo-gangul

2022-07-13 11:00 UTC, danarish4 commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/PlusButton.tsx
> +    const transform = isRotate && { transform: `rotate(45deg)` };
In this case, there are no runtime calculations required, so please add this style to the `floating-add-plugin-menu.scss` file (better performance achieved)

2022-07-13 11:03 UTC, danarish4 commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/FloatingAddPluginMenu.tsx
> +  const [isRotate, setIsRotate] = useState<boolean>();
```suggestion
  const [isRotate, setIsRotate] = useState<boolean>(false);
```

2022-07-13 11:04 UTC, danarish4 requested changes
Follow comments

2022-07-18 09:23 UTC, shlomo-gangul commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/FloatingAddPluginMenu.tsx
> +    setIsRotate(modalService?.isModalOpen(MODAL_ID));
i tried it and it wont work in any other way

2022-07-18 09:24 UTC, shlomo-gangul commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/PlusButton.tsx
> +    const transform = isRotate && { transform: `rotate(45deg)` };
done

2022-07-18 09:24 UTC, shlomo-gangul commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/FloatingAddPluginMenu.tsx
> +  const [isRotate, setIsRotate] = useState<boolean>();
done

2022-07-18 11:06 UTC, tamrat-bay commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/FloatingAddPluginMenu.tsx
> +    modalService.isModalOpen(MODAL_ID)
```suggestion
const isModalOpen = ()=>  modalService.isModalOpen(MODAL_ID)
isModalOpen()
```

2022-07-18 11:07 UTC, tamrat-bay commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/FloatingAddPluginMenu.tsx
> +    setIsModalOpen(modalService.isModalOpen(MODAL_ID));
```suggestion
    setIsModalOpen(isModalOpen());
```

2022-07-18 11:10 UTC, tamrat-bay commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/FloatingAddPluginMenu.tsx
> +  }, [modalService.getOpenModals()]);
Verify whether this dependency is necessary
Maybe you don't need it and [] is enough.

2022-07-21 07:20 UTC, danarish4 commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/FloatingAddPluginMenu.tsx
> +  }, []);
Was it essential? The modal must be closed when the component is mounted

2022-07-21 07:23 UTC, danarish4 commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/FloatingAddPluginMenu.tsx
> +    isModalOpen()
```suggestion
    isModalOpen
```

Please use the isModalOpen property on the component state (so that we can preserve a single source of truth).

2022-07-21 07:24 UTC, danarish4 requested changes
I left comments

2022-07-21 08:58 UTC, shlomo-gangul commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/FloatingAddPluginMenu.tsx
> +  }, []);
yes it is i moved it to another useeffect to not call useeffect  unnecessarily

2022-07-21 09:47 UTC, shlomo-gangul commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/FloatingAddPluginMenu.tsx
> +    isModalOpen()
i have to make a call so it wont be true alll the time

2022-07-21 09:47 UTC, shlomo-gangul commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/FloatingAddPluginMenu.tsx
> +    setIsModalOpen(isModalOpen());
done

2022-07-21 12:22 UTC, danarish4 commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/FloatingAddPluginMenu.tsx
> +    });
```suggestion
```

We dont need it

2022-07-21 12:23 UTC, danarish4 commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/FloatingAddPluginMenu.tsx
> +    const isModalOpen = () => modalService.isModalOpen(MODAL_ID);
```suggestion
    const isModalOpen = modalService.isModalOpen(MODAL_ID);
```

2022-07-21 12:23 UTC, danarish4 commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/FloatingAddPluginMenu.tsx
> +    isModalOpen()
```suggestion
    isModalOpen
```

2022-07-21 12:23 UTC, danarish4 commented on packages/toolbars-v3/web/src/modals/FloatingPluginMenu/FloatingAddPluginMenu.tsx
> +    setIsModalOpen(isModalOpen);
```suggestion
    setIsModalOpen(!isModalOpen);
```

2022-07-21 12:24 UTC, danarish4 requested changes
.

2022-07-21 13:37 UTC, danarish4 approved these changes
😄

2022-07-21 13:43 UTC, merged