[ricos-plugins] plugin text buttons
wix/ricos pull request #4188
Opened 2022-07-14 13:36 UTC by noamtwix

2022-07-17 10:16 UTC, danarish4 commented on packages/ricos-plugins/web/src/editorPlugins.ts
> +    return textButtons.map(button => new PluginTextButton(button.getButton()));
not necessary -> new PluginTextButton(button.getButton()) === button
```suggestion
    return textButtons;
```

2022-07-17 10:18 UTC, danarish4 commented on packages/ricos-plugins/web/src/pluginTextButton.tsx
> +import type { IPluginTextButton, IToolbarItemConfigTiptap } from 'ricos-types';
Nothing is done in this class. It seems unnecessary to me

2022-07-17 10:18 UTC, danarish4 commented on packages/toolbars-v3/web/src/toolbarItemConfig/tiptapToolbarItemConfig.ts
> +  // {
remove comments

2022-07-17 10:19 UTC, danarish4 reviewed
I would remove `PluginTextButton` class for now and return plugin.textButtons

2022-07-17 12:25 UTC, danarish4 commented on packages/ricos-plugins/web/src/editorPlugin.ts
> +  }
```suggestion
```

no need to init anything

2022-07-17 12:25 UTC, danarish4 commented on packages/ricos-plugins/web/src/editorPlugin.ts
> +    this.initTextButtons(plugin);
```suggestion
```

2022-07-17 12:25 UTC, danarish4 commented on packages/ricos-plugins/web/src/editorPlugin.ts
> +    return this.textButtons || [];
```suggestion
    return this.plugin.textButtons || [];
```

2022-07-17 12:26 UTC, danarish4 commented on packages/ricos-plugins/web/src/editorPlugin.ts
> +  textButtons?: IToolbarItemConfigTiptap[];
```suggestion
```

2022-07-17 12:26 UTC, danarish4 requested changes
follow comments :)

2022-07-17 15:32 UTC, lxgreen requested changes

2022-07-17 15:32 UTC, lxgreen commented on packages/ricos-plugins/web/src/editorPlugins.ts
> +  }
What is the point to expose `IToolbarItemConfigTiptap[]`? What's its responsibility? 

Hint: who's responsible to order buttons accordingly to consumer config?

2022-07-17 15:32 UTC, lxgreen commented on packages/ricos-plugins/web/src/editorPlugin.ts
> +
What is the point to expose `IToolbarItemConfigTiptap[]`? What's its responsibility?

2022-07-18 09:26 UTC, merged

2022-07-19 10:09 UTC, lxgreen reviewed
1. file names
2. public types only in `ricos-types`
3. class methods
4. unused code

2022-07-19 10:09 UTC, lxgreen commented on packages/ricos-types/web/src/editorPluginTypes.ts
> +  /**
@noamtwix @danarish4 
please make sure that `ricos-types` contains public types only. seems like you put here all the model types that should be defined in `ricos-plugins` only.

2022-07-19 10:09 UTC, lxgreen commented on packages/ricos-plugins/web/src/editorPlugins.ts
> +    //maybe use filter class func
what's this comment for?

2022-07-19 10:09 UTC, lxgreen commented on packages/ricos-plugins/web/src/editorPlugins.ts
> +    );
see `Array.prototype.flatMap`

2022-07-19 10:09 UTC, lxgreen commented on packages/ricos-plugins/web/src/pluginTextButton.tsx
> +  }
what's the point to define both static `of` and public constructor? the `of` supposed to hide construction in some cases. 
Also, `of` (if used) supposed to be a public method of **aggregate root**. Your root here is `EditorPlugins` class. All the models are internal relative to it.

2022-07-19 10:09 UTC, lxgreen commented on packages/ricos-plugins/web/src/pluginTextButton.tsx
> +import type { IPluginTextButton, IPluginTextButtons, IToolbarItemConfigTiptap } from 'ricos-types';
please stop using `I` prefix for interfaces