Tiptap modals UI html height button values
wix/ricos pull request #4289
Opened 2022-07-28 14:46 UTC by shlomo-gangul

2022-08-03 11:29 UTC, maimonav commented on e2e/tests/__snapshots__/plugins.e2e.ts.snap
>            "textWrap": "wrap",
Why is this deleted?

2022-08-04 10:11 UTC, shlomo-gangul commented on e2e/tests/__snapshots__/plugins.e2e.ts.snap
>            "textWrap": "wrap",
reverted

2022-08-04 13:52 UTC, maimonav requested changes
Looks good 🔥 
Please update changelog

2022-08-07 11:12 UTC, maimonav approved these changes

2022-08-07 11:13 UTC, merged