[ricos-plugins] external alignment button
wix/ricos pull request #4322
Opened 2022-08-04 05:48 UTC by noamtwix

2022-08-04 13:21 UTC, noamtwix commented on packages/ricos-plugins/web/src/plugin-text-button.ts
> +      // 'alignment',
delete

2022-08-04 13:22 UTC, noamtwix commented on packages/toolbars-modals/web/libs/getSelectionTextAlignment/package.json
> +{
delete file

2022-08-04 13:23 UTC, noamtwix commented on packages/toolbars-modals/web/src/alignment/AlignmentPanelController.tsx
> +import React from 'react';
types

2022-08-04 13:28 UTC, noamtwix commented on packages/toolbars-modals/web/src/utils.tsx
> +};
delete

2022-08-07 12:33 UTC, maimonav requested changes

2022-08-07 12:33 UTC, maimonav commented on packages/toolbars-modals/web/src/alignment/consts.tsx
> +    dataHook: 'textAlignmentButton_justify',
@lxgreen I remember you talked about a new API for shortcuts, right?

2022-08-07 12:33 UTC, maimonav commented on packages/toolbars-modals/web/src/alignment/utils.tsx
> +};
Looks redundant, you can simply return 'left' in line 10, or am I missing something?

2022-08-07 12:33 UTC, maimonav commented on packages/toolbars-modals/web/src/panels/DesktopPanel.tsx
> +  theme?: any;
theme: any => RicosTheme?

2022-08-07 12:33 UTC, maimonav commented on packages/toolbars-modals/web/src/panels/DesktopPanel.tsx
> +  currentSelect?: any;
is there a type for other `any` type fields?

2022-08-07 13:58 UTC, noamtwix commented on packages/ricos-types/web/src/modalTypes.ts
>  }
yes

2022-08-07 14:11 UTC, noamtwix commented on packages/ricos-plugins/web/src/plugin-text-button.ts
> +      onClick: e => {
done

2022-08-07 14:11 UTC, noamtwix commented on packages/toolbars-modals/web/src/alignment/utils.tsx
> +};
done

2022-08-07 14:22 UTC, maimonav commented on packages/ricos-plugins/web/src/plugin-text-button.ts
> +                        referenceElement: e?.target,
If e is not passed, but the modal.layout === 'toolbar', what is the expected behavior?

2022-08-07 14:29 UTC, noamtwix commented on packages/ricos-plugins/web/src/plugin-text-button.ts
> +                        referenceElement: e?.target,
the model will be in the top left corner of the window

2022-08-07 14:56 UTC, merged