fix android enter bug
wix/ricos pull request #4360
Opened 2022-08-10 19:53 UTC by justame

2022-08-10 22:14 UTC, justame commented
@lxgreen I don't have a permission to Percy, can you take a look and let me know if it's safe to merge?

2022-08-11 05:06 UTC, oded-soffrin commented
Fixed on surge in my android 🤩🎉🎊

2022-08-11 10:13 UTC, lxgreen requested changes

2022-08-11 10:13 UTC, lxgreen commented on tsconfig.json
> +    "skipLibCheck": true,
i'd limit this flag to specific packages, using the tsconfig extensibility. let's talk

2022-08-11 10:18 UTC, lxgreen commented
@yaronn the resolver unit tests fail. this points to incompatibility we have to handle. `skipLibCheck` is dangerous way to go -- we just replace dependency versions and ignore type errors. The type incompatibility usually points to API incompatibility, and we don't know how many obscure bugs added.

2022-08-13 19:25 UTC, closed without merging