[video] resolve settings button visibility
wix/ricos pull request #4448
Opened 2022-08-22 14:47 UTC by tamrat-bay

2022-08-22 18:45 UTC, danarish4 commented on packages/plugin-video/web/src/getToolbarButtons.tsx
> +          resolve: () => !!config.shouldShowSpoiler,
```suggestion
          resolve: () => {
          const spoilerPlugin = services.plugins.asArray().find(plugins => plugin.type === spoiler)
          return !spoilerPlugin.getConfig().supportedPlugins || spoilerPlugin.getConfig().supportedPlugins.includes(video) 
          },
```

2022-08-22 18:47 UTC, danarish4 requested changes
You can use the `EditorPlugins` entity for checking if a spoiler plugin exists.
you can revert the changes in `helpers-config` file

2022-08-23 07:44 UTC, tamrat-bay commented on packages/plugin-video/web/src/getToolbarButtons.tsx
> +          resolve: () => !!config.shouldShowSpoiler,
we don't have plugins in services
services.plugins === undefined

2022-08-23 11:30 UTC, danarish4 commented on packages/plugin-video/web/src/getToolbarButtons.tsx
> +          resolve: () => !!config.shouldShowSpoiler,
It should be there
https://github.com/wix/ricos/blob/master/packages/ricos-types/web/src/services.ts#L13

2022-08-23 18:04 UTC, merged