[toolbars-v3] undo/redo - handle disabled
wix/ricos pull request #4451
Opened 2022-08-23 13:19 UTC by noamtwix

2022-08-23 19:47 UTC, maimonav requested changes

2022-08-23 19:47 UTC, maimonav commented on packages/ricos-plugins/web/src/plugin-text-button.ts
> +      isDisabled: () => !!attributes.disabled && !!content.resolve(attributes.disabled),
Please add this to `toToolbarItemConfig` as well.

2022-08-24 06:19 UTC, noamtwix commented on packages/ricos-plugins/web/src/plugin-text-button.ts
> +      isDisabled: () => !!attributes.disabled && !!content.resolve(attributes.disabled),
For what purpose?

2022-08-24 06:52 UTC, maimonav commented on packages/ricos-plugins/web/src/plugin-text-button.ts
> +      isDisabled: () => !!attributes.disabled && !!content.resolve(attributes.disabled),
For future buttons that will support disabled state, for example, undo/redo in mega toolbar or indent/outdent on code block.
It can also be added later on, what ever you think is best.

2022-08-24 06:55 UTC, maimonav commented
@noamtwix I've checked the undo/redo buttons, they are disabled but they are not appear disabled like draft, can you please check it also?

2022-08-24 08:02 UTC, merged