[ricos-schema, ricos-content]: add html type property to schema
wix/ricos pull request #4475
Opened 2022-08-25 08:27 UTC by talevy17

2022-09-11 09:23 UTC, danarish4 commented
@lxgreen @maimonav Can you approve please?

2022-09-11 10:07 UTC, lxgreen requested changes

2022-09-11 10:07 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_html.proto
> +    string html = 3;
are we sure no consumers have created content with the boolean isAdsense? it is breaking change, message indexed 4 has changed type from `boolean` to `Type`

2022-09-11 10:07 UTC, lxgreen commented on CHANGELOG.md
> +  - [#4475](https://github.com/wix/ricos/pull/4475) add `type: 'ADSENSE | HTML` property to html schema
this is lies. there's no such value `HTML` in `Type` enum

2022-09-11 10:07 UTC, lxgreen commented on packages/plugin-html/web/src/toolbar/EditHtmlButton.tsx
> +      isAdsense: node?.attrs?.type === HTMLData_Type.ADSENSE,
general question: why do you rely on tiptap content in UI components? @danarish4

2022-09-11 10:07 UTC, lxgreen commented on packages/plugin-html/web/src/getAddButtons.tsx
> +          type: HTMLData_Type.ADSENSE,
`type` is too overused and determining. i suggest to call this field `flavor`

2022-09-11 10:36 UTC, danarish4 commented on packages/plugin-html/web/src/toolbar/EditHtmlButton.tsx
> +      isAdsense: node?.attrs?.type === HTMLData_Type.ADSENSE,
To detremain whether to show AdSense subtitles or not

2022-09-11 11:11 UTC, oded-soffrin commented on packages/plugin-html/web/src/getAddButtons.tsx
> +          type: HTMLData_Type.ADSENSE,
remember it will be also LOTTIE in the future, and might have additional capabilities (like loading relevant scripts)
how about `origin` ? `provider` ? `source` ?

2022-09-11 11:14 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_html.proto
> +  optional Type type = 4;
+1

2022-09-11 11:25 UTC, talevy17 commented on packages/plugin-html/web/src/getAddButtons.tsx
> +          type: HTMLData_Type.ADSENSE,
I think I like `source` best

2022-09-11 11:51 UTC, oded-soffrin requested changes

2022-09-11 11:51 UTC, oded-soffrin commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_html.proto
> +    string html = 3;
we need to avoid breaking changes at all cost. it causes data corruption and it's very hard to fix.
please use deprecated as we did here -https://github.com/wix/ricos/blob/master/packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_app_embed.proto#L27

(also, at this point we not sure, wix-data can created that kind of content, as well as blog with conversion)

2022-09-11 12:41 UTC, talevy17 commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_html.proto
> +  optional Type type = 4;
I'm getting a compilation error `type is missing but is required in HTMLData` [here](https://github.com/wix/ricos/blob/fix/html-schema/packages/ricos-content/web/src/RicosContentAPI/node-builder-methods.ts#L154:L154) when I remove the optional operator

2022-09-11 12:41 UTC, talevy17 commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_html.proto
> +    string html = 3;
changed index to 5 and added deprecated to `is_adsense`

2022-09-11 12:41 UTC, talevy17 commented on CHANGELOG.md
> +  - [#4475](https://github.com/wix/ricos/pull/4475) add `type: 'ADSENSE | HTML` property to html schema
fixed

2022-09-11 12:42 UTC, talevy17 commented on packages/plugin-html/web/src/getAddButtons.tsx
> +          type: HTMLData_Type.ADSENSE,
changed to `Source:  source`

2022-09-13 08:06 UTC, maimonav commented on packages/ricos-content/web/src/converters/draft/fromDraft/convertRicosPluginData.ts
> +  config.isAdsense && (data.source = HTMLData_Source.ADSENSE);
Why do we set the `source` value in the converter? shouldn't it be already defined?

2022-09-13 08:08 UTC, maimonav commented on packages/ricos-content/web/statics/json/migratedFixtures/migration-content.json
> +        "source": "ADSENSE",
Can we use the `source` directly from schema? (HTMLData_Source.ADSENSE)

2022-09-13 08:10 UTC, maimonav commented on packages/ricos-content/web/statics/json/migratedFixtures/migration-content.json
> +        "source": "ADSENSE",
Nevermind, forgot this is generated.

2022-09-13 08:11 UTC, maimonav requested changes
Looks good :)

2022-09-13 08:14 UTC, maimonav approved these changes

2022-09-13 08:19 UTC, lxgreen requested changes

2022-09-13 08:19 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_html.proto
> +    ADSENSE = 0;
please fix this by adding `HTML = 0`

making `ADSENSE = 0` will make `ADSENSE` the **default value** of `source` field, in case it is undefined in content! i.e. by default, **source is always `ADSENSE`**

2022-09-13 08:27 UTC, talevy17 commented on CHANGELOG.md
> +  - [#4475](https://github.com/wix/ricos/pull/4475) add `type: 'ADSENSE | HTML` property to html schema
its no longer lies, reverting

2022-09-13 09:53 UTC, lxgreen approved these changes
good catch -- "Zusammenklappbare" should be just "Klappbare" in this case

2022-09-13 10:39 UTC, merged