[ricos-styles] fix: color decoration
wix/ricos pull request #4528
Opened 2022-08-30 11:25 UTC by maimonav

2022-08-30 19:55 UTC, lxgreen commented on packages/ricos-editor/web/src/tiptap/theme-defaults.ts
> +const defaultPalette = { bgColor: '#ffffff', textColor: '#000000' };
nice!

2022-08-30 20:02 UTC, lxgreen requested changes
some style questions

2022-08-30 20:02 UTC, lxgreen commented on packages/ricos-styles/web/src/decorations/color-decoration.ts
> +    const customStyle = pickBy({ color, backgroundColor });
and if you want remove `undefined`:
```
const customStyle = [color, background].filter(Boolean);
```

2022-08-30 20:02 UTC, lxgreen commented on packages/ricos-styles/web/src/decorations/color-decoration.ts
> +    const customStyle = pickBy({ color, backgroundColor });
lodash is bad

2022-08-31 07:06 UTC, maimonav commented on packages/ricos-styles/web/src/decorations/color-decoration.ts
> +    const customStyle = pickBy({ color, backgroundColor });
If it was the same result, I wouldn't add this change :)
The problem is that undefined is being added to the object, and when afterwards, the undefined overrides actual value.
Do you have a better style to remove undefined? I WOULD LOVE TO KNOW ABOUT IT

2022-08-31 07:06 UTC, maimonav commented on packages/ricos-styles/web/src/decorations/color-decoration.ts
> +    const customStyle = pickBy({ color, backgroundColor });
And you and me both, I'm not a fan of lodash

2022-08-31 10:26 UTC, merged