[ricos-plugins] external formatting toolbar support toolbar settings
wix/ricos pull request #4542
Opened 2022-09-01 13:13 UTC by noamtwix

2022-09-01 14:59 UTC, maimonav commented on packages/ricos-plugins/web/src/plugin-text-button.ts
> +    isMobile: boolean
No need to pass `isMobile` prop, you can access it via `this.services.context.isMobile`

2022-09-01 15:00 UTC, maimonav commented on packages/ricos-types/web/src/formatting-toolbar-buttons.ts
> +    isMobile: boolean
Please revert

2022-09-01 15:01 UTC, maimonav commented on packages/tiptap-editor/web/src/components/RichContentAdapter/RichContentAdapter.tsx
> +          services.context.isMobile
Please revert

2022-09-01 15:02 UTC, maimonav requested changes
Please follow the comments :)

2022-09-04 09:05 UTC, noamtwix commented on packages/ricos-plugins/web/src/plugin-text-button.ts
> +    isMobile: boolean
`services` is an entity of `PluginTextButton` and I need it in `PluginTextButtons`

2022-09-04 11:44 UTC, merged