chore(schema): Descriptions
wix/ricos pull request #4564
Opened 2022-09-05 06:22 UTC by oded-soffrin

Another fun task for this week is to document our whole schema to unblock blog
I started to process feel free to review, I'll make a commit with every file I'm done with

2022-09-11 20:53 UTC, lxgreen requested changes

2022-09-11 20:53 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/common.proto
> +    google.protobuf.StringValue line_height = 2; // CSS LineHeight value
unitless
```suggestion
    google.protobuf.StringValue line_height = 2; // CSS LineHeight value (unitless ratio)
```

2022-09-11 20:53 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/common.proto
> +        AUTO = 0; // Alignment will depend on the language
```suggestion
        AUTO = 0; // browser default, eqivalent to `initial`
```

2022-09-11 20:53 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/common.proto
> +        JUSTIFY = 4; // Stretches the lines so that each line has equal width (like in newspapers and magazines)
```suggestion
        JUSTIFY = 4; // Text is spaced to line up its left and right edges to the left and right edges of the line box, except for the last line
```

2022-09-11 20:53 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/common.proto
> +    google.protobuf.DoubleValue duration = 4; // Duration in seconds (when applied)
```suggestion
    google.protobuf.DoubleValue duration = 4; // Duration in seconds (relevant to audio/video)
```

2022-09-11 20:53 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/decoration_color.proto
> +    google.protobuf.StringValue background = 1; // CSS color value
```suggestion
    google.protobuf.StringValue background = 1; // hexadecimal background color
```

2022-09-11 20:53 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/decoration_color.proto
> +    google.protobuf.StringValue foreground = 2; // CSS color value
```suggestion
    google.protobuf.StringValue foreground = 2; // hexadecimal foreound color
```

2022-09-11 20:53 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_button.proto
> +            google.protobuf.StringValue text = 1; // text hex color
```suggestion
            google.protobuf.StringValue text = 1; // text hexadecimal color
```

2022-09-11 20:53 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_button.proto
> +            google.protobuf.StringValue border = 2; // border hex color
```suggestion
            google.protobuf.StringValue border = 2; // border hexadecimal color
```

2022-09-11 20:53 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_button.proto
> +            google.protobuf.StringValue background = 3; // background hex color
```suggestion
            google.protobuf.StringValue background = 3; // background hexadecimal color
```

2022-09-11 20:53 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_button.proto
> +        ACTION = 1; // Dynamic action button (need to be configured in consumption)
```suggestion
        ACTION = 1; // Triggers custom action that is defined in plugin configuration by the consumer
```

2022-09-11 20:53 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_collapsible_list.proto
> +    google.protobuf.BoolValue expand_only_one = 2; // Collapse all items upon expending new item
```suggestion
    google.protobuf.BoolValue expand_only_one = 2; // Allows to expand single item simultaneously

2022-09-11 20:53 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +    Type type = 1; // Gallry type
```suggestion
    Type type = 1; // Gallery layout type
```

2022-09-11 20:53 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_gallery.proto
> +    Type type = 1; // Gallry type
it's the layout Type enum from line 11, right?

2022-09-11 20:53 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_map.proto
> +  google.protobuf.DoubleValue lat = 6; // latitude
```suggestion
  google.protobuf.DoubleValue lat = 6; // Location latitude  
```

2022-09-11 20:53 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_map.proto
> +  google.protobuf.DoubleValue lng = 7; // longitude
```suggestion
  google.protobuf.DoubleValue lng = 7; // Location longitude
```

2022-09-12 09:33 UTC, maimonav commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/common.proto
> +    google.protobuf.BoolValue private = 4; // indicates whather the file source is public/private
whether* :)

2022-09-13 19:43 UTC, merged