[table] feat: formatting button
wix/ricos pull request #4602
Opened 2022-09-11 09:05 UTC by talevy17

2022-09-11 10:09 UTC, lxgreen commented on packages/ricos-editor/web/src/tiptap/RicosToolbars.tsx
> +  };
unacceptable. any service registration should be performed within orchestrator initialization flow, never in UI

2022-09-11 10:12 UTC, lxgreen requested changes

2022-09-11 10:12 UTC, lxgreen commented on packages/ricos-editor/web/src/tiptap/RicosToolbars.tsx
> +  };
the toolbar registration is big deal. please don't merge this PR before we talk. + @danarish4

2022-09-19 08:29 UTC, talevy17 commented on packages/ricos-editor/web/src/tiptap/RicosToolbars.tsx
> +  };
moved it to `ricos-plugins` more specifically `PluginTextButtons` (the same way we handle the plugin menu registration in `PluginAddButtons`). WDYT? @lxgreen

2022-10-23 13:46 UTC, merged