feat/table plugin menu
wix/ricos pull request #4633
Opened 2022-09-15 14:27 UTC by talevy17

2022-09-15 14:43 UTC, danarish4 commented on packages/plugin-table/web/src/tiptap/decorations/pluginMenuDecoration.ts
> +export const getPluginMenuDecoration = services => $cell => {
Do you have a reason for returning a callback?

2022-09-15 14:45 UTC, talevy17 commented on packages/plugin-table/web/src/tiptap/decorations/pluginMenuDecoration.ts
> +export const getPluginMenuDecoration = services => $cell => {
nope, shouldn't be a callback (:

2022-09-18 07:50 UTC, danarish4 requested changes
Please check if the click is on plugin add button instead of disable resizing plugin.

Bonus points 😄 :
Enable column resizing only from column handler

2022-09-18 07:50 UTC, danarish4 commented on packages/plugin-table/web/src/tiptap/plugins/columnResizingPlugin.tsx
> +  if (pluginState.activeHandle === -1 || pluginState.dragging || isCellEditingActive) return false;
```suggestion
  if (pluginState.activeHandle === -1 || pluginState.dragging || event.target.contains('pluginMenuButton')) return false;
```

2022-09-18 12:14 UTC, talevy17 commented on packages/plugin-table/web/src/tiptap/plugins/cellStatesPlugin.tsx
> +          const pluginMenuDecoration = getPluginMenuDecoration(services)(tablePluginState.editCell);
already changed its outdated

2022-09-19 14:02 UTC, talevy17 commented on packages/plugin-table/web/src/tiptap/plugins/columnResizingPlugin.tsx
> +  if (pluginState.activeHandle === -1 || pluginState.dragging || isCellEditingActive) return false;
redundant (:

2022-09-19 14:16 UTC, merged