editor-custom-style
wix/ricos pull request #4642
Opened 2022-09-18 18:39 UTC by tamrat-bay

2022-09-18 18:58 UTC, oded-soffrin commented
Notice how in groups the editor grows until it reaches its max height:

![editorHeight](https://user-images.githubusercontent.com/1297297/190923903-20e322b7-c548-40ad-8cde-4f25d7554358.gif)

this is the css they apply:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/1297297/190923959-da4c2b4d-2a38-4ab4-982c-1a1b34438a3f.png">


is it possible with this API ?

2022-09-18 19:45 UTC, tamrat-bay commented
> Notice how in groups the editor grows until it reaches its max height:
> 
> ![editorHeight](https://user-images.githubusercontent.com/1297297/190923903-20e322b7-c548-40ad-8cde-4f25d7554358.gif) [ ![editorHeight](https://user-images.githubusercontent.com/1297297/190923903-20e322b7-c548-40ad-8cde-4f25d7554358.gif) ](https://user-images.githubusercontent.com/1297297/190923903-20e322b7-c548-40ad-8cde-4f25d7554358.gif) [ ](https://user-images.githubusercontent.com/1297297/190923903-20e322b7-c548-40ad-8cde-4f25d7554358.gif)
> 
> this is the css they apply: <img alt="image" width="379" src="https://user-images.githubusercontent.com/1297297/190923959-da4c2b4d-2a38-4ab4-982c-1a1b34438a3f.png">
> 
> is it possible with this API ?

It's possible, we just need to give them the option of
min-height and max-height in the theme

 // customStyles : {editor : { minHeight: '200px' ,maxHeight: 'calc(100vh - 460px)' } }

2022-09-18 19:46 UTC, tamrat-bay commented on packages/ricos-types/web/src/themeTypes.ts
> +  height?: CSSProperties['height'];
add min & max options

2022-09-18 19:48 UTC, danarish4 commented on packages/tiptap-editor/web/src/statics/styles/tiptap-editor-styles.scss
> +// @import '~wix-rich-content-common/dist/statics/styles/palette';
please remove 
```suggestion
```

2022-09-18 19:51 UTC, danarish4 requested changes
Looks good 🔥 
Please add this new API to our docs 
https://ricos.js.org/docs/ricos/theming/#custom-styles

How did you check it? You can add an editor height option to the theme storybook
https://rich-content-storybook-master.surge.sh/?path=/story/theme--custom-styles

2022-09-19 07:31 UTC, tamrat-bay commented
> Looks good 🔥 Please add this new API to our docs [ricos.js.org/docs/ricos/theming/#custom-styles](https://ricos.js.org/docs/ricos/theming/#custom-styles)
> 
> How did you check it? You can add an editor height option to the theme storybook [rich-content-storybook-master.surge.sh/?path=/story/theme--custom-styles](https://rich-content-storybook-master.surge.sh/?path=/story/theme--custom-styles)

Currently, none of the theme are working in the storybook.
I passed the relevant property into the exampleApp and it looks great.

2022-09-19 08:31 UTC, danarish4 approved these changes
🔥

2022-09-19 08:37 UTC, merged

2022-09-19 08:47 UTC, maimonav commented
@tamrat-bay 
> Currently, none of the theme are working in the storybook.
Not accurate, storybook include some stories with theme, for example [here](https://rich-content-storybook-master.surge.sh/?path=/story/theme--palette) , you can also toggle between draft & tiptap.

2022-09-19 19:08 UTC, oded-soffrin commented
<img width="515" alt="image" src="https://user-images.githubusercontent.com/1297297/191096311-77f183c2-70c0-49f9-aa53-39356cc8e7ba.png">