[ui-components] collapse components
wix/ricos pull request #4674
Opened 2022-10-11 10:02 UTC by tamrat-bay

2022-11-08 14:38 UTC, tamrat-bay commented on packages/toolbars-modals/web/src/link/LinkComponents/LinkPanel.jsx
> +        label: t('LinkPanel_Noreferrer_Checkbox_Label'),
label keys - change on experiment toggle

2022-11-08 14:38 UTC, tamrat-bay commented on packages/toolbars-modals/web/src/link/LinkComponents/LinkPanel.jsx
> +        label: t('LinkPanel_Nofollow_Checkbox_Label'),
label keys - change on experiment toggle

2022-11-08 21:01 UTC, tamrat-bay commented on packages/toolbars-modals/web/src/link/LinkComponents/LinkPanel.jsx
> +        rel="noreferrer noopener"
noreferrer

2022-11-09 10:05 UTC, danarish4 commented on packages/editor-common/web/src/Components/LinkComponents/LinkPanel.jsx
> +                  dataHook="linkPanelRelCheckbox"
```suggestion
                  dataHook="linkPanelNofollowCheckbox"
```

2022-11-09 10:13 UTC, danarish4 commented on packages/toolbars-modals/web/src/link/LinkComponents/LinkPanel.jsx
> +    );
split to another file `LearnMoreLink`

2022-11-09 10:14 UTC, danarish4 commented on packages/toolbars-modals/web/src/link/LinkComponents/LinkPanel.jsx
> +    };
create `AdvancedSettings` component

2022-11-09 10:15 UTC, danarish4 requested changes
After merging this we need to remember to add BI & e2e

2022-11-09 14:12 UTC, merged