[schema] add FAQ to collapsible schema
wix/ricos pull request #4741
Opened 2022-11-02 07:23 UTC by tamrat-bay

2022-11-02 10:08 UTC, lxgreen commented on packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_collapsible_list.proto
> +    google.protobuf.BoolValue faq_enabled = 5; // If `true`, The collapsible item will appear in search results as an FAQ.
`is_qapage_data` is more correct. The whole feature aims to provide the FAQ schema structured data. The correct [technical term](https://developers.google.com/search/docs/appearance/structured-data/qapage) is `QAPage`

2022-11-02 10:10 UTC, lxgreen requested changes
see my comment

2022-11-02 13:07 UTC, maimonav commented
@tamrat-bay please add a test case to this such schema, in ricos-converters/collapsible-list converters (from/to tiptap).

2022-11-03 11:15 UTC, maimonav approved these changes
Looks good 🔥 , you're familiar with the [schema changes flow](https://bo.wix.com/pages/wix-ricos/docs/for-developers/schema-changes) right? @tamrat-bay

2022-11-03 16:11 UTC, merged