[*] return api
wix/ricos pull request #4752
Opened 2022-11-07 15:32 UTC by noamtwix

2022-11-12 20:45 UTC, lxgreen requested changes

2022-11-12 20:45 UTC, lxgreen commented on packages/tiptap-editor/web/src/components/RichContentAdapter.tsx
> +      overrideEnter: cb => {
rename to `enter`

2022-11-12 20:45 UTC, lxgreen commented on packages/ricos-types/web/src/shortcuts.ts
> +  register: (shortcut: KeyboardShortcut, override?: boolean) => void;
remove this

2022-11-12 20:45 UTC, lxgreen commented on packages/ricos-types/web/src/editorCommandsType.ts
> +  overrideEnter: (cb: () => void) => void;
`enter`

2022-11-12 20:45 UTC, lxgreen commented on packages/ricos-types/web/src/RicosTypes.ts
> +  customKeyboardShortcut?: KeyboardShortcut[];
rename to `keyboardShortcuts`

2022-11-12 20:45 UTC, lxgreen commented on packages/ricos-shortcuts/web/src/editor-keyboard-shortcuts.ts
> +  register(shortcut: KeyboardShortcut, override?: boolean) {
this whole issue caused by logic implemented in a wrong layer. 

you want to allow overrides by exposing the `shortcuts` prop. Any external shortcut provided by the user should override the internal shortcuts during merge:

```ts
 shortcuts = [...internal, ...external]
 ```
This merge logic should be performed in a proper time, as part of orchestration.  The main source of the shortcuts is plugins/extensions, so this merge should run after the plugin registration. Since we treat external  shortcuts differently, this should be reflected in model. The Shortcuts aggregate should expose a special method for it:

```ts
this.shortcuts.mergeWithCustomShortcuts(ricosProps.shortcuts);
```

2022-11-12 20:45 UTC, lxgreen commented on packages/ricos-shortcuts/web/src/editor-keyboard-shortcuts.ts
> +  register(shortcut: KeyboardShortcut, override?: boolean) {
of course, each external shortcut should have proper structure (it is user input, even if it is typed, they can do dirty tricks). You'll have to  validate the structure of each shortcut.

2022-11-12 20:45 UTC, lxgreen commented on packages/ricos-shortcuts/web/src/editor-keyboard-shortcuts.ts
> +      }
revert

2022-11-12 20:45 UTC, lxgreen commented on packages/ricos-orchestrator/web/src/ricos-orchestrator.ts
> +    const defaultKeyboardShortcuts: KeyboardShortcut[] = [
defaults should be placed in a proper entity. orchestrator is for sure not proper one.

2022-11-12 20:45 UTC, lxgreen commented on packages/ricos-orchestrator/web/src/ricos-orchestrator.ts
> +        name: 'Soft New Line (Cmd/Ctrl+Enter)',
name should not contain keys. there's `keys` field for keys

2022-11-12 20:45 UTC, lxgreen commented on packages/ricos-orchestrator/web/src/ricos-orchestrator.ts
> +        description: 'soft new line with Cmd+Enter / Ctrl+Enter',
description should not contain keys.

2022-11-12 20:45 UTC, lxgreen commented on packages/ricos-orchestrator/web/src/ricos-orchestrator.ts
> +import { merge } from 'lodash';
please remove this 💩 (i mean lodash, yes)

2022-11-12 20:45 UTC, lxgreen commented on packages/editor/web/src/RichContentEditor/EditorCommands.ts
> +    overrideEnter: _cb => {},
`enter`?

2022-11-12 20:45 UTC, lxgreen commented on packages/ricos-types/web/src/editorCommandsType.ts
> +  clearEditorContent: (triggerUpdate: boolean) => void;
WTF is this?

2022-11-12 20:45 UTC, lxgreen commented on packages/tiptap-extensions/web/src/hard-break.ts
> +          // 'Mod-Enter': () => this.editor.commands.setHardBreak(),
just remove the `shorcuts-enabled` group

2022-11-21 12:05 UTC, noamtwix commented on packages/ricos-types/web/src/shortcuts.ts
> +export type CustomKeyboardShortcut = Omit<KeyboardShortcut, 'keys'> & {
```suggestion
export type CustomizableKeyboardShortcut = Omit<KeyboardShortcut, 'keys'> & {
```

2022-11-21 12:09 UTC, noamtwix commented on packages/ricos-shortcuts/web/src/editor-keyboard-shortcuts.ts
> +  registerAndOverride(shortcut: KeyboardShortcut) {
```suggestion
  mergeKeyboadShortcutProp(shortcut: CustomizableKeyboardShortcut) {
```

2022-11-21 12:17 UTC, noamtwix commented on packages/tiptap-extensions/web/src/keymap.ts
> +import type { RicosExtension, NodeConfig, ExtensionProps, RicosServices } from 'ricos-types';
take the whole Keymap extension from tiptap

2022-11-21 12:19 UTC, noamtwix commented on packages/tiptap-extensions/web/src/keymap-override.ts
> +      priority: 2000,
try Math.infinity

2022-11-21 12:21 UTC, noamtwix commented on packages/tiptap-extensions/web/src/keymap-override.ts
> +        });
insert TODO: move to shortcut agregate

2022-11-22 10:15 UTC, merged